### PR TITLE
[BugFix] Fix ArrayIndexOutOfBoundsException in partial updates after ADD COLUMN

### LINKED ISSUE #2988: ArrayIndexOutOfBoundsException in partial updates after ADD COLUMN
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.9.0 (latest release)

### Please describe the bug 🐞

After ADD COLUMN, partial updates on existing rows crash with ArrayIndexOutOfBoundsException. ThePartialUpdater is created with the latest schema (4 fields) but reads old rows from RocksDB that were stored with the previous schema (3 fields). At field index 3, GenericRow.fields[3] throws on a 3-element array.

Reproduce: insert a row, ADD COLUMN, partial update the same row - crash.

### Solution

Use column IDs to align rows to the latest schema before the merger sees them

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by fresh-borzoni**
## Summary
closes #2988
relates to #2293

Partial updates crash with ArrayIndexOutOfBoundsException after ADD COLUMN, the PartialUpdater iterates over the latest schema's field count but old rows in RocksDB have fewer fields. 

The fix re-encodes rows to the latest schema layout using column IDs before the merger sees them, filling new columns with null.

Target column positions and incoming rows are also aligned via column IDs to support future schema operations beyond ADD COLUMN LAST

### CODE REVIEW

**Comment by fresh-borzoni** [comment]
@loserwang1024 @luoyuxia 
PTAL 🙏

File: fluss-server/src/main/java/org/apache/fluss/server/kv/KvTablet.java [hunk 1]
```diff
@@ -582,6 +618,74 @@ private long applyUpdate(
...
+            BinaryValue value, short latestSchemaId, Schema latestSchema) {
+        if (value.schemaId == latestSchemaId) {
+            return value;
+        }
+
+        Schema sourceSchema = schemaGetter.getSchema(value.schemaId);
+        List<Integer> sourceColIds = sourceSchema.getColumnIds();
+        List<Integer> targetColIds = latestSchema.getColumnIds();
+
+        Map<Integer, Integer> sourceIdToPos = new HashMap<>();
```
[the remark this answers is not in the document]
Comment (fresh-borzoni) [reply fluss-server/src/main/java/org/apache/fluss/server/kv/KvTablet.java]: The allocations only fire during schema transitions and are dominated by the RocksDB point lookup on the same path, not worth the complexity.

**Comment by fresh-borzoni** [comment]
Answered copilot comment

File: fluss-server/src/main/java/org/apache/fluss/server/kv/KvTablet.java [hunk 2]
```diff
@@ -582,6 +618,74 @@ private long applyUpdate(
...
+        for (int i = 0; i < sourceColIds.size(); i++) {
+            sourceIdToPos.put(sourceColIds.get(i), i);
+        }
+
+        InternalRow.FieldGetter[] sourceGetters =
+                InternalRow.createFieldGetters(sourceSchema.getRowType());
+        RowEncoder encoder = RowEncoder.create(kvFormat, latestSchema.getRowType());
```
Comment (polyzos) [inline fluss-server/src/main/java/org/apache/fluss/server/kv/KvTablet.java]: RowEncoder implements AutoCloseable but is never closed. Wrap in try-with-resources to avoid a resource leak on every aligned record.

File: fluss-server/src/main/java/org/apache/fluss/server/kv/KvTablet.java [hunk 3]
```diff
@@ -582,6 +618,74 @@ private long applyUpdate(
...
+        Schema sourceSchema = schemaGetter.getSchema(value.schemaId);
+        List<Integer> sourceColIds = sourceSchema.getColumnIds();
+        List<Integer> targetColIds = latestSchema.getColumnIds();
+
+        Map<Integer, Integer> sourceIdToPos = new HashMap<>();
+        for (int i = 0; i < sourceColIds.size(); i++) {
+            sourceIdToPos.put(sourceColIds.get(i), i);
+        }
+
+        InternalRow.FieldGetter[] sourceGetters =
```
Comment (polyzos) [inline fluss-server/src/main/java/org/apache/fluss/server/kv/KvTablet.java]: createFieldGetters and RowEncoder.create are called once per record, but for a batch, they are constant across all records sharing the same source schema. Maybe we can consider constructing them once per batch?

**Comment by fresh-borzoni** [comment]
@polyzos Thank you for the review
Addressed comments, PTAL 🙏

**Comment by polyzos** [comment]
LGTM.. thank you for your contribution

File: fluss-server/src/main/java/org/apache/fluss/server/kv/KvTablet.java [hunk 4]
```diff
@@ -628,6 +661,102 @@ private long applyUpdate(
...
+                // Column added after the source schema — fill with null.
+                ctx.encoder.encodeField(targetPos, null);
+            } else {
+                ctx.encoder.encodeField(
+                        targetPos, mapping.getters[sourcePos].getFieldOrNull(value.row));
+            }
+        }
+        // copy() is required: the encoder reuses its internal buffer, so the next
+        // startNewRow() would overwrite the row returned here.
+        return new BinaryValue(ctx.latestSchemaId, ctx.encoder.finishRow().copy());
```
Comment (wuchong) [inline fluss-server/src/main/java/org/apache/fluss/server/kv/KvTablet.java:724]: After schema evolution, every `oldValue` read from KV store with an older schema goes through `alignToLatestSchema`, which does a full field-by-field re-encode + `copy()`. The previous approach used `PaddingRow` as a zero-copy virtual view. This introduces a significant per-record overhead during the (potentially long) transition period when old-schema data still dominates the KV store.

File: fluss-server/src/main/java/org/apache/fluss/server/kv/KvTablet.java [hunk 5]
```diff
@@ -473,39 +488,50 @@ private void processKvRecords(
                 KvRecordReadContext.createReadContext(kvFormat, schemaGetter);
         ValueDecoder valueDecoder = new ValueDecoder(schemaGetter, kvFormat);
 
-        for (KvRecord kvRecord : kvRecords.records(readContext)) {
-            byte[] keyBytes = BytesUtils.toArray(kvRecord.getKey());
-            KvPreWriteBuffer.Key key = KvPreWriteBuffer.Key.of(keyBytes);
-            BinaryRow row = kvRecord.getRow();
-            BinaryValue currentValue = row == null ? null : new BinaryValue(schemaIdOfNewData, row);
+        try (SchemaAlignmentContext alignmentContext =
+                new SchemaAlignmentContext(latestSchemaId, latestSchema, kvFormat)) {
```
Comment (wuchong) [inline fluss-server/src/main/java/org/apache/fluss/server/kv/KvTablet.java:492]: `SchemaAlignmentContext` is created unconditionally on every `processKvRecords` call, even when `schemaIdOfNewData == latestSchemaId` (the common case — no schema evolution). This allocates a `RowEncoder` + `HashMap` on the hot path for every batch. Which will introduce performance regression.

**Comment by fresh-borzoni** [comment]
@wuchong Good judgement, thank you,  I prepared new PR: https://github.com/apache/fluss/pull/3000
