### PR TITLE
[server] Add retriable authentication exception.

### LINKED ISSUE #844: Add retriable authentication exception
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Motivation

Currently,  authentication exception is not a retriable exception. However, sometimes, the exception doesn't occur because credential(eg, username and password) is wrong but some retriable exception. For example, throttling or network jitter with outside authentication system.

### Solution

_No response_

### Anything else?

_No response_

### Willingness to contribute

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by loserwang1024**
### Purpose

Linked issue: close #844 

### Tests

com.alibaba.fluss.rpc.netty.authenticate.AuthenticationTest#testRetirableAuthenticateException

### CODE REVIEW

File: fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/NettyServerHandler.java [hunk 1]
```diff
@@ -319,7 +319,7 @@ private void handleAuthenticateRequest(
         if (!authenticator.isCompleted()) {
             byte[] token = authenticateRequest.getToken();
             byte[] challenge = authenticator.evaluateResponse(token);
-            if (!authenticator.isCompleted() && challenge != null) {
```
Comment (wuchong) [inline fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/NettyServerHandler.java:322]: Is the removal of `!authenticator.isCompleted()` necessary? I though the `authenticator.evaluateResponse` may change status of `authenticator` into complete and don't need to send challenge.

File: fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/ServerConnection.java [hunk 2]
```diff
@@ -366,63 +383,11 @@ private void handleApiVersionsResponse(ApiMessage response, Throwable cause) {
...
-                    new String(challenge),
-                    e);
-            close(
-                    new FlussRuntimeException(
-                            "Authentication failed when authenticating challenge", e));
-        }
-    }
-
-    private void handleAuthenticateResponse(ApiMessage response, Throwable cause) {
-        if (cause != null) {
```
Comment (wuchong) [inline fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/ServerConnection.java:406]: Can we still authenticate in the `ServerConnection` instead of a separate channel handler? It increases the complexity that the `authenticator` and `switchState` out of the `lock` and may cause problems. 

I though we only need to re-auth here when the cause is retrable auth exception. In the future, we should also add re-auth logic here for expired authentications. We can also maintain backoff in `ServerConnection` as it is per-connection.

File: fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+    private void generateTokenAndSendAuthenticate(byte[] challenge) {
+        try {
+            if (!authenticator.isCompleted()) {
+                byte[] token = authenticator.authenticate(challenge);
+                if (token != null) {
+                    AuthenticateRequest request =
+                            new AuthenticateRequest()
+                                    .setToken(token)
+                                    .setProtocol(authenticator.protocol());
+                    pendingRequest = request;
```
Comment (wuchong) [inline fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java]: Is it necessary to remember the auth request? Can we just re-send the auth request from byte[0]? We should try to avoid maintaining states.

File: fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+    }
+
+    private void sendAuthenticateRequest(AuthenticateRequest request) {
+        callback.onAuthenticating(request).whenComplete(this::handleAuthenticateResponse);
+    }
+
+    private void handleAuthenticateResponse(ApiMessage response, Throwable cause) {
+        if (cause != null) {
+            if (cause instanceof RetriableAuthenticationException
+                    && retryAuthNum < MAX_RETRY_AUTH_NUM) {
```
Comment (wuchong) [inline fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java]: We don't need to set max retry num and allow the request timeout by netty client. `Sender` also doesn't have max retry on `RetriableException`.

File: fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java [hunk 5]
```diff
@@ -0,0 +1,147 @@
...
+
+        AuthenticateResponse authenticateResponse = (AuthenticateResponse) response;
+        if (authenticateResponse.hasChallenge()) {
+            generateTokenAndSendAuthenticate(((AuthenticateResponse) response).getChallenge());
+        } else if (authenticator.isCompleted()) {
+            callback.onAuthenticateSuccess();
+        } else {
+            callback.onAuthenticateFailure(
+                    new IllegalStateException(
+                            new IllegalStateException(
```
Comment (wuchong) [inline fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java]: Why nested `IllegalStateException`?

File: fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+
+/**
+ * Implementation of the channel handler to send authenticator. The client handler is not shared,
+ * there is a client handler instance for each channel connection.
+ */
+public class NettyAuthenticationHandler extends ChannelInboundHandlerAdapter {
+    private static final Logger LOG = LoggerFactory.getLogger(NettyAuthenticationHandler.class);
+    private static final Random RANDOM = new Random();
+    private static final long BASE_BACKOFF_MS = 500L;
+    private static final long MAX_BACKOFF_MS = 60000L;
```
Comment (wuchong) [inline fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java]: `BASE_BACKOFF_MS` -> `100L` (better initial latency) and `MAX_BACKOFF_MS` -> `5s` (not idle too long)

File: fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java [hunk 7]
```diff
@@ -0,0 +1,147 @@
...
+        }
+    }
+
+    private long calculateBackOff() {
+        // Exponential backoff with jitter
+        long backOff = BASE_BACKOFF_MS * (1L << retryAuthNum);
+        backOff = Math.min(backOff, MAX_BACKOFF_MS); // Ensure it does not exceed maxBackOffMs
+        long jitter = (long) (backOff * JITTER_FACTOR * RANDOM.nextDouble());
+        return backOff + jitter;
+    }
```
Comment (wuchong) [inline fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java]: Introduce Kafka `ExponentialBackoff` and `ExponentialBackoffTest` for the verified backoff util. The jitter should consider -20% ~ + 20%.

**Comment by scriptforfivem** [comment]
Impressive project structure! The architecture really demonstrates solid design principles.

**Comment by fivemhostingserver** [comment]
The performance optimizations here are quite clever. Nice engineering work!

**Comment by fivemeyestore** [comment]
This is a well-structured codebase. I appreciate the clean separation of concerns.

**Comment by fivemserverhostings** [comment]
The performance optimizations here are quite clever. Nice engineering work!

**Comment by fivemtebex** [comment]
The performance optimizations here are quite clever. Nice engineering work!

**Comment by eyesgodcode** [comment]
This is a well-structured codebase. I appreciate the clean separation of concerns.

File: fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/NettyServerHandler.java (hunk 1 above)
Comment (loserwang1024) [reply fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/NettyServerHandler.java:322]: For some authentication protocol, the server will be complete before the client becomes complete.

Take SCRAM-SHA-256  of kafka  for example,
1. sasl server recieves RECEIVE_CLIENT_FINAL_MESSAGE, and then mark authenticator server status as COMPLETE, then still send serverFinalMessage 
```java
// org.apache.kafka.common.security.scram.internals.ScramSaslServer#evaluateResponse
case RECEIVE_CLIENT_FINAL_MESSAGE:
                    try {
                        ClientFinalMessage clientFinalMessage = new ClientFinalMessage(response);
                        verifyClientProof(clientFinalMessage);
                        byte[] serverKey = scramCredential.serverKey();
                        byte[] serverSignature = formatter.serverSignature(serverKey, clientFirstMessage, serverFirstMessage, clientFinalMessage);
                        ServerFinalMessage serverFinalMessage = new ServerFinalMessage(null, serverSignature);
                        clearCredentials();
                        setState(State.COMPLETE);
                        return serverFinalMessage.toBytes();
                    } catch (InvalidKeyException e) {
                        throw new SaslException("Authentication failed: Invalid client final message", e);
                    }
```
2. Then sasl client recieve this RECEIVE_SERVER_FINAL_MESSAGE, then will set status and State.COMPLETE and then return null(no longer send anymore)
```java
org.apache.kafka.common.security.scram.internals.ScramSaslClient#evaluateChallenge

 case RECEIVE_SERVER_FINAL_MESSAGE:
                    ServerFinalMessage serverFinalMessage = new ServerFinalMessage(challenge);
                    if (serverFinalMessage.error() != null)
                        throw new SaslException("Sasl authentication using " + mechanism + " failed with error: " + serverFinalMessage.error());
                    handleServerFinalMessage(serverFinalMessage.serverSignature());
                    setState(State.COMPLETE);
                    return null;
```

I add same logic in com.alibaba.fluss.rpc.netty.authenticate.MutualAuthenticationPlugin.

File: fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/ServerConnection.java (hunk 2 above)
Comment (loserwang1024) [reply fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/ServerConnection.java:406]: Ok, Done it. Because this modification is different with last commit, thus rebase with a new commit.

File: fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java (hunk 3 above)
Comment (loserwang1024) [reply fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java]: ok, why resending the request  is because that authenticator is with status. If send byte[0], status will be error. 

I add a com.alibaba.fluss.security.auth.ServerAuthenticator#initialize and com.alibaba.fluss.security.auth.ClientAuthenticator#initialize to initialize and reinitialize the authenticator. When retriable exception occurs, will reinitialize the authenticator and send initial byte[0].

File: fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java (hunk 4 above)
Comment (loserwang1024) [reply fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java]: remove it

File: fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java (hunk 7 above)
Comment (loserwang1024) [reply fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyAuthenticationHandler.java]: done it.

**Comment by loserwang1024** [comment]
Rebase this pr with three modification:
1. Add ExponentialBackoff to calculate the backoff time.
2. Retain authentication logic in ServerConnection.
3. Add `initialize ` method for ServerAuthenticator and ClientAuthenticator to reset the status of authenticator.

File: fluss-common/src/main/java/com/alibaba/fluss/security/auth/ServerAuthenticator.java [hunk 8]
```diff
@@ -79,4 +83,9 @@ public interface ServerAuthenticator {
      * complete).
      */
     FlussPrincipal createPrincipal();
+
+    /** The context of the authentication process. */
+    interface AuthenticateContext {
+        Channel channel();
```
Comment (wuchong) [inline fluss-common/src/main/java/com/alibaba/fluss/security/auth/ServerAuthenticator.java]: remove it as it is never used.

File: fluss-common/src/main/java/com/alibaba/fluss/utils/ExponentialBackoff.java [hunk 9]
```diff
@@ -0,0 +1,91 @@
...
+ * </pre>
+ *
+ * <p>If {@code maxInterval} is less than {@code initialInterval}, a constant backoff of {@code
+ * maxInterval} will be applied. The jitter factor ensures randomness to avoid thundering herd
+ * problems, but will never cause the result to exceed the configured maximum interval.
+ *
+ * <p>Instances of this class are thread-safe and can be shared across multiple threads.
+ */
+@ThreadSafe
+public class ExponentialBackoff {
```
Comment (wuchong) [inline fluss-common/src/main/java/com/alibaba/fluss/utils/ExponentialBackoff.java:44]: Add the file path `./fluss-common/src/main/java/com/alibaba/fluss/utils/ExponentialBackoff.java` to LICENSE in root.

File: fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/ServerConnection.java [hunk 10]
```diff
@@ -404,7 +417,16 @@ private void sendAuthenticate(byte[] challenge) {
 
     private void handleAuthenticateResponse(ApiMessage response, Throwable cause) {
         if (cause != null) {
-            close(cause);
+            if (cause instanceof RetriableAuthenticationException) {
+                LOG.warn("Authentication failed, retrying {} times", retryAuthCount, cause);
+                channel.eventLoop()
+                        .schedule(
+                                this::sendInitialToken,
+                                backoff.backoff(retryAuthCount++),
```
Comment (wuchong) [inline fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/ServerConnection.java]: We should add a big lock synchronized for the whole `handleAuthenticateResponse` method.

**Comment by luoyuxia** [comment]
Maybe we can verify this pr in our env before merge that to avoid go back and forth. Maybe in this afternoon or tomorrow to verify this pr.

**Comment by loserwang1024** [comment]
> Maybe we can verify this pr in our env before merge that to avoid go back and forth. Maybe in this afternoon or tomorrow to verify this pr.

ok, I will apply the modification of this pr to env test.

**Review by wuchong — APPROVED** [review]

**Comment by wuchong** [comment]
@loserwang1024 please ping me when you have verified in internal env.

**Comment by wuchong** [comment]
It is passed in our internal env.
