### PR TITLE
[client] Change the default value of 'client.lookup.max-retries' to Integer.MAX_VALUE

### LINKED ISSUE #2095: The default value of `client.lookup.max-retries` is too small for RetriableException
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.8.0 (latest release)

### Please describe the bug 🐞

The default value of `client.lookup.max-retries` is too small for `RetriableException`.  For `Sender`,  the default value of `client.writer.retries` is `Interge.MAX_VALUE`, which means that for a `RetriableException` returned by the server, it's reasonable to wait until the server recovers. I think the `LookupSender` should handle it in the same way as well. 

Currently, we don't yet support retries at the `Flink` level, but this could be considered for future implementation.

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by swuferhong**
### Purpose

Linked issue: close #2095 

Change the default value of 'client.lookup.max-retries' to Integer.MAX_VALUE

### CODE REVIEW

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/catalog/FlinkTableFactory.java [hunk 1]
```diff
@@ -243,12 +243,9 @@ private static Configuration toFlussClientConfig(
                     }
                 });
 
-        // map flink lookup.max-retries to client.lookup.max-retries
-        if (tableOptions.containsKey(LookupOptions.MAX_RETRIES.key())) {
-            flussConfig.setString(
-                    ConfigOptions.CLIENT_LOOKUP_MAX_RETRIES.key(),
-                    tableOptions.get(LookupOptions.MAX_RETRIES.key()));
-        }
+        // Todo support LookupOptions.MAX_RETRIES. Currently, Fluss doesn't support connector level
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/catalog/FlinkTableFactory.java:246]: create an issue for this, and tag as blocker for v0.9

**Review by wuchong — APPROVED** [review]

**Review by zhuangchong — APPROVED** [review]
+1
