### PR TITLE
[server] Fix rebalance may cause remote file deleted error

### LINKED ISSUE #2526: Rebalance may cause kv snapshot deleted by accident
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.8.0 (latest release)

### Please describe the bug 🐞

Just got a kv snapshot not exists exception after rebanlace  primary key table, still not know why, got the following message:

Image

The current leader for the bucket is 10
I got message in tablet server 10 for rebalance:
```
2026-01-26 17:24:10,579 INFO  org.apache.fluss.server.replica.Replica                      [] - Shrink ISR From [1, 2, 0, 16, 5, 10] to [10] for bucket TableBucket{tableId=7, partitionId=124, bucket=2}. Leader: (high watermark: 7660, end offset: 7660, out of sync replicas: [0, 16, 1, 2, 5])
```

It must be some servers delete the kv snapshot for this bucket, so I search such message globally, I got the following message from the tablet server 1
```
content:2026-01-26 17:24:10,624 INFO org.apache.fluss.server.kv.KvManager                         [] - Delete table's remote bucket snapshot dir of TableBucket{tableId=7, partitionId=124, bucket=2} success.
```

Seem the tablet server 1 mis-delete the kv snapshot for the bucket.

cc @swuferhong 
 

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by swuferhong**
### Purpose

Linked issue: close #2526

### CODE REVIEW

File: fluss-server/src/main/java/org/apache/fluss/server/coordinator/CoordinatorRequestBatch.java [hunk 1]
```diff
@@ -241,6 +241,7 @@ public void addStopReplicaRequestForTabletServers(
             Set<Integer> tabletServers,
             TableBucket tableBucket,
             boolean isDelete,
+            boolean deleteRemote,
```
Comment (wuchong) [inline fluss-server/src/main/java/org/apache/fluss/server/coordinator/CoordinatorRequestBatch.java]: rename `delete` to `deleteLocal`, and add comments to explain the parameters meaning.

File: fluss-server/src/main/java/org/apache/fluss/server/coordinator/CoordinatorRequestBatch.java [hunk 2]
```diff
@@ -255,7 +256,10 @@ public void addStopReplicaRequestForTabletServers(
                                             && stopBucketReplica.get(tableBucket).isDelete();
                             PbStopReplicaReqForBucket protoStopReplicaForBucket =
                                     makeStopBucketReplica(
-                                            tableBucket, alreadyDelete || isDelete, leaderEpoch);
+                                            tableBucket,
+                                            alreadyDelete || isDelete,
+                                            deleteRemote,
```
Comment (wuchong) [inline fluss-server/src/main/java/org/apache/fluss/server/coordinator/CoordinatorRequestBatch.java]: Do we need to reduce the `deleteRemote` like `isDelete`?

File: fluss-rpc/src/main/proto/FlussApi.proto [hunk 3]
```diff
@@ -900,6 +900,7 @@ message PbStopReplicaReqForBucket {
   required PbTableBucket table_bucket = 1;
   required int32 leader_epoch = 2;
   required bool delete = 3;
+  optional bool deleteRemote = 4;
```
Comment (wuchong) [inline fluss-rpc/src/main/proto/FlussApi.proto:908]: Add a comment to clarify the behavioral difference between `delete` and `deleteRemote`:

- `delete` removes **local replica data** (i.e., data stored on the current node).
- `deleteRemote` deletes **remote bucket data** (e.g., data in object storage) and was introduced in **v0.9**.

For backward compatibility, if a request does not include the `deleteRemote` flag, the system treats `delete` as `deleteRemote` (i.e., it falls back to remote deletion). This ensures older. CoordinatorServer continues to function correctly with newer TabletServers.

File: fluss-server/src/test/java/org/apache/fluss/server/coordinator/rebalance/RebalanceManagerITCase.java [hunk 4]
```diff
@@ -97,16 +118,141 @@ void testBuildClusterModel() throws Exception {
...
+        // remote log not be deleted.
+        int newLeader = planForBucket.getNewLeader();
+        TabletServer leaderTs = FLUSS_CLUSTER_EXTENSION.getTabletServerById(newLeader);
+        RemoteLogManager leaderRm = leaderTs.getReplicaManager().getRemoteLogManager();
+        RemoteLogTablet leaderRlt = leaderRm.remoteLogTablet(tb);
+
+        RemoteLogManifest newManifest = leaderRlt.currentManifest();
+        assertThat(newManifest.getPhysicalTablePath().getTablePath()).isEqualTo(DATA1_TABLE_PATH);
+        assertThat(newManifest.getTableBucket()).isEqualTo(tb);
+        assertThat(newManifest.getRemoteLogSegmentList().size()).isGreaterThan(0);
```
Comment (wuchong) [inline fluss-server/src/test/java/org/apache/fluss/server/coordinator/rebalance/RebalanceManagerITCase.java]: assert the size is the same with preivous size?

File: fluss-server/src/main/java/org/apache/fluss/server/log/remote/RemoteLogManager.java [hunk 5]
```diff
@@ -387,4 +388,9 @@ private static void shutdownAndAwaitTermination(
     public RemoteLogIndexCache getRemoteLogIndexCache() {
         return remoteLogIndexCache;
     }
+
+    @VisibleForTesting
+    public @Nullable TaskWithFuture getTaskWithFuture(TableBucket tableBucket) {
```
Comment (wuchong) [inline fluss-server/src/main/java/org/apache/fluss/server/log/remote/RemoteLogManager.java]: package visible is enough.

File: fluss-server/src/test/java/org/apache/fluss/server/log/remote/RemoteLogManagerTest.java [hunk 6]
```diff
@@ -497,10 +504,78 @@ void testStopReplica(boolean partitionTable) throws Exception {
...
+    void testStopReplicaDeleteRemoteLog(boolean partitionTable, boolean deleteRemote)
+            throws Exception {
+        TableBucket tb = makeTableBucket(partitionTable);
+        // Need to make leader by ReplicaManager.
+        makeLogTableAsLeader(tb, partitionTable);
+        LogTablet logTablet = replicaManager.getReplicaOrException(tb).getLogTablet();
+        addMultiSegmentsToLogTablet(logTablet, 5);
+        // trigger RLMTask copy local log segment to remote and update metadata.
+        remoteLogTaskScheduler.triggerPeriodicScheduledTasks();
+        RemoteLogTablet remoteLog = remoteLogManager.remoteLogTablet(tb);
```
Comment (wuchong) [inline fluss-server/src/test/java/org/apache/fluss/server/log/remote/RemoteLogManagerTest.java]: can remove

File: fluss-server/src/test/java/org/apache/fluss/server/log/remote/RemoteLogManagerTest.java [hunk 7]
```diff
@@ -497,10 +504,78 @@ void testStopReplica(boolean partitionTable) throws Exception {
...
+
+        CompletableFuture<List<StopReplicaResultForBucket>> future2 = new CompletableFuture<>();
+        replicaManager.stopReplicas(
+                0,
+                Collections.singletonList(new StopReplicaData(tb, true, deleteRemote, 0, 0)),
+                future2::complete);
+        assertThat(future2.get()).containsOnly(new StopReplicaResultForBucket(tb));
+        hostedReplica = replicaManager.getReplica(tb);
+        assertThat(hostedReplica).isInstanceOf(ReplicaManager.NoneReplica.class);
+        if (!deleteRemote) {
```
Comment (wuchong) [inline fluss-server/src/test/java/org/apache/fluss/server/log/remote/RemoteLogManagerTest.java:570]: assert `logTablet.getLogDir()` is also deleted?

File: fluss-server/src/main/java/org/apache/fluss/server/replica/ReplicaManager.java [hunk 8]
```diff
@@ -1715,6 +1716,7 @@ private void maybeShrinkIsr() {
     private StopReplicaResultForBucket stopReplica(
             TableBucket tb,
             boolean delete,
+            boolean deleteRemote,
```
Comment (wuchong) [inline fluss-server/src/main/java/org/apache/fluss/server/replica/ReplicaManager.java]: Rename `delete` to `deleteLocal`, and add comment to explain the parameters.

File: fluss-server/src/main/java/org/apache/fluss/server/entity/StopReplicaData.java [hunk 9]
```diff
@@ -24,13 +24,19 @@
...
     private final boolean delete;
+    private final boolean deleteRemote;
     private final int coordinatorEpoch;
     private final int leaderEpoch;
 
     public StopReplicaData(
-            TableBucket tableBucket, boolean delete, int coordinatorEpoch, int leaderEpoch) {
+            TableBucket tableBucket,
+            boolean delete,
+            boolean deleteRemote,
```
Comment (wuchong) [inline fluss-server/src/main/java/org/apache/fluss/server/entity/StopReplicaData.java:34]: rename `delete` to `deleteLocal`, and add comments to explain the parameters meaning.

File: fluss-server/src/main/java/org/apache/fluss/server/coordinator/statemachine/ReplicaState.java [hunk 10]
```diff
@@ -48,6 +48,14 @@ public Set<ReplicaState> getValidPreviousStates() {
             return EnumSet.of(NewReplica, OnlineReplica, OfflineReplica);
         }
     },
+    ReplicaMigrateSuccessful {
```
Comment (wuchong) [inline fluss-server/src/main/java/org/apache/fluss/server/coordinator/statemachine/ReplicaState.java]: Rename the state to `ReplicaMigrationStarted`. This indicates that replica migration has been initiated for the replica, but has not yet completed successfully. Once the migration succeeds, the state should transition directly to `NonExistentReplica`.

File: fluss-server/src/main/java/org/apache/fluss/server/coordinator/statemachine/ReplicaStateMachine.java [hunk 11]
```diff
@@ -307,17 +308,36 @@ private void doHandleStateChanges(
...
+                                    false,
+                                    coordinatorContext.getBucketLeaderEpoch(
+                                            tableBucketReplica.getTableBucket()));
+                        });
+                break;
             case ReplicaDeletionStarted:
                 validReplicas.forEach(
                         replica -> doStateChange(replica, ReplicaState.ReplicaDeletionStarted));
-                // send stop replica request with delete = true
+                // send stop replica request with delete = true and delete = true indicates the
```
Comment (wuchong) [inline fluss-server/src/main/java/org/apache/fluss/server/coordinator/statemachine/ReplicaStateMachine.java]:
```suggestion
                // send stop replica request with deleteLocal = true and deleteRemote = true indicates the
```

File: fluss-server/src/main/java/org/apache/fluss/server/utils/ServerRpcMessageUtils.java [hunk 12]
```diff
@@ -716,11 +716,12 @@ public static List<NotifyLeaderAndIsrResultForBucket> getNotifyLeaderAndIsrRespo
     }
 
     public static PbStopReplicaReqForBucket makeStopBucketReplica(
-            TableBucket tableBucket, boolean isDelete, int leaderEpoch) {
+            TableBucket tableBucket, boolean isDelete, boolean deleteRemote, int leaderEpoch) {
```
Comment (wuchong) [inline fluss-server/src/main/java/org/apache/fluss/server/utils/ServerRpcMessageUtils.java]: rename `delete` to `deleteLocal`, and add comments to explain the parameters meaning.

File: fluss-server/src/main/java/org/apache/fluss/server/utils/ServerRpcMessageUtils.java [hunk 13]
```diff
@@ -739,6 +740,9 @@ public static List<StopReplicaData> getStopReplicaData(StopReplicaRequest reques
                     new StopReplicaData(
                             toTableBucket(tableBucket),
                             reqForBucket.isDelete(),
+                            reqForBucket.hasDeleteRemote()
+                                    ? reqForBucket.isDeleteRemote()
+                                    : reqForBucket.isDelete(),
```
Comment (wuchong) [inline fluss-server/src/main/java/org/apache/fluss/server/utils/ServerRpcMessageUtils.java:759]: add comment for the backward compatibility explanation.

**Comment by swuferhong** [comment]
LGTM.

**Comment by swuferhong** [comment]
Hi, @wuchong. I've locally tested rebalance for log table and the KV table with remote data—everything looks good. I'll go ahead and merge it. Thanks for your review.
