### PR TITLE
[server] Fix zk partition residual when using dynamic partition

### LINKED ISSUE #1185: Dynamic partition create redundant partition assignment in Zookeeper
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

main (development)

### Please describe the bug 🐞

Reproduce steps:
1. Create a partitioned table
2. Insert into table with enough data and trigger dynamic partition using Flink.
3. In my case, these data are partitioned into 24 partitions.
4. In ZK path : /metadata/databases/[databaseName]/tables/[tableName]/partitions   **24 partitions** created.
However, in ZK path /tabletservers/partitions/[partitionId]  **32 partitions** created.
5. Drop table in Flink. 24 partitions are successfully deleted but 8 partitions are residual in ZK.

It seems a thread unsafe issue.

### Solution

Although we found it in dynamic partition scene, it is not only concern with dynamic partition. It happens when more than one client try to create partition with the same table id and the same partition name at the same time (which usually occurs in dynamic partition).

`com.alibaba.fluss.server.coordinator.MetadataManager#createPartition
`
This method is not thread safe, even though it checks if partition exists before registers to zk.
Thread 1: 
t1: check zk for partition name 「x」  -> t2: register to zk
Thread 2: 
t3: check zk for partition name 「x」-> t4: register to zk
t1 and t3 can happen in the same time.
t2 and t4 can happen in the same time.

```
try {
	long partitionId = zookeeperClient.getPartitionIdAndIncrement();
	// register partition assignments to zk first
	zookeeperClient.registerPartitionAssignment(
	        partitionId, partitionAssignment);
	// then register the partition metadata to zk
	zookeeperClient.registerPartition(
	        tablePath, tableId, partitionName, partitionId);
	LOG.info(
	        "Register partition {} to zookeeper for table [{}].",
	        partitionName,
	        tablePath);
}
```

Thus "registerPartitionAssignment" call twice because partition id is different 
but "zookeeperClient.registerPartition" call once because they share the zk node.
That is why 
In zk path : /metadata/databases/[databaseName]/tables/[tableName]/partitions   **24 partitions** created.
However, in zk path /tabletservers/partitions/[partitionId]  **32 partitions** created.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by zcoo**
### Purpose

Linked issue: close #1185

### CODE REVIEW

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java [hunk 1]
```diff
@@ -385,78 +393,97 @@ public void createPartition(
...
+                    } catch (Exception e) {
+                        throw new FlussRuntimeException(
+                                String.format(
+                                        "Register partition to zookeeper failed to create partition %s for table [%s]",
+                                        partitionName, tablePath),
+                                e);
+                    }
+                });
+        if (!lock.isLocked() && lock.getQueueLength() == 0) {
+            createPartitionLockMap.remove(physicalTablePath, lock);
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java]: If any exception happens in above `inLock(xxx` cde fragement, this lock won't be removed..

Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java]: Considering the following case:
- Thread A come to here, is going to remove the lock1
- Thread B acquired the lock1 in https://github.com/alibaba/fluss/pull/1187/files#diff-4623210f8554fe6ea208a8dfc413f997d6d10b8c64cfc3aa530f3620ddbd09ccR401
- Thread A remove the lock1 from the map
- Thread C find no lock for the partition, try to create lock2
There still race in Thread B & Thread C.

TBH, I'm not still thinking out a good way to solve it. Maybe a guava cache?

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java [hunk 2]
```diff
@@ -385,78 +393,97 @@ public void createPartition(
...
+                                String.format(
+                                        "Failed to check total bucket count for table %s",
+                                        tablePath),
+                                e);
+                    }
+
+                    try {
+                        long partitionId = zookeeperClient.getPartitionIdAndIncrement();
+                        // register partition assignments to zk first
+                        zookeeperClient.registerPartitionAssignment(
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java]: Can we wrap `registerPartitionAssignment` and `registerPartition` into a zk transation? We let zk to do the concurrent controll so that we won't need the lock. We will have clean code. 
The only bad is that we may fire mutiple zk transation for same partition. But it shouldn't happen frequently, so I think it's fine since the current implemenation also will fire mutiple zk operations for same partition.

**Review by luoyuxia — COMMENTED** [review]
@zcoo Thanks for the pr. Left some comments. PTAL

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java (hunk 2 above)
Comment (zcoo) [reply fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java]: very valuable suggestion. I have changed the solution.

**Comment by zcoo** [comment]
@luoyuxia Thanks! I refactor my code to solve problem by using zk transaction instead of Lock Map! PLAT

File: fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java [hunk 3]
```diff
@@ -519,6 +519,62 @@ public void deletePartition(TablePath tablePath, String partitionName) throws Ex
         zkClient.delete().forPath(path);
     }
 
+    /** Register partition assignment and metadata in transaction. */
+    public void registerPartitionAssignmentAndMetadata(
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java:502]: with this method, we can remove methods `registerPartition` & `registerPartitionAssignment`

**Review by luoyuxia — COMMENTED** [review]
@zcoo Thanks for update. Only one comment. Otherwise, LGTM!

File: fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java (hunk 3 above)
Comment (zcoo) [reply fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java:502]: yes!
