### PR TITLE
Fix union read paimon issue

### LINKED ISSUE #2168: Fix issue in union read
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.8.0 (latest release)

### Please describe the bug 🐞

During testing union read paimon, I found some critial issues:
- for partitioned table, if partition key is the first field of primary key, union read will return wrong result
- if some buckets don't have lake data, exception will be thrown, and the batch union read will never finish

### Solution

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by luoyuxia**
### Purpose

Linked issue: close #2168

### CODE REVIEW

**Comment by luoyuxia** [comment]
@beryllw Fix some issue during testing I found. I'll add test later

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/lake/reader/LakeSnapshotAndLogSplitScanner.java [hunk 1]
```diff
@@ -192,23 +192,26 @@ public CloseableIterator<InternalRow> pollBatch(Duration timeout) throws IOExcep
             return currentSortMergeReader.readBatch();
         } else {
             if (lakeRecordIterators.isEmpty()) {
+                List<RecordReader> recordReaders = new ArrayList<>();
                 if (lakeSnapshotSplitAndFlussLogSplit.getLakeSplits() == null
                         || lakeSnapshotSplitAndFlussLogSplit.getLakeSplits().isEmpty()) {
-                    lakeRecordIterators = Collections.emptyList();
-                    logRows = new LinkedHashMap<>();
```
Comment (luoyuxia) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/lake/reader/LakeSnapshotAndLogSplitScanner.java:198]: ProjectedRow doesn't support hash & equal. It'll throw exception if come to here.

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/lake/LakeSplitReaderGenerator.java [hunk 2]
```diff
@@ -55,8 +55,16 @@ public void addSplit(SourceSplitBase split, Queue<SourceSplitBase> boundedSplits
...
+            LakeSnapshotAndFlussLogSplit lakeSnapshotAndFlussLogSplit =
+                    (LakeSnapshotAndFlussLogSplit) split;
+            boolean isStreaming = ((LakeSnapshotAndFlussLogSplit) split).isStreaming();
+            // if is streaming and lake split not finished, add to it
+            if (isStreaming) {
+                if (!lakeSnapshotAndFlussLogSplit.isLakeSplitFinished()) {
+                    boundedSplits.add(split);
+                }
+            } else {
+                // otherwise, in batch mode, always add it
```
Comment (luoyuxia) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/lake/LakeSplitReaderGenerator.java:67]: in batch mode, we need to add it. otherwise, the split won't never be read & mark as finished.

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/lake/reader/SortMergeReader.java [hunk 3]
```diff
@@ -300,12 +307,27 @@ public void close() {
 
         @Override
         public boolean hasNext() {
-            return changeLogRecordIterator != null && changeLogRecordIterator.hasNext();
```
Comment (luoyuxia) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/lake/reader/SortMergeReader.java:303]: the next will be delete row.

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/FlinkSourceEnumerator.java [hunk 4]
```diff
@@ -680,6 +688,7 @@ private void handleSplitsAdd(List<SourceSplitBase> splits, Throwable t) {
                         t);
             }
         }
+        doHandleSplitsAdd(splits);
```
Comment (luoyuxia) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/FlinkSourceEnumerator.java:691]: handle split firstly before mark noMoreNewSplits to true

**Comment by beryllw** [comment]
LGTM
