### PR TITLE
[flink] Immediately throw Exception in mailbox executor  rather than wait until next record in flink sink writer.

### LINKED ISSUE #735: Immediately throw Exception in mailbox executor  rather than wait until next record in flink sink writer.
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Motivation

In currently flink sink, `checkAsyncException` is trigger by newly coming record or checkpoint. It's better to  throw Exception in mailbox executor  rather than wait until next record in flink sink writer.

### Solution

_No response_

### Anything else?

_No response_

### Willingness to contribute

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by loserwang1024**
### Purpose

Linked issue: close #735 

### Tests

Add some failover test in FlinkSinkWriterTest.

### CODE REVIEW

**Comment by loserwang1024** [comment]
@wuchong @swuferhong , CC

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriter.java [hunk 1]
```diff
@@ -123,6 +130,18 @@ public void write(RowData value, Context context) throws IOException, Interrupte
 
         InternalRow internalRow = sinkRow.replace(value);
         CompletableFuture<?> writeFuture = writeRow(value.getRowKind(), internalRow);
+        writeFuture.whenComplete(
```
Comment (luoyuxia) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriter.java:133]: Just wondering what's the problem if checkAsyncException in writing new rows?

File: fluss-flink/fluss-flink-common/src/test/resources/log4j2-test.properties [hunk 2]
```diff
@@ -16,7 +16,7 @@
 
 # Set root logger level to OFF to not flood build logs
 # set manually to INFO for debugging purposes
-rootLogger.level = OFF
+rootLogger.level = DEBUG
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/test/resources/log4j2-test.properties]: revert it

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriter.java [hunk 3]
```diff
@@ -123,6 +130,18 @@ public void write(RowData value, Context context) throws IOException, Interrupte
...
+                (ignored, throwable) -> {
+                    if (throwable != null) {
+                        if (this.asyncWriterException == null) {
+                            this.asyncWriterException = throwable;
+                        }
+
+                        // Checking for exceptions from previous writes
+                        // Checking for exceptions from previous writes
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriter.java]: remove the duplicated comment

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriter.java [hunk 4]
```diff
@@ -123,6 +130,18 @@ public void write(RowData value, Context context) throws IOException, Interrupte
...
+                        mailboxExecutor.execute(this::checkAsyncException, "Update error metric");
+                    }
+                });
         writeFuture.exceptionally(
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriter.java]: This can be removed now?

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriter.java (hunk 1 above)
Comment (loserwang1024) [reply fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriter.java:133]: Two reasons:
1. case 1: The KafkaWriter flushing needs to wait for all in-flight records to send successfully. What if one record is stuck for some reason, the job will be stuck.
2. case 2: If data is little, the failover will be thrown at a long time later. (if the former is a window, a heavy calculate will be replay.)

File: fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriterTest.java [hunk 5]
```diff
@@ -0,0 +1,210 @@
...
+                                        while (mailboxExecutor.tryYield()) {
+                                            // execute all mails
+                                        }
+                                    })
+                            .hasRootCauseExactlyInstanceOf(NetworkException.class);
+                });
+    }
+
+    private void testExceptionWhenFlussUnavailable(
+            BiConsumer<FlinkSinkWriter, MailboxExecutor> actionAfterFlussUnavailable)
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriterTest.java:162]: The `actionAfterFlussUnavailable` is not used.

File: fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriterTest.java [hunk 6]
```diff
@@ -0,0 +1,210 @@
...
+            throws Exception {
+        FlussClusterExtension flussClusterExtension = FlussClusterExtension.builder().build();
+        flussClusterExtension.start();
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriterTest.java]: use `try ... catch ... finally` to make sure the `flussClusterExtension` is closed if any exception is thrown in the middle.

File: fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriterTest.java [hunk 7]
```diff
@@ -0,0 +1,210 @@
...
+                            .hasRootCauseExactlyInstanceOf(NetworkException.class);
+                });
+    }
+
+    @Test
+    void testMailBoxExceptionWhenFlussUnavailable() throws Exception {
+        testExceptionWhenFlussUnavailable(
+                (writer, mailboxExecutor) -> {
+                    writer.getTableWriter().flush();
+                    writer.getTableWriter().flush();
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriterTest.java:150]: remove the duplicated flush

File: fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriterTest.java [hunk 8]
```diff
@@ -0,0 +1,210 @@
...
+                            .hasRootCauseExactlyInstanceOf(NetworkException.class);
+                });
+    }
+
+    @Test
+    void testFlushExceptionWhenFlussUnavailable() throws Exception {
+        testExceptionWhenFlussUnavailable(
+                (writer, mailboxExecutor) -> {
+                    writer.getTableWriter().flush();
+                    assertThatThrownBy(() -> writer.flush(true))
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/sink/writer/FlinkSinkWriterTest.java:127]: Add some comment for the tests that why the lines will throw exception, but `tableWriter#flush()` doesn't.

**Review by wuchong — COMMENTED** [review]
Please add an IT case that only insert one row into a shutdown cluster and expects job failover.

**Review by wuchong — APPROVED** [review]
