### PR TITLE
[lake/paimon] Compare paimon schema and Fluss schema before alter table.

### LINKED ISSUE #2330: Compare Paimon schema and Fluss schema when alter table.
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.8.0 (latest release)

### Please describe the bug 🐞

When altering a table, compare the Paimon schema with the Fluss schema. If the schemas are not identical, throw an exception. If the Paimon schema is broader than the Fluss schema, verify whether multiple changes are idempotent.

### Solution

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by loserwang1024**
### Purpose

Linked issue: close #2330

### CODE REVIEW

File: fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/PaimonLakeCatalog.java [hunk 1]
```diff
@@ -133,69 +138,118 @@ public void alterTable(TablePath tablePath, List<TableChange> tableChanges, Cont
...
+            if (flussColumns.size() + tableChanges.size() != paimonFields.size()) {
+                throw new InvalidAlterTableException(errorMsg);
+            }
+
+            for (int i = 0; i < paimonFields.size() - flussColumns.size(); i++) {
+                DataField paimonDataField = paimonFields.get(i + flussColumns.size());
+                TableChange tableChange = tableChanges.get(i);
+                if (!(tableChange instanceof TableChange.AddColumn
+                        && ((TableChange.AddColumn) tableChange).getPosition()
+                                == TableChange.ColumnPosition.last()
```
Comment (beryllw) [inline fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/PaimonLakeCatalog.java]: Maybe we could perform this check earlier—it’s not related to the existing Paimon schema. Also, it’s already validated here:
https://github.com/apache/fluss/blob/256bd7f3838a72965720eb2a8c6c7c0575f46b07/fluss-server/src/main/java/org/apache/fluss/server/coordinator/SchemaUpdate.java#L101-L104

File: fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/PaimonLakeCatalog.java [hunk 2]
```diff
@@ -133,69 +138,118 @@ public void alterTable(TablePath tablePath, List<TableChange> tableChanges, Cont
...
+                        && isColumnAlreadyExists(
+                                paimonDataField, (TableChange.AddColumn) tableChange))) {
+                    throw new InvalidAlterTableException(errorMsg);
```
Comment (beryllw) [inline fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/PaimonLakeCatalog.java]: Maybe we could split the checks and provide distinct error messages to help users more easily identify issues related to the Paimon schema.

File: fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/PaimonLakeCatalog.java (hunk 1 above)
Comment (loserwang1024) [reply fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/PaimonLakeCatalog.java]: @beryllw 

> It’s not related to the existing Paimon schema

If paimon schema is same as fluss schema, all the operations(both add column and set config) can be accepted. Otherwise, only add columns can be accepted to make the schema same.

**Comment by wuchong** [comment]
@loserwang1024 as we discussed offline, we can refactor the implementation to reuse the logic of `PaimonTableValidation#validatePaimonSchemaCompatible` instead of checking fields by fields.

**Comment by wuchong** [comment]
@loserwang1024 the test coverage of `PaimonLakeCatalog` is failed, could you run `PaimonLakeCatalogTest` with coverage and improve the line coverage of `PaimonLakeCatalog` by adding tests `PaimonLakeCatalogTest`? 


```
Warning:  Rule violated for class org.apache.fluss.lake.paimon.PaimonLakeCatalog: lines covered ratio is 0.57, but expected minimum is 0.70
```

image

**Comment by loserwang1024** [comment]
@wuchong some old codes are remained, I have removed them
