### PR TITLE
[hotfix] Fix unstable testIOExceptionShouldStopTabletServer

### LINKED ISSUE #739: TabletServerFailOverITCase.testIOExceptionShouldStopTabletServer is not stable
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.6.0 (latest release)

### Please describe the bug 🐞

It failed in this PR build.
https://github.com/alibaba/fluss/actions/runs/14406439668/job/40404028187?pr=738

The tablet server doesn't stop after an exception
> [INFO] 
> [INFO] Results:
> [INFO] 
> Error:  Failures: 
> Error:    TabletServerFailOverITCase.testIOExceptionShouldStopTabletServer:101 [Tablet server number should be 2] 
> expected: 2
>  but was: 3
> [INFO] 

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by luoyuxia**
### Purpose

Linked issue: close #739

### Brief change log

I found in `testIOExceptionShouldStopTabletServer`, it'll try to write data to a old tablet server. Then I found `newTabletServerClientForNode` will get the client for old server. We should use `Map` to keep `tabletServerInfos` instead of `List` which will cause it contains two different serverNodes with same tablet id

### CODE REVIEW

File: fluss-server/src/test/java/com/alibaba/fluss/server/tablet/TabletServerFailOverITCase.java [hunk 1]
```diff
@@ -88,7 +88,6 @@ void testIOExceptionShouldStopTabletServer(boolean isLogTable) throws Exception
                         .waitAndGetLeaderReplica(tb)
                         .getLogTablet()
                         .activeLogSegment();
-        logSegment.flush();
```
Comment (luoyuxia) [inline fluss-server/src/test/java/com/alibaba/fluss/server/tablet/TabletServerFailOverITCase.java:91]: Don't need flush in testing..

File: fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java [hunk 2]
```diff
@@ -115,7 +115,7 @@ public final class FlussClusterExtension
     private File tempDir;
 
     private final Map<Integer, TabletServer> tabletServers;
-    private final List<ServerInfo> tabletServerInfos;
+    private final Map<Integer, ServerInfo> tabletServerInfos;
```
Comment (luoyuxia) [inline fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java:118]: Use `List<ServerInfo> tabletServerInfos` will cause two `ServerInfo` with same tablet server id which will then cause `newTabletServerClientForNode` retrun a client connecting to old ServerNode.

**Review by wuchong — APPROVED** [review]
Good catch!
