### PR TITLE
[kv] when table(partition) is deleted, drop corresponding snapshots

### LINKED ISSUE #412: CompletedSnapshotStoreManager miss to remove the table buckets for dropped table
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.5.0 (latest release)

### Please describe the bug 🐞

When the table/partition is dropped, CompletedSnapshotStoreManager won't remove the table buckets of the dropped table which will cause momory leak..

### Solution

When table & partition is listened by `CoordinatorEventProcessor` to be deleted,  `completedSnapshotStoreManager` should remove these buckets.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by zcoo**
### Purpose

Linked issue: close #412 

Currently, when kv table is deleted or table partition is expired, memory still persist its kv snapshot, which causes memory leak. This pr will fix it.
### Tests

**CompletedSnapshotStoreManagerTest::testRemoveCompletedSnapshotStoreFromManager**

### CODE REVIEW

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManager.java [hunk 1]
```diff
@@ -96,6 +97,14 @@ public CompletedSnapshotStore getOrCreateCompletedSnapshotStore(TableBucket tabl
                 });
     }
 
+    public void onRemoveCompletedSnapshotStoreByTableBuckets(Set<TableBucket> tableBuckets) {
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManager.java]: nit:
```suggestion
    public void removeCompletedSnapshotStoreByTableBuckets(Set<TableBucket> tableBuckets) {
```
to make the naming style align with `createCompletedSnapshotStore`

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManager.java [hunk 2]
```diff
@@ -96,6 +97,14 @@ public CompletedSnapshotStore getOrCreateCompletedSnapshotStore(TableBucket tabl
...
+        // Remove CompletedSnapshotStore is all we need to do, as remote KV files have already
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManager.java]: I think we can remove theres comments since it may not precise for the root directory of table snapshot  will be drop in coordinator server.

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessor.java [hunk 3]
```diff
@@ -499,6 +499,12 @@ private void processCreatePartition(CreatePartitionEvent createPartitionEvent) {
     }
 
     private void processDropTable(DropTableEvent dropTableEvent) {
+        // When drop a table, drop its snapshot store meanwhile.
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessor.java]: Only when the table is a primary key table, do we need to remove snapshot store
```
// When drop a primary key table, drop its snapshot store meanwhile.
        if (coordinatorContext.getTableInfo(dropTableEvent.getTableId()).hasPrimaryKey()) {
            Set<TableBucket> deleteTableBuckets =
                    coordinatorContext.getAllBucketsForTable(dropTableEvent.getTableId());
            completedSnapshotStoreManager.onRemoveCompletedSnapshotStoreByTableBuckets(
                    deleteTableBuckets);
        }
```

You'll need to add a method `getTableInfo` in `CoordinatorContext`

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessor.java [hunk 4]
```diff
@@ -510,6 +516,14 @@ private void processDropPartition(DropPartitionEvent dropPartitionEvent) {
         TablePartition tablePartition =
                 new TablePartition(
                         dropPartitionEvent.getTableId(), dropPartitionEvent.getPartitionId());
+
+        // When drop a table partition, drop its snapshot store meanwhile.
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessor.java]: dito:
Only when the table is a primary key table, do we need to remove snapshot store

**Review by luoyuxia — COMMENTED** [review]
@zcoo Thanks for the pr.. I left some comments..
Also, we need to add test to verify when table/partition is dropped, the completeSnapshotStore will also be removed in `CoordinatorEventProcessorTest`.

**Comment by zcoo** [comment]
@luoyuxia  thanks a lot for your opinion! I've tried to fix. 

PTAL~

File: fluss-common/src/main/java/com/alibaba/fluss/metadata/TableInfo.java [hunk 5]
```diff
@@ -149,6 +149,11 @@ public boolean hasPrimaryKey() {
         return !primaryKeys.isEmpty();
     }
 
+    /** Check if the table is a primary key table or a log table. */
+    public boolean isPrimaryKeyTable() {
```
Comment (luoyuxia) [inline fluss-common/src/main/java/com/alibaba/fluss/metadata/TableInfo.java]: if `hasPrimaryKey` return true, it means it's a primaryKeyTable. We don't need to introduce this method.

File: fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessorTest.java [hunk 6]
```diff
@@ -612,12 +627,45 @@ void testCreateAndDropPartition() throws Exception {
...
                 replicationFactor);
 
+        // mock CompletedSnapshotStore for partition1 and partition2
+        Set<TableBucket> tableBuckets4partition1 =
+                coordinatorContext.getAllBucketsForPartition(tableId, partition1Id);
+        Set<TableBucket> tableBuckets4partition2 =
+                coordinatorContext.getAllBucketsForPartition(tableId, partition2Id);
+        int sizeofCompletedSnapshotStore4partition1 = 0;
+        int sizeofCompletedSnapshotStore4partition2 = 0;
+        for (TableBucket tableBucket : tableBuckets4partition1) {
```
Comment (luoyuxia) [inline fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessorTest.java:633]: nit:
We can just mock `completedSnapshotStore` for the partition1 which is to be drop to simlify the test

**Review by luoyuxia — COMMENTED** [review]
@zcoo Thanks for updating.. Left minor comments. should be ready to be merged in next iteration.

**Comment by zcoo** [comment]
@luoyuxia I've simplify the code. Thanks for code review!

**Review by luoyuxia — APPROVED** [review]
