### PR TITLE
[server] Support max partition number of a table

### LINKED ISSUE #687: Support max partition number of a table
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Description

The suggested implementation steps:

1. Introduce a cluster level config: `max.partition.num`: Limits the maximum number of partitions that can be created for a  partitioned table to avoid creating too many partitions. Default 1000?
2. Add `TooManyPartitionsException` in `com.alibaba.fluss.exception` which is an `ApiException`, and register to `com.alibaba.fluss.rpc.protocol.Errors`.
3. Add the method `getPartitionNumber(TablePath tablePath)` in `ZooKeeperClient`. The implementation should use `zkClient.checkExists().forPath(path)` to get `numChildren` from `org.apache.zookeeper.data.Stat`, instead of listing all children.
4. Checks the current partition number of this table is not exceed the configured max number in `com.alibaba.fluss.server.coordinator.MetadataManager#createPartition`. Otherwise, throws `TooManyPartitionsException`.
5. `com.alibaba.fluss.server.coordinator.AutoPartitionManager#createPartitions` should catch `TooManyPartitionsException` to log warning. 
6. Add tests in `FlussAdminITCase` to verify the expected exception when create too many partitions.
7. Add tests in `AutoPartitionManagerTest` to verify new partitions will not created if it reaches max number of partitions. 

### Willingness to contribute

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by caozhen1937**
### Purpose

Linked issue: close #687

### CODE REVIEW

File: fluss-common/src/main/java/com/alibaba/fluss/config/ConfigOptions.java [hunk 1]
```diff
@@ -119,6 +119,14 @@ public class ConfigOptions {
...
                                     + "The default value is 10 minutes.");
 
+    public static final ConfigOption<Integer> MAX_PARTITION_NUM =
+            key("max.partition.num")
+                    .intType()
+                    .defaultValue(1000)
+                    .withDescription(
+                            "Limits the maximum number of partitions that can be created for a partitioned table "
+                                    + "to avoid creating too many partitions.");
+
```
Comment (wuchong) [inline fluss-common/src/main/java/com/alibaba/fluss/config/ConfigOptions.java:129]: Please also update the documentation, page https://alibaba.github.io/fluss-docs/docs/maintenance/configuration/#common

File: fluss-common/src/main/java/com/alibaba/fluss/exception/TooManyPartitionsException.java [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.alibaba.fluss.exception;
+
+/** This exception is thrown if the number of table partitions is exceed max.partition.num. */
```
Comment (wuchong) [inline fluss-common/src/main/java/com/alibaba/fluss/exception/TooManyPartitionsException.java]:
```suggestion
/**
 * This exception is thrown if the number of table partitions is exceed max.partition.num.
 *
 * @since 0.7
 */
@PublicEvolving
```

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java [hunk 3]
```diff
@@ -343,6 +347,23 @@ public void createPartition(
                             partition.getPartitionQualifiedName(), tablePath));
         }
 
+        try {
+            int partitionNumber = zookeeperClient.getPartitionNumber(tablePath);
+            int configMaxSize = conf.get(ConfigOptions.MAX_PARTITION_NUM);
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java]: get and store the config value in the constructor, instead of storing `conf` and get the value every time.

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/AutoPartitionManager.java [hunk 4]
```diff
@@ -250,6 +251,11 @@ private void createPartitions(
                         "Auto partitioning skip to create partition {} for table [{}] as the partition is exist.",
                         partition,
                         tablePath);
+            } catch (TooManyPartitionsException t) {
+                LOG.warn(
+                        "Auto partitioning skip to create partition {} for table [{}], "
+                                + "because exceed the maximum number of partitions.",
+                        tablePath);
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/AutoPartitionManager.java:264]: missing `partition` parameter for the partition placeholder.

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java [hunk 5]
```diff
@@ -343,6 +347,23 @@ public void createPartition(
...
+                        String.format(
+                                "Exceed the maximum number of partitions for table %s", tablePath));
+            }
+        } catch (TooManyPartitionsException e) {
+            throw e;
+        } catch (Exception e) {
+            LOG.error(
+                    "Get the number of partition from zookeeper failed for table [{}]",
+                    tablePath,
+                    e);
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java:365]: We should throw the exception to allow users (CoordinatorService) know the partition creation failed (like how `createTable` does). The following exception catch should also be removed. In the `AutoPartitionManager`, we should catch the exception and log error messages.

File: fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/AutoPartitionManagerTest.java [hunk 6]
```diff
@@ -242,6 +249,26 @@ void testAddPartitionedTable(TestParams params) throws Exception {
...
+
+        // create too many partitions
+        int expectPartitionNumber = params.expectedPartitionsFinal.length;
+        Configuration config = new Configuration();
+        config.set(ConfigOptions.MAX_PARTITION_NUM, expectPartitionNumber);
+        MetadataManager metadataManager = new MetadataManager(zookeeperClient, config);
+
+        assertThatThrownBy(
+                        () ->
+                                metadataManager.createPartition(
```
Comment (wuchong) [inline fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/AutoPartitionManagerTest.java]: The test here is not targeting `AutoPartitionManager` but rather `MetadataManager` (this has been covered by `FlussAdminITCase`). Our goal is to verify that new partitions will not be created if `AutoPartitionManager` reaches the maximum number of partitions. You can add a new test method instead of relying on the parameterized test, for example (update `createPartitionedTable` to accept `numToRetain` parameter for `TABLE_AUTO_PARTITION_NUM_RETENTION` config):

```java
@Test
    void testMaxPartitions() throws Exception {
        ZonedDateTime startTime =
                LocalDateTime.parse("2024-09-10T00:00:00").atZone(ZoneId.systemDefault());
        long startMs = startTime.toInstant().toEpochMilli();
        ManualClock clock = new ManualClock(startMs);
        ManuallyTriggeredScheduledExecutorService periodicExecutor =
                new ManuallyTriggeredScheduledExecutorService();

        AutoPartitionManager autoPartitionManager =
                new AutoPartitionManager(
                        new TestingMetadataCache(3),
                        metadataManager,
                        new Configuration(),
                        clock,
                        periodicExecutor);
        autoPartitionManager.start();

        // create a partitioned with -1 retention to never auto-drop partitions
        TableInfo table = createPartitionedTable(-1, AutoPartitionTimeUnit.DAY);
        TablePath tablePath = table.getTablePath();
        autoPartitionManager.addAutoPartitionTable(table);
        // the first auto-partition task is a non-periodic task
        periodicExecutor.triggerPeriodicScheduledTasks();

        Map<String, Long> partitions = zookeeperClient.getPartitionNameAndIds(tablePath);
        // pre-create 4 partitions including current partition
        assertThat(partitions.keySet())
                .containsExactlyInAnyOrder("20240910", "20240911", "20240912", "20240913");

        // manually create 4 future partitions.
        int replicaFactor = table.getTableConfig().getReplicationFactor();
        Map<Integer, BucketAssignment> bucketAssignments =
                TableAssignmentUtils.generateAssignment(
                                table.getNumBuckets(), replicaFactor, new int[] {0, 1, 2})
                        .getBucketAssignments();
        long tableId = table.getTableId();
        PartitionAssignment partitionAssignment =
                new PartitionAssignment(tableId, bucketAssignments);
        for (int i = 20250101; i <= 20250104; i++) {
            metadataManager.createPartition(
                    tablePath,
                    tableId,
                    partitionAssignment,
                    fromPartitionName(table.getPartitionKeys(), i + ""),
                    false);
            // mock the partition is created in zk.
            autoPartitionManager.addPartition(tableId, i + "");
        }

        clock.advanceTime(Duration.ofDays(4));
        periodicExecutor.triggerPeriodicScheduledTasks();
        partitions = zookeeperClient.getPartitionNameAndIds(tablePath);
        assertThat(partitions.keySet())
                .containsExactlyInAnyOrder(
                        "20240910",
                        "20240911",
                        "20240912",
                        "20240913",
                        // only 20240914, 20240915 are created in this round
                        "20240914",
                        "20240915",
                        // 20250101 ~ 20250102 are retained
                        "20250101",
                        "20250102",
                        "20250103",
                        "20250104");
    }
```

File: fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java [hunk 7]
```diff
@@ -408,6 +408,13 @@ public Optional<TablePartition> getPartition(TablePath tablePath, String partiti
         return getOrEmpty(path).map(PartitionZNode::decode);
     }
 
+    /** Get partition num of a table in ZK. */
+    public int getPartitionNumber(TablePath tablePath) throws Exception {
+        String path = PartitionsZNode.path(tablePath);
+        Stat stat = zkClient.checkExists().forPath(path);
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java:414]: Add proection for empty node (no partition created under the path), otherwise, it will throw NPE

```
        if (stat == null) {
            return 0;
        }
```

**Review by wuchong — CHANGES_REQUESTED** [review]

**Comment by caozhen1937** [comment]
@wuchong Thank you for the review, comments addressed.

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/AutoPartitionManager.java [hunk 8]
```diff
@@ -250,6 +252,14 @@ private void createPartitions(
...
+                LOG.warn(
+                        "Auto partitioning skip to create partition {} for table [{}], "
+                                + "because exceed the maximum number of partitions.",
+                        partition,
+                        tablePath);
+            } catch (FlussRuntimeException f) {
+                LOG.warn(f.getMessage());
             }
 
             currentPartitions.add(partition.getPartitionName());
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/AutoPartitionManager.java]: We should move this into the above try catch, otherwise, the state of `currentPartitions` is not correct.

**Review by wuchong — APPROVED** [review]
I pushed a commit to fix the above comment. Will merge once the CI is passed.
