### PR TITLE
[client]Support initial cluster with retries to avoid initial failed when bootstrap server only contains one available address

### LINKED ISSUE #2014: FlussConnection getTable method fails due to missing retries when fetching metadata
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.8.0 (latest release)

### Please describe the bug 🐞

FlussConnection getTable method fails due to missing retries when fetching metadata：

```
java.lang.IllegalArgumentException: table: xxx not found in cluster
	at org.apache.fluss.cluster.Cluster.lambda$getTableOrElseThrow$2(Cluster.java:260)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.apache.fluss.cluster.Cluster.getTableOrElseThrow(Cluster.java:257)
	at org.apache.fluss.client.metadata.MetadataUpdater.getTableInfoOrElseThrow(MetadataUpdater.java:100)
	at org.apache.fluss.client.FlussConnection.getTable(FlussConnection.java:103)
	at org.apache.fluss.flink.sink.writer.FlinkSinkWriter.initialize(FlinkSinkWriter.java:112)
	at org.apache.fluss.flink.sink.writer.AppendSinkWriter.initialize(AppendSinkWriter.java:53)
	at org.apache.fluss.flink.sink.FlinkSink.createWriter(FlinkSink.java:63)
	at org.apache.flink.streaming.runtime.operators.sink.StatelessSinkWriterStateHandler.createWriter(StatelessSinkWriterStateHandler.java:39)
	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.initializeState(SinkWriterOperator.java:170)
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.initializeOperatorState(StreamOperatorStateHandler.java:122)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:285)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:106)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:843)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:790)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:747)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:959)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:928)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:751)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:567)
	at java.lang.Thread.run(Thread.java:879)
```

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by swuferhong**
### Purpose

Linked issue: close #2014 

Support initial cluster with retries to avoid initial failed when bootstrap server only contains one available address.  Currently, retries are only applied to errors on the allowlist: `StaleMetadataException` and `NetworkException`, as these two types of errors may occur during machine upgrades.

### CODE REVIEW

File: fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java [hunk 1]
```diff
@@ -293,7 +296,18 @@ private static Cluster initializeCluster(Configuration conf, RpcClient rpcClient
         Exception lastException = null;
         for (InetSocketAddress address : inetSocketAddresses) {
             try {
-                cluster = tryToInitializeCluster(rpcClient, address);
+                ServerNode serverNode =
+                        new ServerNode(
+                                -1,
```
Comment (wuchong) [inline fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java:302]: We should `.disconnect()` with the bootstrap server id, otherwise, the second retry will still use the old server host. If the bootstrap server is a SLB, this makes the SLB doesn't work.

File: fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java [hunk 2]
```diff
@@ -316,14 +330,54 @@ private static Cluster initializeCluster(Configuration conf, RpcClient rpcClient
...
-    private static Cluster tryToInitializeCluster(RpcClient rpcClient, InetSocketAddress address)
+    @VisibleForTesting
+    static @Nullable Cluster tryToInitializeClusterWithRetries(
+            InetSocketAddress address, AdminReadOnlyGateway gateway, int maxRetryTimes)
+            throws Exception {
+        int retryCount = 0;
+        while (retryCount <= maxRetryTimes) {
+            try {
+                return tryToInitializeCluster(gateway);
+            } catch (Exception e) {
```
Comment (wuchong) [inline fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java:357]: Instead of retrying only the first bootstrap server, the client should attempt to connect to all provided bootstrap servers before sleeping and retrying. For example, if a user specifies three bootstrap servers and only the first one is unavailable, the client should immediately try the second (or third) server—rather than repeatedly retrying the failed one—improving connection resilience and startup latency.

Comment (swuferhong) [reply fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java:357]: Agreed. I have change this to two separate code paths: the retry logic is only applied when there is exactly one bootstrap server address.

**Comment by swuferhong** [comment]
@wuchong comments addressed.

File: fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java [hunk 3]
```diff
@@ -316,14 +335,61 @@ private static Cluster initializeCluster(Configuration conf, RpcClient rpcClient
...
+                    throw e;
+                }
+
+                if (retryCount >= maxRetryTimes) {
+                    LOG.warn(
+                            "Max retries ({}) exceeded to connect to {}. ",
+                            maxRetryTimes,
+                            serverNode,
+                            e);
+                    return null;
```
Comment (wuchong) [inline fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java]: We don't need to logging, we should throw the exception and let the parent method catch it. Otherwise, the root exception is swallowed in the exception message.

File: fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java [hunk 4]
```diff
@@ -316,14 +335,61 @@ private static Cluster initializeCluster(Configuration conf, RpcClient rpcClient
...
+            try {
+                return tryToInitializeCluster(gateway);
+            } catch (Exception e) {
+                Throwable cause = stripExecutionException(e);
+                if (!(cause instanceof StaleMetadataException
+                        || cause instanceof NetworkException)) {
+                    throw e;
+                }
+
+                if (retryCount >= maxRetryTimes) {
```
Comment (wuchong) [inline fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java]: Add comment above `// in case of bootstrap is recovering, we should retry to connect`

File: fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java [hunk 5]
```diff
@@ -293,8 +296,24 @@ private static Cluster initializeCluster(Configuration conf, RpcClient rpcClient
...
+                    cluster =
+                            tryToInitializeClusterWithRetries(
+                                    rpcClient, serverNode, adminReadOnlyGateway, MAX_RETRY_TIMES);
+                } else {
+                    cluster = tryToInitializeCluster(adminReadOnlyGateway);
+                    break;
+                }
             } catch (Exception e) {
                 LOG.error(
                         "Failed to initialize fluss client connection to bootstrap server: {}",
```
Comment (wuchong) [inline fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java]: We should improve this exception message, it didn't carry exception message to the top error message which may confuse users. 

```
            String errorMsg =
                    "Failed to initialize fluss client connection to bootstrap servers: "
                            + inetSocketAddresses
                            + ". \nReason: "
                            + lastException.getMessage();
```

File: fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java [hunk 6]
```diff
@@ -56,12 +57,14 @@
 import java.util.stream.Collectors;
 
 import static org.apache.fluss.client.utils.MetadataUtils.sendMetadataRequestAndRebuildCluster;
+import static org.apache.fluss.utils.ExceptionUtils.stripExecutionException;
 
 /** The updater to initialize and update client metadata. */
 public class MetadataUpdater {
     private static final Logger LOG = LoggerFactory.getLogger(MetadataUpdater.class);
 
     private static final int MAX_RETRY_TIMES = 5;
```
Comment (wuchong) [inline fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java]: Do we need so many retry times? 3 times is enough?

File: fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java [hunk 7]
```diff
@@ -293,8 +296,24 @@ private static Cluster initializeCluster(Configuration conf, RpcClient rpcClient
...
+                    // if there is only one bootstrap server, we can retry to connect to it.
+                    cluster =
+                            tryToInitializeClusterWithRetries(
+                                    rpcClient, serverNode, adminReadOnlyGateway, MAX_RETRY_TIMES);
+                } else {
+                    cluster = tryToInitializeCluster(adminReadOnlyGateway);
+                    break;
+                }
             } catch (Exception e) {
                 LOG.error(
```
Comment (wuchong) [inline fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java:325]: We should `.disconnect()` here as well? for the case of `tryToInitializeCluster` failed

File: fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java [hunk 8]
```diff
@@ -316,14 +335,61 @@ private static Cluster initializeCluster(Configuration conf, RpcClient rpcClient
         return cluster;
```
Comment (wuchong) [inline fluss-client/src/main/java/org/apache/fluss/client/metadata/MetadataUpdater.java:343]: We should improve this exception message, it didn't carry exception message to the top error message which may confuse users. 

```
            String errorMsg =
                    "Failed to initialize fluss client connection to bootstrap servers: "
                            + inetSocketAddresses
                            + ". \nReason: "
                            + lastException.getMessage();
```

**Comment by swuferhong** [comment]
@wuchong comments addressed.
