### PR TITLE
[server] Tablet server should register lakeCatalogDynamicLoader in dynamicConfigManager

### LINKED ISSUE #1878: Tablet server should register lakeCatalogDynamicLoader in dynamicConfigManager
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.7.0 (latest release)

### Please describe the bug 🐞

Currently, In tablet server, dynamicConfigManager is not registered in DynamicConfigManager. If get table info from tablet server, will lack new modified config.

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by loserwang1024**
### Purpose

Linked issue: close #1878

### CODE REVIEW

File: fluss-client/src/test/java/org/apache/fluss/client/admin/FlussAdminITCase.java [hunk 1]
```diff
@@ -1092,20 +1093,33 @@ void testDynamicConfigs() throws ExecutionException, InterruptedException {
...
+                        .property(ConfigOptions.TABLE_DATALAKE_ENABLED, true)
+                        .build(),
+                true);
+
+        waitUntil(
+                () -> {
+                    TableInfo tableInfo = admin.getTableInfo(tablePath).get();
+                    Map<String, String> tableProperties = tableInfo.getProperties().toMap();
+                    return "test-warehouse"
+                            .equals(tableProperties.get("table.datalake.paimon.warehouse"));
```
Comment (leonardBang) [inline fluss-client/src/test/java/org/apache/fluss/client/admin/FlussAdminITCase.java]: minor: we can check `tableProperties` has key 'datalake.format' and 'table.datalake.paimon.warehouse' firstly and then check value of two properties

Comment (loserwang1024) [reply fluss-client/src/test/java/org/apache/fluss/client/admin/FlussAdminITCase.java]: done

**Comment by loserwang1024** [comment]
@leonardBang Thanks for your review! Just modified it.
