### PR TITLE
[hotfix] Still do remove server tag if tablet server not exist

### LINKED ISSUE #2882: [hotfix] Still do remove server tag if tablet server not exist
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.9.0 (latest release)

### Please describe the bug 🐞

Before rebalancing, we need to tag TabletServers.

After rebalancing, we do remove tag. 

If the tablet server does not exists afterwards, the remove tag request will throw a exception. 

### Solution

We expect not throw a exception but execute the request normally.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by zcoo**
### Purpose

Linked issue: close #2882

### CODE REVIEW

File: fluss-client/src/test/java/org/apache/fluss/client/admin/FlussAdminITCase.java [hunk 1]
```diff
@@ -1625,22 +1610,17 @@ public void testAddAndRemoveServerTags() throws Exception {
...
-                .hasMessageContaining("Server 100 not exists when trying to removing server tag.");
-
-        // 5.remove server tag for server 0,1.
+        // 4.remove server tag for server 0,1.
+        // should remove server tag successfully even we remove live tablet server from context
+        FLUSS_CLUSTER_EXTENSION
+                .getCoordinatorServer()
+                .getCoordinatorEventProcessor()
+                .getCoordinatorContext()
+                .removeLiveTabletServer(0);
```
Comment (swuferhong) [inline fluss-client/src/test/java/org/apache/fluss/client/admin/FlussAdminITCase.java]: This test does not cover the case where this `serverTag` exists in zk but the server is already offline. The remove operation can remove the record from zk. please adding that test.

**Comment by zcoo** [comment]
@swuferhong Thanks! please take another look

**Comment by swuferhong** [comment]
Hi, @zcoo could you cherry pick this pr to release-0.9, big thinks.
