### PR TITLE
[hotfix][flink] Fix acquire kv snapshot lease cannot work issue for legacy clusters

### LINKED ISSUE #2737: Acquire kv snapshot lease cannot work for legacy clusters
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

main (development)

### Please describe the bug 🐞

Acquire kv snapshot lease cannot work for legacy clusters.

### Solution

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by swuferhong**
### Purpose

Linked issue: close #2737 

[hotfix][flink] Fix acquire kv snapshot lease cannot work issue for legacy clusters

### CODE REVIEW

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/FlinkSourceEnumerator.java [hunk 1]
```diff
@@ -1054,10 +1071,21 @@ public void notifyCheckpointComplete(long checkpointId) throws Exception {
...
         } catch (Exception e) {
-            LOG.error("Failed to release kv snapshot lease. These snapshot need to re-enqueue", e);
-            // use the current checkpoint id to re-enqueue the buckets
-            consumedKvSnapshots.forEach(
-                    tableBucket -> addConsumedBucket(checkpointId, tableBucket));
+            if (ExceptionUtils.findThrowable(e, UnsupportedVersionException.class).isPresent()) {
+                LOG.warn(
+                        "Failed to release kv snapshot lease because the server does not support "
+                                + "kv snapshot lease API. Snapshots may remain in storage longer "
+                                + "than necessary. Please upgrade the Fluss server to version 0.10 "
```
Comment (loserwang1024) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/FlinkSourceEnumerator.java]:
```suggestion
                               Please upgrade the Fluss server to version 0.9 "
```
