### PR TITLE
[connector] Fluss sink supports ignore_delete.

### LINKED ISSUE #251: [Feature][connector] Support ignore delete for Log Table
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Motivation

In flink, the join operation may produce retractions, if writing join result into an append-only sink will throw plan exception. However, in some cases, users want to use Log Table as the sink of join operation. We can introduce a `sink.ignore-delete` option for the sink connector, and ignore deletions when the option is enabled. 

### Solution

_No response_

### Anything else?

_No response_

### Willingness to contribute

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by loserwang1024**
### Purpose

Linked issue: close #251

### CODE REVIEW

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/options/DeleteStrategy.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+public enum DeleteStrategy implements Serializable {
+
+    /**
+     * Ignore -U and -D. This is applicable for scenarios where users only need to insert or update
+     * data without the need to delete data.
+     */
+    IGNORE_DELETE,
+
+    /**
+     * Operate normally based on PK + rowkind, suitable for scenarios that do not involve localized
```
Comment (luoyuxia) [inline fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/options/DeleteStrategy.java]: What `localized updates` means?

File: fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSinkITCase.java [hunk 2]
```diff
@@ -378,6 +380,30 @@ void testInsertWithoutSpecifiedCols() {
...
+    void testIgnoreDelete() throws Exception {
+        String cdcSourceData =
+                TestValuesTableFactory.registerData(
+                        Arrays.asList(
+                                Row.ofKind(RowKind.INSERT, 1, 3501L, "Tim"),
+                                Row.ofKind(RowKind.DELETE, 1, 3501L, "Tim"),
+                                Row.ofKind(RowKind.INSERT, 2, 3502L, "Fabian"),
+                                Row.ofKind(RowKind.UPDATE_BEFORE, 2, 3502L, "Fabian"),
+                                Row.ofKind(RowKind.UPDATE_AFTER, 3, 3503L, "coco")));
+        tEnv.executeSql(
```
Comment (luoyuxia) [inline fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSinkITCase.java:434]: We should verify a stream with -D/-U change mode can write to a log sink with `ignoreDelete`, but currently the source's changelog mode is +I only...

Btw, can we just use the public interface `tableEnv.fromChangelogStream` to do the testing? I'd like not to introduce an external test jar `flink-table-planner` since the test jar may change overtime and we may need to adjust our test then..

File: fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSinkITCase.java [hunk 3]
```diff
@@ -378,6 +380,30 @@ void testInsertWithoutSpecifiedCols() {
...
+                "create temporary table source_test (a int not null, b bigint, c string) with('connector'='values', 'bounded' = 'true', 'data-id'='"
+                        + cdcSourceData
+                        + "')");
+        tEnv.executeSql(
+                "create table sink_test (a int not null, b bigint, c string) with('bucket.num' = '3', 'sink.delete-strategy'='IGNORE_DELETE')");
```
Comment (luoyuxia) [inline fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSinkITCase.java]: nit: use `ignore_delete` since user likely to use lowercase in table option

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/options/DeleteStrategy.java (hunk 1 above)
Comment (loserwang1024) [reply fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/options/DeleteStrategy.java]: `partial update` is better, I will update it.

**Review by luoyuxia — APPROVED** [review]
LGTM! May @wuchong check the table option `'sink.delete-strategy'='ignore_delete'` used for ignore delete  is fine to you?

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/FlinkSinkFunction.java [hunk 4]
```diff
@@ -74,20 +75,27 @@ abstract class FlinkSinkFunction extends RichSinkFunction<RowData>
     private transient Counter numRecordsOutCounter;
     private transient Counter numRecordsOutErrorsCounter;
     private volatile Throwable asyncWriterException;
+    private final DeleteStrategy deleteStrategy;
```
Comment (wuchong) [inline fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/FlinkSinkFunction.java]: nit: put the `final` variables together.

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSink.java [hunk 5]
```diff
@@ -147,8 +155,13 @@ public SinkRuntimeProvider getSinkRuntimeProvider(Context context) {
         FlinkSinkFunction sinkFunction =
                 primaryKeyIndexes.length > 0
                         ? new UpsertSinkFunction(
-                                tablePath, flussConfig, tableRowType, targetColumnIndexes)
-                        : new AppendSinkFunction(tablePath, flussConfig, tableRowType);
+                                tablePath,
+                                flussConfig,
+                                tableRowType,
+                                targetColumnIndexes,
+                                deleteStrategy)
```
Comment (wuchong) [inline fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSink.java]: Add a test for primary key table as well.

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSink.java [hunk 6]
```diff
@@ -95,8 +99,12 @@ public ChangelogMode getChangelogMode(ChangelogMode requestedMode) {
...
                 return builder.build();
             } else {
-                // append only
-                return ChangelogMode.insertOnly();
+                // log table which supports ignore_delete can accept RowKind.DELETE.
+                if (DeleteStrategy.IGNORE_DELETE.equals(deleteStrategy)) {
+                    return ChangelogMode.upsert();
+                } else {
+                    return ChangelogMode.insertOnly();
+                }
```
Comment (wuchong) [inline fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSink.java]:
```java
        if (!streaming) {
            return ChangelogMode.insertOnly();
        } else {
            if (primaryKeyIndexes.length > 0
                    || DeleteStrategy.IGNORE_DELETE.equals(deleteStrategy)) {
                // primary-key table or ignore_delete mode can accept RowKind.DELETE
                ChangelogMode.Builder builder = ChangelogMode.newBuilder();
                for (RowKind kind : requestedMode.getContainedKinds()) {
                    // optimize out the update_before messages
                    if (kind != RowKind.UPDATE_BEFORE) {
                        builder.addContainedKind(kind);
                    }
                }
                return builder.build();
            } else {
                return ChangelogMode.insertOnly();
            }
        }
```

Better to dynamically remove update_before messages instead of hard-code `upsert`.

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/FlinkConnectorOptions.java [hunk 7]
```diff
@@ -98,6 +99,15 @@ public class FlinkConnectorOptions {
...
                                     + " A non-positive value disables the partition discovery.");
 
+    public static final ConfigOption<DeleteStrategy> SINK_DELETE_STRATEGY =
+            ConfigOptions.key("sink.delete-strategy")
+                    .enumType(DeleteStrategy.class)
+                    .defaultValue(DeleteStrategy.CHANGELOG_STANDARD)
+                    .withDescription(
+                            "This field is used to decide what to do when data of type -D/-U is received. "
+                                    + "`IGNORE_DELETE` means ignoring the `-D` and `-U` type message. "
+                                    + "`CHANGELOG_STANDARD` means neither `-U` nor `-D` is ignored, they both cause the corresponding row in fluss to be deleted");
```
Comment (wuchong) [inline fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/FlinkConnectorOptions.java]: Personally, I prefer `sink.ignore-delete=true/false`. If there are only 2 values and `CHANGELOG_STANDARD` is the default, I think `sink.ignore-delete=true/false` is much simpler for users to understand and use. 

It seems `sink.delete-strategy` comes from [here](https://www.alibabacloud.com/help/en/flink/developer-reference/hologres-connector/?spm=a2c63.l28256.help-menu-search-45029.d_3#section-r91-f4z-7lp) that contains additional values `NON_PK_FIELD_TO_NULL` and `DELETE_ROW_ON_PK`. However, Fluss already handles partial-updates and partial-delete with leveraging the `INSERT INTO (columns)` grammar and I don't see this config will extend additional values in the near future.

**Review by wuchong — COMMENTED** [review]
Thanks @luoyuxia and @loserwang1024 , I left some comments about the config.

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/FlinkConnectorOptions.java (hunk 7 above)
Comment (loserwang1024) [reply fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/FlinkConnectorOptions.java]: > It seems sink.delete-strategy comes from [here](https://www.alibabacloud.com/help/en/flink/developer-reference/hologres-connector/?spm=a2c63.l28256.help-menu-search-45029.d_3#section-r91-f4z-7lp) that contains additional values NON_PK_FIELD_TO_NULL and DELETE_ROW_ON_PK.

Yes, I don't know whether user want to partial update(-D) not delete the whole row but also not ignore , just set the non pk columns as null.

**Comment by loserwang1024** [comment]
rebase into main branch

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/options/DeleteStrategy.java [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+
+package com.alibaba.fluss.connector.flink.options;
+
+import org.apache.flink.annotation.PublicEvolving;
+
+import java.io.Serializable;
+
+/** The strategy when fluss sink receives delete data. */
+@PublicEvolving
+public enum DeleteStrategy implements Serializable {
```
Comment (wuchong) [inline fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/options/DeleteStrategy.java]: can be removed.

**Review by wuchong — APPROVED** [review]
LGTM.

**Comment by luoyuxia** [comment]
Let me merge it to reduce the gap between my test branch and main bach...
