### PR TITLE
[hotfix] Report empty string as value for partition label for non-partitioned table

### LINKED ISSUE #302: [Bug] Prometheus metrics plugin will throw Incorrect number of labels when partitioned table and non-partitioned table mixed in cluster
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

main

### Minimal reproduce step

1: enable prometheus metric reporter
2: create a partitioned table and non-partitioned table
3: then the following waning message will be thrown
```
2024-12-27 16:48:12,199 WARN  com.alibaba.fluss.metrics.registry.MetricRegistryImpl        [] - Error while handling metric: messagesInPerSecond.
java.lang.IllegalArgumentException: Incorrect number of labels.
	at io.prometheus.client.SimpleCollector.setChild(SimpleCollector.java:136) ~[?:?]
	at com.alibaba.fluss.metrics.prometheus.PrometheusReporter.addMetric(PrometheusReporter.java:214) ~[?:?]
	at com.alibaba.fluss.metrics.prometheus.PrometheusReporter.notifyOfAddedMetric(PrometheusReporter.java:153) ~[?:?]
	at com.alibaba.fluss.metrics.registry.MetricRegistryImpl.forAllReporters(MetricRegistryImpl.java:267) ~[fluss-server-0.6-SNAPSHOT.jar:0.6-SNAPSHOT]
	at com.alibaba.fluss.metrics.registry.MetricRegistryImpl.register(MetricRegistryImpl.java:214) ~[fluss-server-0.6-SNAPSHOT.jar:0.6-SNAPSHOT]
	at com.alibaba.fluss.metrics.groups.AbstractMetricGroup.addMetric(AbstractMetricGroup.java:292) ~[fluss-server-0.6-SNAPSHOT.jar:0.6-SNAPSHOT]
	at com.alibaba.fluss.metrics.groups.AbstractMetricGroup.meter(AbstractMetricGroup.java:250) ~[fluss-server-0.6-SNAPSHOT.jar:0.6-SNAPSHOT]
```

### What doesn't meet your expectations?

Should print warn message

### Anything else?

1: for partitioned table and  metrics name `messagesInPerSecond`, assuming `m1`,  it'll be of scope name `fluss_tabletserver_table__messagesInPerSecond`  with labels `{database=test_db_1, cluster_id=fluss, partition=2027, host=127.0.0.1, tablet_type=kv, server_id=2, table=test_pk_table_1}`. Note the label count is **7**

2: for non-partitioned table and metrics name `fluss_tabletserver_table__messagesInPerSecond`, assuming `m2`,  it'll be of scope name 
`fluss_tabletserver_table__messagesInPerSecond` with labels `{database=test_db_11, cluster_id=fluss, host=127.0.0.1, tablet_type=kv, server_id=2, table=tt}`. Note the label count is **6**

First, it registers `m1`  with a new created `Collector` `c1` to Prometheus reporter.  Then when add m2, it has same scope name with `m1`, so it use `c1` to add.  However, `c1` is expected to with label count **7**,  `m2` is with label count `6`. So, `Incorrect number of labels.` is thrown..

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by michaelkoepf**
### Purpose

Linked issue: close #302 

### Tests

See changes in 
- `com.alibaba.fluss.metrics.prometheus.PrometheusReporterDifferentLabelValueTest`
- `com.alibaba.fluss.metrics.jmx.JMXReporterTest`

Additional manually verification by creating the following 2 tables 

```
CREATE TABLE tbl1(
  a STRING,
  b INT,
  PRIMARY KEY(a, b) NOT ENFORCED 
) PARTITIONED BY (a) WITH (
  'table.auto-partition.enabled' = 'true',
   'table.auto-partition.time-unit' = 'YEAR',
   'table.auto_partitioning.time-zone' = 'Asia/Shanghai'
);

CREATE TABLE tbl2(
  c STRING,
  d INT,
  PRIMARY KEY(c,d) NOT ENFORCED 
);
```

in the Flink SQL client and check if all metrics are reported in Prometheus and JMX.

**Prometheus**

Screenshot from 2025-01-08 21-09-45

**JMX** (non-partitioned tables have a single entry with an empty string as key)

Screenshot from 2025-01-08 21-18-42

### API and Format

n/a

### Documentation

n/a

### CODE REVIEW

File: fluss-server/src/main/java/com/alibaba/fluss/server/metrics/group/PhysicalTableMetricGroup.java [hunk 1]
```diff
@@ -78,8 +78,12 @@ public PhysicalTableMetricGroup(
     protected void putVariables(Map<String, String> variables) {
         variables.put("database", physicalTablePath.getDatabaseName());
         variables.put("table", physicalTablePath.getTableName());
+
         if (physicalTablePath.getPartitionName() != null) {
             variables.put("partition", physicalTablePath.getPartitionName());
+        } else {
+            LOG.debug("Setting variable 'partition' for non-partitioned table to empty string.");
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/metrics/group/PhysicalTableMetricGroup.java]: nit: I don't think we should log it since it doesn't provide any useful info... We all know the partition will be empty string for non-partitioned table... Maybe you can add a comment about it in code instead of log it.

**Review by luoyuxia — COMMENTED** [review]
@michaelkoepf Thanks for the pr. Just one comment. Otherwise, LGTM!

File: fluss-server/src/main/java/com/alibaba/fluss/server/metrics/group/PhysicalTableMetricGroup.java (hunk 1 above)
Comment (michaelkoepf) [reply fluss-server/src/main/java/com/alibaba/fluss/server/metrics/group/PhysicalTableMetricGroup.java]: @luoyuxia replaced by comment -- done

**Review by luoyuxia — APPROVED** [review]
@michaelkoepf Thanks.. LGTM! Will merge later
