### PR TITLE
[server] Use dynamic tablet server gateway for fetching log from leader 

### LINKED ISSUE #633: ReplicaFetcherManager#createFetcherThread create gateway should use MetadataCache#getTabletServer(int serverId) instead of using a static ServerNode
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.6.0 (latest release)

### Please describe the bug 🐞

`ReplicaFetcherManager#createFetcherThread` create `gateway` should use `MetadataCache#getTabletServer(int serverId)` instead of using a static `ServerNode`.  The reason is that when a `tabletServer` or `coordinatorServer` goes offline, the corresponding `IP address` and `port` may change. Using static `ServerNode` will prevent recovery in this situation.

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by luoyuxia**
### Purpose

Linked issue: close #633 

Now, the tablet server gateway to fetch log from leader is static, which will cause if the leader change/failover,  it will still fetch log from old ip address.
Assuming the case:
- server 0 is follower, server 1 is leader.  Coordinator server down.
- server 1 down
- server 1 up and ip is changed, but the server 0 will stil try to fetch from old ip address.

### Brief change log
`ReplicaFetcherThread` use dynamic tablet server gateway to fetch log from leader, which will got latest server node of the tablet server. 

### Tests

Exsting tests has covered it.

### CODE REVIEW

**Comment by luoyuxia** [comment]
@wuchong @swuferhong Could you please help review it?

File: fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java [hunk 1]
```diff
@@ -851,7 +857,7 @@ private void addFetcherForReplicas(
                     bucketAndStatus.put(
                             tb,
                             new InitialFetchStatus(
-                                    tb.getTableId(), leader.get(), logTablet.localLogEndOffset()));
+                                    tb.getTableId(), leaderId, logTablet.localLogEndOffset()));
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java]: As we don't need to get the leader `ServerNode` here, is it still necessary to return a bucket level error to CoordinatorServer when the leader `ServerNode` is not in metadata?

File: fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/LeaderEndpoint.java [hunk 2]
```diff
@@ -28,8 +27,8 @@
 /** Defines the interface to be used to access a tablet server that is a leader. */
 interface LeaderEndpoint {
 
-    /** The specific tablet server address we want to connect to. */
-    ServerNode leaderNode();
+    /** The tablet server id we want to connect to. */
+    int leaderNode();
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/LeaderEndpoint.java]: rename to `leaderServerId`

File: fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/RemoteLeaderEndpoint.java [hunk 3]
```diff
@@ -41,7 +40,7 @@
 /** Facilitates fetches from a remote replica leader in one tablet server. */
 final class RemoteLeaderEndpoint implements LeaderEndpoint {
     private final int followerServerId;
-    private final ServerNode remoteNode;
+    private final int remoteNode;
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/RemoteLeaderEndpoint.java]: rename to `removeServerId`.

File: fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java (hunk 1 above)
Comment (luoyuxia) [reply fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java]: Yes, I believe we don't need to return a bucket level error . I meant to remove bucket level error thrown in #644 since #644 is part of caused by the thrown error.  But I think we can remove bucket level error thrown in here, and along with #664,  #644 won't happen.

**Review by wuchong — APPROVED** [review]
