### PR TITLE
[client] Get tableInfo via the Admin API instead of via metadata updater

### LINKED ISSUE #2014: FlussConnection getTable method fails due to missing retries when fetching metadata
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.8.0 (latest release)

### Please describe the bug 🐞

FlussConnection getTable method fails due to missing retries when fetching metadata：

```
java.lang.IllegalArgumentException: table: xxx not found in cluster
	at org.apache.fluss.cluster.Cluster.lambda$getTableOrElseThrow$2(Cluster.java:260)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.apache.fluss.cluster.Cluster.getTableOrElseThrow(Cluster.java:257)
	at org.apache.fluss.client.metadata.MetadataUpdater.getTableInfoOrElseThrow(MetadataUpdater.java:100)
	at org.apache.fluss.client.FlussConnection.getTable(FlussConnection.java:103)
	at org.apache.fluss.flink.sink.writer.FlinkSinkWriter.initialize(FlinkSinkWriter.java:112)
	at org.apache.fluss.flink.sink.writer.AppendSinkWriter.initialize(AppendSinkWriter.java:53)
	at org.apache.fluss.flink.sink.FlinkSink.createWriter(FlinkSink.java:63)
	at org.apache.flink.streaming.runtime.operators.sink.StatelessSinkWriterStateHandler.createWriter(StatelessSinkWriterStateHandler.java:39)
	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.initializeState(SinkWriterOperator.java:170)
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.initializeOperatorState(StreamOperatorStateHandler.java:122)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:285)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:106)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:843)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:790)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:747)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:959)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:928)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:751)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:567)
	at java.lang.Thread.run(Thread.java:879)
```

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by swuferhong**
### Purpose

Linked issue: close #2014 

Get `TableInfo` via the Admin API instead of via metadata updater.  This PR does not aim to fully remove `TableInfo` from the `metadataUpdater` and the `Cluster`—that work will be done in [483](https://github.com/apache/fluss/issues/483). This PR only changes the way table info is retrieved.

### CODE REVIEW

**Comment by wuchong** [comment]
@swuferhong is this PR ready to review? It seems there are tests are failing.

File: fluss-common/src/main/java/org/apache/fluss/cluster/Cluster.java [hunk 1]
```diff
@@ -234,26 +237,8 @@ public Optional<Long> getPartitionId(PhysicalTablePath physicalTablePath) {
...
-                        () ->
-                                new IllegalArgumentException(
-                                        String.format(
-                                                "table: %s not found in cluster", tablePath)));
-    }
-
-    public TableBucket getTableBucket(PhysicalTablePath physicalTablePath, int bucketId) {
-        TableInfo tableInfo = getTableOrElseThrow(physicalTablePath.getTablePath());
+    public TableBucket getTableBucket(
+            TableInfo tableInfo, PhysicalTablePath physicalTablePath, int bucketId) {
```
Comment (wuchong) [inline fluss-common/src/main/java/org/apache/fluss/cluster/Cluster.java]: Replace the parameter `TableInfo tableInfo` with `long tableId`. Only the table ID is needed, the full `TableInfo` object is unnecessarily large for this method.

**Review by wuchong — CHANGES_REQUESTED** [review]
We can put `TableInfo` into `WriteRecord`, and then we don't need `TableInfoCache`.

File: fluss-client/src/main/java/org/apache/fluss/client/write/Sender.java [hunk 2]
```diff
@@ -602,4 +607,31 @@ public void initiateClose() {
...
+            if (o == null || getClass() != o.getClass()) {
+                return false;
+            }
+            TableKey tableKey = (TableKey) o;
+            return tableId == tableKey.tableId;
+        }
+
+        @Override
+        public int hashCode() {
+            return Objects.hash(tableId);
```
Comment (wuchong) [inline fluss-client/src/main/java/org/apache/fluss/client/write/Sender.java]: The `TableKey` is super hack, because it is used as a map key, but the TableInfo is not considered for comparison. If we want to carry the TableInfo in the Map, it should belong to the values. However, I think we don't need the TableInfo to check log/kv. I made a change for this.

File: fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/sink/FlussSinkITCase.java [hunk 3]
```diff
@@ -93,11 +92,6 @@ public void setup() throws Exception {
         env.setParallelism(2);
     }
 
-    @AfterAll
-    protected static void afterAll() throws Exception {
-        conn.close();
-    }
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/sink/FlussSinkITCase.java]: I think we can revert all the test changes.

File: fluss-client/src/main/java/org/apache/fluss/client/write/ArrowLogWriteBatch.java [hunk 4]
```diff
@@ -52,14 +53,15 @@ public class ArrowLogWriteBatch extends WriteBatch {
     public ArrowLogWriteBatch(
             int bucketId,
             PhysicalTablePath physicalTablePath,
-            int schemaId,
+            TableInfo tableInfo,
```
Comment (wuchong) [inline fluss-client/src/main/java/org/apache/fluss/client/write/ArrowLogWriteBatch.java]: We should avoid passing large context objects; pass only the required data.

**Review by wuchong — APPROVED** [review]
