### PR TITLE
[lake/paimon] Fix than tiering service for paimon missed timestampNtz support

### LINKED ISSUE #1121: Tiering Service failed with TimestampNtz.
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

main (development)

### Please describe the bug 🐞

I created a table named recommendations, it includes a field called `rec_ts` of type `TimestampNtz`.

Image

I followed the steps in this [blog](https://alibaba.github.io/fluss-docs/blog/partial-updates/) and ran into a problem at Step 7.  The Flink task to start the tiering service failed, with the following error stack trace.

Image

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by leonardBang**
### Purpose

Linked issue: close #1121

### CODE REVIEW

File: fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/FlussRecordAsPaimonRowTest.java [hunk 1]
```diff
@@ -58,7 +77,7 @@ void testLogTableRecordAllTypes() {
         genericRow.setField(8, Decimal.fromUnscaledLong(9, 5, 2));
         genericRow.setField(9, Decimal.fromBigDecimal(new BigDecimal(10), 20, 0));
         genericRow.setField(10, TimestampLtz.fromEpochMillis(1698235273182L));
-        genericRow.setField(11, TimestampLtz.fromEpochMillis(1698235273182L, 45678));
+        genericRow.setField(11, TimestampNtz.fromMillis(1698235273182L, 45678));
```
Comment (wuchong) [inline fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/FlussRecordAsPaimonRowTest.java]: assert the nano seconds part as well?

**Review by wuchong — APPROVED** [review]

**Comment by leonardBang** [comment]
Thanks @wuchong and @luoyuxia for the review, CI passed, merging..
