### PR TITLE
[Connector] Resource cleanup via AfterEach Extending AbstractStreamBase

### LINKED ISSUE #868: Unstable flink-core CI getting timed out randomly
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.6.0 (latest release)

### Please describe the bug 🐞

Flink-core CI is failing randomly due to resource cleanup from one test iteration starting but not completing before another test iteration accesses the same resources, causing the test case to run indefinitely, eventually causing the CI pipeline to timeout.

### Solution

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by MehulBatra**
### Purpose

Linked issue: close #868

To prevent Flink-core CI from failing randomly due to resource cleanup from one test iteration starting but not completing before another test iteration accesses the same resources, causing the test case to run indefinitely, eventually causing the CI pipeline to timeout.

### Brief change log

- Proper cleanup of resources after each test using `AbstractTestBase` MiniClusterExtension using cleanupRunningJobs
- Explicitly wait for bucket snapshots to complete before collecting results in `testPrefixLookupWithCondition`
- Created a separate utility class `FlinkRowAssertionsUtils` for assertion method, moved away from `FlinkTestBase` to avoid duplicate code, & Improved error handling and closure for the same.
- Removed extensibility of `FlinkTestBase` from `FlinkMetricsITCase`, manually configured Fluss & Flink cluster extension and changes related to it.

 

### Tests

Targeting PrefixLookup type tests

### API and Format

None

### Documentation

None

### CODE REVIEW

File: fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceITCase.java [hunk 1]
```diff
@@ -108,6 +108,30 @@ void after() {
         tEnv.executeSql(String.format("drop database %s cascade", DEFAULT_DB));
     }
 
+    @AfterEach
+    void cleanupAfterTest() {
+        try {
+            // Cancel any running jobs in the environment
+            if (execEnv != null) {
+                try {
+                    execEnv.close();
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceITCase.java]: 1. `execEnv` is initialized in `@BeforeAll`, if we close it in `@AfterEach`, it will has problems in next test method that the `execEnv` has been closed. 
2. The `org.apache.flink.streaming.api.environment.StreamExecutionEnvironment#close` doesn't do anything, thus no effect to the test.

Comment (MehulBatra) [reply fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceITCase.java]: Resolved it by extending to AbstractTestBase using MiniclusterExtension afterEach via cleanUpRunningJobs

File: fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceITCase.java [hunk 2]
```diff
@@ -911,6 +911,7 @@ void testPrefixLookupWithCondition(Caching caching, boolean async) throws Except
                                 + " ON src.b = h.name AND h.address = 'address5'",
                         dim);
 
+        waitUtilAllBucketFinishSnapshot(admin, TablePath.of(DEFAULT_DB, dim));
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceITCase.java]: Why do we need to add this? I think we can still remove this because lookup doesn't rely on snapshots.

**Review by wuchong — COMMENTED** [review]
`FlinkAuthorizationITCase` is timeout, which also needs to extends `FlinkTestBase` and `AbstractTestBase`.

File: fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceITCase.java (hunk 2 above)
Comment (MehulBatra) [reply fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceITCase.java]: I added due to table lookup failure warning I saw in the maven logs, to avoid any future warning, but if it is not required I will remove.

**Comment by MehulBatra** [comment]
> `FlinkAuthorizationITCase` is timeout, which also needs to extends `FlinkTestBase` and `AbstractTestBase`.

I will try to solve this today and ping you once done!

**Comment by MehulBatra** [comment]
@wuchong can't extend `FlinkTestBase` directly as it has different generic Fluss cluster configurations, but `FlinkAuthorizationITCase` needs a specific security-enabled configuration; rather, I will directly extend `AbstractTestBase` to cater to Flink Minicluster needs

File: fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/metrics/FlinkSourceReaderMetricsTest.java [hunk 3]
```diff
@@ -32,7 +33,7 @@
 import static org.assertj.core.api.Assertions.assertThat;
 
 /** Unit test for {@link com.alibaba.fluss.flink.source.metrics.FlinkSourceReaderMetrics}. */
-class FlinkSourceReaderMetricsTest {
+class FlinkSourceReaderMetricsTest extends FlinkTestBase {
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/metrics/FlinkSourceReaderMetricsTest.java]: `FlinkSourceReaderMetricsTest` is not an integration test (`ITCase`) that doesn't rely on a fluss cluster and flink cluster, therefore, it doesn't need to extend `FlinkTestBase`. Setting up clusters is very heavy which should be avoided as much as possible to reduce the test time.

**Review by wuchong — APPROVED** [review]
@MehulBatra thanks, this looks good to me except `FlinkSourceReaderMetricsTest` doesn't need to extend `FlinkTestBase`.

File: fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/metrics/FlinkSourceReaderMetricsTest.java (hunk 3 above)
Comment (MehulBatra) [reply fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/metrics/FlinkSourceReaderMetricsTest.java]: My bad, done mistakenly despite knowing, I will be more cautious.

**Comment by MehulBatra** [comment]
> @MehulBatra thanks, this looks good to me except `FlinkSourceReaderMetricsTest` doesn't need to extend `FlinkTestBase`.

Thank you @wuchong for the review!
