### PR TITLE
[test] Fix unstable test ReplicaTest.testRestore

### LINKED ISSUE #2276: Unstable test ReplicaTest.testRestore
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

main (development)

### Please describe the bug 🐞

https://github.com/apache/fluss/actions/runs/20571548213/job/59079676068?pr=2154

```
[INFO] Running org.apache.fluss.server.replica.ReplicaManagerTest
Error:  Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 20.008 s <<< FAILURE! - in org.apache.fluss.server.replica.ReplicaTest
Error:  org.apache.fluss.server.replica.ReplicaTest.testRestore(Path)  Time elapsed: 2.223 s  <<< ERROR!
java.util.NoSuchElementException
	at java.base/java.util.AbstractQueue.remove(AbstractQueue.java:117)
	at org.apache.fluss.testutils.common.ManuallyTriggeredScheduledExecutorService.triggerNonPeriodicScheduledTask(ManuallyTriggeredScheduledExecutorService.java:252)
	at org.apache.fluss.server.replica.ReplicaTest.testRestore(ReplicaTest.java:720)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(Interceptin
```

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by wuchong**
### Purpose

Linked issue: close #2276

The original exception occurs because the code assumes there are always exactly two scheduled tasks in the `scheduledExecutorService`: one for the previous KV tablet and one for the current KV tablet. Accordingly, it first calls `scheduledExecutorService.removeNonPeriodicScheduledTask()` and then `triggerNonPeriodicScheduledTask()`. However, this assumption is fragile—there may be no previous scheduled task at all, leading to a `NoSuchElementException` when `triggerNonPeriodicScheduledTask()` attempts to remove an element from an empty queue.

```
Error:  org.apache.fluss.server.replica.ReplicaTest.testRestore(Path)  Time elapsed: 2.199 s  <<< ERROR!
java.util.NoSuchElementException
	at java.base/java.util.AbstractQueue.remove(AbstractQueue.java:117)
	at org.apache.fluss.testutils.common.ManuallyTriggeredScheduledExecutorService.triggerNonPeriodicScheduledTask(ManuallyTriggeredScheduledExecutorService.java:252)
	at org.apache.fluss.server.replica.ReplicaTest.testRestore(ReplicaTest.java:720)
```

A more robust solution involves two improvements:

1. **Enhance the production code**: When closing a `PeriodicSnapshotManager` (e.g., during `makeFollower`), explicitly cancel any previously registered scheduled snapshot task to avoid dangling or orphaned tasks.

2. **Improve the test logic**:  
   - After the replica becomes leader, trigger **all** pending scheduled tasks once to ensure any cancelled tasks are cleared from the `ManuallyTriggeredScheduledExecutorService`.  
   - Then, use `triggerNextNonPeriodicScheduledTask(timeout)` to trigger the next snapshot task. Note that a short wait may be necessary after `waitUntilSnapshotComplete`, as the completion of the current snapshot does not guarantee that the next snapshot task has already been scheduled into the executor service.

This approach eliminates reliance on brittle assumptions about task counts and makes both the implementation and tests more resilient.

### CODE REVIEW

**Comment by wuchong** [comment]
@platinumhamburg could you help to review this?

File: fluss-server/src/main/java/org/apache/fluss/server/kv/snapshot/PeriodicSnapshotManager.java [hunk 1]
```diff
@@ -79,6 +80,9 @@ public class PeriodicSnapshotManager implements Closeable {
     /** Whether snapshot is started. */
     private volatile boolean started = false;
 
+    /** The scheduled snapshot task. */
+    private volatile ScheduledFuture<?> scheduledTask = null;
```
Comment (platinumhamburg) [inline fluss-server/src/main/java/org/apache/fluss/server/kv/snapshot/PeriodicSnapshotManager.java]: Because all reads and writes of this variable are protected by synchronized, the volatile modifier may no longer be necessary.

Comment (wuchong) [reply fluss-server/src/main/java/org/apache/fluss/server/kv/snapshot/PeriodicSnapshotManager.java]: You are right.
