### PR TITLE
[lake/flink] Enforce to keep data insistent when commit to lake but fail to commit to fluss

### LINKED ISSUE #1064: Keep data insistent when commit to lake but fail to commit to fluss
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Description

Currently, when commit, it'll first try to commit to lake, and then commit to Fluss cluster.
Then, in next round of tiering, it'll read committed from Fluss cluster.
It may happen that it has been commit to lake, but fail to commit to Fluss. In next round of tiering, it'll read from the latest known committed offset from  Fluss cluster, and try to commit again to lake. But the data has been already in lake.

### Willingness to contribute

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by luoyuxia**
### Purpose

Linked issue: close #1064 

To fix the data insistent when commit to lake, but fail to commit to fluss

### Brief change log

When try to generate splits to read in source enumerator, it'll get the latest known lake snapshot from Fluss, 
compare it with the latest snapshot in lake, if same, do thing. 

If not, try to get the newly commited log end offset in the latest snapshot, and commit to fluss , then request latest known lake snapshot from Fluss again which will get the consistent data splits.

### Tests
`FlussTableLakeSnapshotCommitterTest` to verify it can commit the miss lake snapshot to fluss
`PaimonTieringTest` to verify it can get the missing lake snapshot and log offset
`TieringSourceEnumeratorTest` to verify if missing snapshot, it can commit missing snapshot to lake, and get the  consistent data splits.

### CODE REVIEW

File: fluss-common/src/main/java/com/alibaba/fluss/lakehouse/committer/LakeCommittedSnapshot.java [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+
+    private final long lakeSnapshotId;
+
+    public LakeCommittedSnapshot(long lakeSnapshotId) {
+        this.lakeSnapshotId = lakeSnapshotId;
+    }
+
+    // <partition_name, bucket> -> log offset, partition_name will be null if it's not a
+    // partition bucket
+    private final Map<Tuple2<String, Integer>, Long> logEndOffsets = new HashMap<>();
```
Comment (leonardBang) [inline fluss-common/src/main/java/com/alibaba/fluss/lakehouse/committer/LakeCommittedSnapshot.java]: nit: Bubble up this code to line 32

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/committer/FlussTableLakeSnapshotCommitter.java [hunk 2]
```diff
@@ -71,6 +75,36 @@ public void commit(FlussTableLakeSnapshot flussTableLakeSnapshot) throws IOExcep
...
+                new FlussTableLakeSnapshot(tableId, lakeCommittedSnapshot.getLakeSnapshotId());
+        for (Map.Entry<Tuple2<String, Integer>, Long> entry :
+                lakeCommittedSnapshot.getLogEndOffsets().entrySet()) {
+            Tuple2<String, Integer> partitionBucket = entry.getKey();
+            TableBucket tableBucket;
+            if (partitionBucket.f0 == null) {
+                tableBucket = new TableBucket(tableId, partitionBucket.f1);
+            } else {
+                String partitionName = partitionBucket.f0;
+                // todo: consider what if partition rename, drop + create?
```
Comment (leonardBang) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/committer/FlussTableLakeSnapshotCommitter.java]: could you create an issue and add issue link here?

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/source/enumerator/TieringSourceEnumerator.java [hunk 3]
```diff
@@ -310,6 +326,55 @@ private List<TieringSplit> populateNumberOfTieringSplits(List<TieringSplit> tier
...
+                            flussAdmin.listPartitionInfos(tablePath).get().stream()
+                                    .collect(
+                                            Collectors.toMap(
+                                                    PartitionInfo::getPartitionName,
+                                                    PartitionInfo::getPartitionId));
+                }
+                flussTableLakeSnapshotCommitter.commit(
+                        tableId, partitionIdByName, lakeCommittedSnapshot);
+                // then, we can generate split thenAdd commentMore actions
+                return doGenerateTieringSplits(tableId, tablePath);
```
Comment (leonardBang) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/source/enumerator/TieringSourceEnumerator.java]: Do we need to introduce a recursion here ？

I think we can add a method like `boolean advanceLatestLakeCommittedSnapshots()` and then call `splitGenerator.generateTableSplits` temporally . Furthermore, we'd better move this logic to committer operator.

**Review by leonardBang — COMMENTED** [review]
Thanks @luoyuxia for the contribution, left some comments

**Comment by luoyuxia** [comment]
I would like to refactor the implementation to avoid introduce tiering factory in enumerator

**Comment by luoyuxia** [comment]
@leonardBang Comments addressed and rebase master

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/source/enumerator/TieringSourceEnumerator.java [hunk 4]
```diff
@@ -23,6 +23,7 @@
 import com.alibaba.fluss.client.metadata.MetadataUpdater;
 import com.alibaba.fluss.config.Configuration;
 import com.alibaba.fluss.flink.metrics.FlinkMetricRegistry;
+import com.alibaba.fluss.flink.tiering.event.FailedTieringEvent;
 import com.alibaba.fluss.flink.tiering.event.FinishTieringEvent;
```
Comment (leonardBang) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/source/enumerator/TieringSourceEnumerator.java]: nit: could we use same naming style? (`FailTieringEvent`, `FinishTieringEvent `) or (`FailedTieringEvent`, `FinishedTieringEvent `) , I prefer later one

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/source/enumerator/TieringSourceEnumerator.java [hunk 5]
```diff
@@ -198,6 +198,24 @@ public void handleSourceEvent(int subtaskId, SourceEvent sourceEvent) {
...
+                    "Tiering table {} is failed, fail reason is {}.",
+                    tieringEpoch,
+                    failedEvent.failReason());
+            if (tieringEpoch == null) {
+                // shouldn't happen, warn it
+                LOG.warn(
+                        "The failed table {} is not in tiering table, won't report it to Fluss to mark as failed.",
+                        failedTableId);
+            } else {
+                failedTableEpochs.put(failedTableId, tieringEpoch);
```
Comment (leonardBang) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/source/enumerator/TieringSourceEnumerator.java:213]: for failed tiering table, do we need to notify fluss coordinator eagerly just like finished tiering table ?

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/source/split/TieringSplitGenerator.java [hunk 6]
```diff
@@ -316,7 +316,7 @@ private Optional<TieringSplit> generateSplitForLogTableBucket(
             }
         }
         LOG.info(
-                "The lastCommittedBucketOffset{} is equals or bigger than latestBucketOffset {}, skip generating split for bucket {}",
+                "The lastCommittedBucketOffset {} is equals or bigger than latestBucketOffset {}, skip generating split for bucket {}",
```
Comment (leonardBang) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/source/split/TieringSplitGenerator.java:319]: 👍🏻

File: fluss-common/src/main/java/com/alibaba/fluss/lake/committer/LakeCommittedSnapshot.java [hunk 7]
```diff
@@ -0,0 +1,80 @@
...
+
+import java.util.HashMap;
+import java.util.Map;
+import java.util.Objects;
+
+/**
+ * The lake already committed snapshot, containing the lake snapshot id and the bucket end offsets
+ * in this snapshot.
+ */
+public class LakeCommittedSnapshot {
```
Comment (leonardBang) [inline fluss-common/src/main/java/com/alibaba/fluss/lake/committer/LakeCommittedSnapshot.java]: how about `CommittedLakeSnapshot` as we use `LakeSnapshot` suffix in many places?

File: fluss-common/src/main/java/com/alibaba/fluss/lake/committer/LakeCommitter.java [hunk 8]
```diff
@@ -49,4 +51,24 @@ public interface LakeCommitter<WriteResult, CommittableT> extends AutoCloseable
...
+     * Get the missing committed snapshot from the view of the knownSnapshotId.
+     *
+     * @param knownSnapshotId the known snapshot id to judge which snapshot missing based the lake
+     *     current snapshot. Will be null if no any knownSnapshotId.
+     * @return the missing committed snapshot, will be null if no any missing snapshot
+     * @throws IOException if an I/O error occurs
+     */
+    @Nullable
+    LakeCommittedSnapshot getMissingCommittedSnapshot(@Nullable Long knownSnapshotId)
+            throws IOException;
```
Comment (leonardBang) [inline fluss-common/src/main/java/com/alibaba/fluss/lake/committer/LakeCommitter.java]:
```suggestion
 /**
     * Get missing lake snapshot that has been committed to lake but didn't commit to fluss.
     *
     * @param latestLakeSnapshotIdOfFluss the latest lake snapshot id in fluss, used to judge which
     *     lake snapshot is missing.
     * @return the missing lake snapshot, returns null if no any missing snapshot found
     * @throws IOException if an I/O error occurs
     */
    @Nullable
    CommittedLakeSnapshot getMissingLakeSnapshot(@Nullable Long latestLakeSnapshotIdOfFluss)
            throws IOException;
```

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/committer/TieringCommitOperator.java [hunk 9]
```diff
@@ -166,6 +194,57 @@ private Committable commitWriteResults(
...
+                                                PartitionInfo::getPartitionName,
+                                                PartitionInfo::getPartitionId));
+            }
+            flussTableLakeSnapshotCommitter.commit(
+                    tableInfo.getTableId(), partitionIdByName, missingCommittedSnapshot);
+            // abort this committable to delete the written files
+            lakeCommitter.abort(committable);
+            throw new IllegalStateException(
+                    String.format(
+                            "The current Fluss's lake snapshot %d is less than lake actual snapshot %d committed by Fluss, missing snapshot: %s.",
```
Comment (leonardBang) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/committer/TieringCommitOperator.java]: we can add tableId to exception message for troubleshooting.

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/event/FailedTieringEvent.java [hunk 10]
```diff
@@ -0,0 +1,42 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.alibaba.fluss.flink.tiering.event;
+
+import org.apache.flink.api.connector.source.SourceEvent;
+
+/** SourceEvent used to represent a Fluss table is failed to tiering. */
```
Comment (leonardBang) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/event/FailedTieringEvent.java]:
```suggestion
/** SourceEvent used to represent a Fluss table is failed during tiering. */
```

File: fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java [hunk 11]
```diff
@@ -83,6 +93,67 @@ public long commit(PaimonCommittable committable) throws IOException {
...
 
+    @Override
+    public void abort(PaimonCommittable committable) throws IOException {
+        fileStoreCommit = fileStoreTable.store().newCommit(FLUSS_LAKE_TIERING_COMMIT_USER);
+        fileStoreCommit.abort(committable.manifestCommittable().fileCommittables());
+    }
+
+    @Nullable
+    @Override
+    public LakeCommittedSnapshot getMissingCommittedSnapshot(@Nullable Long knownSnapshotId)
```
Comment (leonardBang) [inline fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java]: we can abstract a method to make the code more readable:
```java
  @Nullable
    @Override
    public CommittedLakeSnapshot getMissingLakeSnapshot(@Nullable Long latestLakeSnapshotIdOfFluss)
            throws IOException {
        Long latestLakeSnapshotIdOfLake =
                getCommittedLatestSnapshotIdOfLake(FLUSS_LAKE_TIERING_COMMIT_USER);
        if (latestLakeSnapshotIdOfLake == null) {
            return null;
        }

        if (latestLakeSnapshotIdOfFluss != null
                && latestLakeSnapshotIdOfLake <= latestLakeSnapshotIdOfFluss) {
            return null;
        }

        // todo: the temporary way to scan the delta to get the log end offset,
        // we should read from snapshot's properties in Paimon 1.2
        CommittedLakeSnapshot committedLakeSnapshot =
                new CommittedLakeSnapshot(latestLakeSnapshotIdOfLake);
        ScanMode scanMode =
                fileStoreTable.primaryKeys().isEmpty() ? ScanMode.DELTA : ScanMode.CHANGELOG;

        Iterator<ManifestEntry> manifestEntryIterator =
                fileStoreTable
                        .store()
                        .newScan()
                        .withSnapshot(latestLakeSnapshotIdOfLake)
                        .withKind(scanMode)
                        .readFileIterator();

        while (manifestEntryIterator.hasNext()) {
            updateCommittedLakeSnapshot(committedLakeSnapshot, manifestEntryIterator.next());
        }

        return committedLakeSnapshot;
    }

    @Nullable
    private Long getCommittedLatestSnapshotIdOfLake(String commitUser) throws IOException {
        // get the latest snapshot commited by fluss or latest commited id
        SnapshotManager snapshotManager = fileStoreTable.snapshotManager();
        Long userCommittedSnapshotIdOrLatestCommitId =
                fileStoreTable
                        .snapshotManager()
                        .pickOrLatest((snapshot -> snapshot.commitUser().equals(commitUser)));
        // no any snapshot, return null directly
        if (userCommittedSnapshotIdOrLatestCommitId == null) {
            return null;
        }

        // pick the snapshot
        Snapshot snapshot = snapshotManager.tryGetSnapshot(userCommittedSnapshotIdOrLatestCommitId);

        if (!snapshot.commitUser().equals(commitUser)) {
            // the snapshot is still not commited by Fluss, return directly
            return null;
        }
        return snapshot.id();
    }
```

File: fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java [hunk 12]
```diff
@@ -16,23 +16,33 @@
...
+
+import javax.annotation.Nullable;
 
 import java.io.IOException;
+import java.util.ArrayList;
 import java.util.Collections;
+import java.util.Iterator;
 import java.util.List;
 
 import static com.alibaba.fluss.lake.paimon.tiering.PaimonLakeTieringFactory.FLUSS_LAKE_TIERING_COMMIT_USER;
```
Comment (leonardBang) [inline fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java:43]: `FLUSS_LAKE_TIERING_COMMIT_USER = "fluss_lake_tiering";` could we change to  `FLUSS_LAKE_TIERING_COMMIT_USER = "__fluss_lake_tiering_user", ` to make it looks like a system user?

File: fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java [hunk 13]
```diff
@@ -124,4 +195,32 @@ public void close() throws Exception {
...
         }
     }
+
+    private void updateCommittedLakeSnapshot(
+            LakeCommittedSnapshot lakeCommittedSnapshot, ManifestEntry manifestEntry) {
+        // always get bucket, log_offset from statistic
+        DataFileMeta dataFileMeta = manifestEntry.file();
+        BinaryRow maxStatisticRow = dataFileMeta.valueStats().maxValues();
+
+        // the system columns orders are: __bucket, __offset, __timestampAdd commentMore actions
```
Comment (leonardBang) [inline fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java]: nit: remove  `Add commentMore actions`

File: fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java [hunk 14]
```diff
@@ -124,4 +195,32 @@ public void close() throws Exception {
...
+        int fieldCount = maxStatisticRow.getFieldCount();
+        int bucketId = maxStatisticRow.getInt(fieldCount - 3);
+        long offset = maxStatisticRow.getLong(fieldCount - 2);
```
Comment (leonardBang) [inline fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java]: We can record system columns with ordered set or map, and then use the system column index instead of magic number here, magic number is hard to maintain once we introduce new system column

File: fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/tiering/source/enumerator/TieringSourceEnumeratorTest.java [hunk 15]
```diff
@@ -579,6 +586,63 @@ void testPartitionedLogTableSplits() throws Throwable {
         }
     }
 
+    @Test
+    void testHandleFailTieringTableEvent() throws Throwable {
```
Comment (leonardBang) [inline fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/tiering/source/enumerator/TieringSourceEnumeratorTest.java]: nit: testHandleFailedTieringTableEvent

File: fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java (hunk 12 above)
Comment (luoyuxia) [reply fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java:43]: Let's use `__fluss_lake_tiering` since paimon snapshot's property committer user already means a user.

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/source/enumerator/TieringSourceEnumerator.java (hunk 5 above)
Comment (luoyuxia) [reply fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/source/enumerator/TieringSourceEnumerator.java:213]: I think so. just missing that.

File: fluss-common/src/main/java/com/alibaba/fluss/lake/committer/LakeCommitter.java (hunk 8 above)
Comment (luoyuxia) [reply fluss-common/src/main/java/com/alibaba/fluss/lake/committer/LakeCommitter.java]: Good suggestion. It's more clear.

File: fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java (hunk 11 above)
Comment (luoyuxia) [reply fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java]: Good suggestion.

File: fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java (hunk 14 above)
Comment (luoyuxia) [reply fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java]: Ok, let's get the system column index by find it in columns according to the system column name.

**Review by leonardBang — APPROVED** [review]
Thanks @luoyuxia for the updating, LGTM
