### PR TITLE
[flink] Fix split will lose offset when restore from state

### LINKED ISSUE #358: The log offset will loss after restore from checkpoint
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.5.0 (latest release)

### Please describe the bug 🐞

Assume init a LogSplit with an log offset in the scenario of scanning from latest offset, if no any records are read from the offset. Stop with save point and restore from the save point..The log offset of the LogSplit will be reset to 0 which is not expected.. 

Set log level to INFO, then can be reproduce by the following code.
```
class FlinkTableSourceFailOverITCase {

    private static final String CATALOG_NAME = "testcatalog";

    @RegisterExtension
    public static final FlussClusterExtension FLUSS_CLUSTER_EXTENSION =
            FlussClusterExtension.builder()
                    .setClusterConf(
                            new com.alibaba.fluss.config.Configuration()
                                    .set(ConfigOptions.KV_SNAPSHOT_INTERVAL, Duration.ofDays(1)))
                    .setNumOfTabletServers(3)
                    .build();

    @TempDir File checkpointDir;
    @TempDir File savepointDir;

    protected static Connection conn;
    protected static Admin admin;

    protected static com.alibaba.fluss.config.Configuration clientConf;

    @BeforeAll
    protected static void beforeAll() {
        clientConf = FLUSS_CLUSTER_EXTENSION.getClientConfig();
        conn = ConnectionFactory.createConnection(clientConf);
        admin = conn.getAdmin();
    }

    @Test
    void t1() throws Exception {
        final int numTaskManagers = 2;
        final int numSlotsPerTaskManager = 2;
        final int parallelism = numTaskManagers * numSlotsPerTaskManager;

        final MiniClusterResourceFactory clusterFactory =
                new MiniClusterResourceFactory(
                        numTaskManagers,
                        numSlotsPerTaskManager,
                        getFileBasedCheckpointsConfig(savepointDir));

        StreamExecutionEnvironment execEnv = StreamExecutionEnvironment.getExecutionEnvironment();
        execEnv.setParallelism(parallelism);
        StreamTableEnvironment tEnv =
                StreamTableEnvironment.create(execEnv, EnvironmentSettings.inStreamingMode());
        String bootstrapServers = String.join(",", clientConf.get(ConfigOptions.BOOTSTRAP_SERVERS));
        // crate catalog using sql
        tEnv.executeSql(
                String.format(
                        "create catalog %s with ('type' = 'fluss', '%s' = '%s')",
                        CATALOG_NAME, BOOTSTRAP_SERVERS.key(), bootstrapServers));
        tEnv.executeSql("use catalog " + CATALOG_NAME);

        tEnv.executeSql(
                "create table test_partitioned("
                        + "a int, b string, c varchar, primary key(a, c) not enforced"
                        + ") partitioned by (c) "
                        + "with ("
                        + "'table.auto-partition.enabled' = 'true',"
                        + "'table.auto-partition.time-unit' = 'day',"
                        + "'scan.partition.discovery.interval' = '100ms',"
                        + "'table.auto-partition.num-precreate' = '1')");

        TablePath tablePath = TablePath.of("fluss", "test_partitioned");
        Map<Long, String> partitionNameById =
                waitUntilPartitions(FLUSS_CLUSTER_EXTENSION.getZooKeeperClient(), tablePath, 1);

        Collection<String> partitions = partitionNameById.values();

        // prepare table data
        try (com.alibaba.fluss.client.table.Table table = conn.getTable(tablePath)) {
            UpsertWriter upsertWriter = table.getUpsertWriter();
            RowType rowType = table.getDescriptor().getSchema().toRowType();
            for (int i = 1; i <= 3; i++) {
                for (String partition : partitions) {
                    Object[] values = new Object[] {i, "address" + i, partition};
                    upsertWriter.upsert(compactedRow(rowType, values));
                    // make sure every bucket has records
                    upsertWriter.flush();
                }
            }
        }

        Table table =
                tEnv.sqlQuery(
                        "select * from test_partitioned /*+ OPTIONS('scan.startup.mode' = 'latest') */");
        tEnv.toChangelogStream(table).addSink(new DiscardingSink<>());

        JobGraph jobGraph = execEnv.getStreamGraph().getJobGraph();

        JobID jobId = jobGraph.getJobID();

        MiniClusterWithClientResource cluster = clusterFactory.get();
        cluster.before();
        ClusterClient<?> client = cluster.getClusterClient();

        String savePointPath;

        try {
            client.submitJob(jobGraph).get();
            waitForAllTaskRunning(cluster.getMiniCluster(), jobId, false);
            Thread.sleep(5000);

            // now, stop the job with save point
            savePointPath =
                    client.cancelWithSavepoint(jobId, null, SavepointFormatType.CANONICAL).get();

            execEnv = StreamExecutionEnvironment.getExecutionEnvironment();
            execEnv.setParallelism(parallelism);
            tEnv = StreamTableEnvironment.create(execEnv, EnvironmentSettings.inStreamingMode());
            // crate catalog using sql
            tEnv.executeSql(
                    String.format(
                            "create catalog %s with ('type' = 'fluss', '%s' = '%s')",
                            CATALOG_NAME, BOOTSTRAP_SERVERS.key(), bootstrapServers));
            tEnv.executeSql("use catalog " + CATALOG_NAME);
            table =
                    tEnv.sqlQuery(
                            "select * from test_partitioned  /*+ OPTIONS('scan.startup.mode' = 'latest') */");
            tEnv.toChangelogStream(table).addSink(new DiscardingSink<>());
            jobGraph = execEnv.getStreamGraph().getJobGraph();
            SavepointRestoreSettings savepointRestoreSettings =
                    SavepointRestoreSettings.forPath(savePointPath, false, RestoreMode.CLAIM.CLAIM);
            jobGraph.setSavepointRestoreSettings(savepointRestoreSettings);
            client.submitJob(jobGraph).get();
            jobId = jobGraph.getJobID();

            waitForAllTaskRunning(cluster.getMiniCluster(), jobId, false);
            Thread.sleep(5000);
        } finally {
            cluster.after();
        }
    }
}
```

We will found the the following message after the job starts:
```
Subscribe to read log for split log-0-0 from offset 3.
```

After restore from savepoint, found the the following message
```
Subscribe to read log for split log-0-0 from offset 0.
```
It's not expected to subscribe from offset 0

### Solution

The resaon is that when init `LogSplitState` from `LogSplit`, it won't use the the log offset of `LogSplit` to  set  `LogSplitState`'s current offset.. So the default value of offset of `LogSplitState` is 0...If no any records are read, the offset will be always be 0..

Then restore from checkpoint, the `LogSplit` will be stored from `LogSplitState` which incure zero log offset of `LogSplit`..

The `HybridSnapshotLogSplit` has the same problem..

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by luoyuxia**
### Purpose

Linked issue: close #358

To fix the issue that split will lose offset when restore from state.

When init the SplitState from split, SplitState should use the logoffset from split to init.

### Tests

UT: SourceSplitStateTest
IT: Let's add the IT that restore from savapoint in #280

### CODE REVIEW

File: fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/source/split/HybridSnapshotLogSplitState.java [hunk 1]
```diff
@@ -26,10 +26,13 @@ public class HybridSnapshotLogSplitState extends SourceSplitState {
     private boolean snapshotFinished;
 
     /** The next log offset to read. */
-    private long offset;
+    private long currentOffset;
```
Comment (wuchong) [inline fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/source/split/HybridSnapshotLogSplitState.java]: Maybe `nextOffset` to be align with the comment? The `currentOffset` may confuse users this the offset that just read to.

File: fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/source/state/SourceSplitStateTest.java [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+import com.alibaba.fluss.connector.flink.source.split.LogSplit;
+import com.alibaba.fluss.connector.flink.source.split.LogSplitState;
+import com.alibaba.fluss.metadata.TableBucket;
+
+import org.junit.jupiter.api.Test;
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+/** Test for {@link LogSplitState} and {@link HybridSnapshotLogSplitState} . */
+class SourceSplitStateTest {
```
Comment (wuchong) [inline fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/source/state/SourceSplitStateTest.java:30]: Add such a test for lakehouse module as well?

**Review by wuchong — APPROVED** [review]
LGTM.
