### PR TITLE
[client] LookupSender get table info from LookupQuery

### LINKED ISSUE #2092: LookupSender#groupByLeaderAndType may enter a busy loop when `tableInfo` is missing from the metadata
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.8.0 (latest release)

### Please describe the bug 🐞

`LookupSender#groupByLeaderAndType` may enter a busy loop when `tableInfo` is missing from the metadata.

The reason is that `metadataUpdater.leaderFor()` will first `getTableInfo` from `metadateUpdater`, this operation will throw an exception which will be catch by `LookupSender#groupByLeaderAndType` and never return.

### Solution

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by swuferhong**
### Purpose

Linked issue: close #2092 

This pr will change the way `LookupSender` get `tableInfo` from `MetadataUpdater` to `LookupQuery`.

### CODE REVIEW

File: fluss-client/src/main/java/org/apache/fluss/client/lookup/LookupClient.java [hunk 1]
```diff
@@ -78,14 +79,17 @@ private ExecutorService createThreadPool() {
...
+            TableInfo tableInfo, TableBucket tableBucket, byte[] keyBytes) {
+        LookupQuery lookup = new LookupQuery(tableInfo.getTablePath(), tableBucket, keyBytes);
         lookupQueue.appendLookup(lookup);
         return lookup.future();
     }
 
-    public CompletableFuture<List<byte[]>> prefixLookup(TableBucket tableBucket, byte[] keyBytes) {
-        PrefixLookupQuery prefixLookup = new PrefixLookupQuery(tableBucket, keyBytes);
+    public CompletableFuture<List<byte[]>> prefixLookup(
+            TableInfo tableInfo, TableBucket tableBucket, byte[] keyBytes) {
```
Comment (wuchong) [inline fluss-client/src/main/java/org/apache/fluss/client/lookup/LookupClient.java]: Use `TablePath` is enough?

File: fluss-client/src/main/java/org/apache/fluss/client/lookup/LookupClient.java [hunk 2]
```diff
@@ -78,14 +79,17 @@ private ExecutorService createThreadPool() {
         return Executors.newFixedThreadPool(1, new ExecutorThreadFactory(LOOKUP_THREAD_PREFIX));
     }
 
-    public CompletableFuture<byte[]> lookup(TableBucket tableBucket, byte[] keyBytes) {
-        LookupQuery lookup = new LookupQuery(tableBucket, keyBytes);
+    public CompletableFuture<byte[]> lookup(
+            TableInfo tableInfo, TableBucket tableBucket, byte[] keyBytes) {
```
Comment (wuchong) [inline fluss-client/src/main/java/org/apache/fluss/client/lookup/LookupClient.java]: Use `TablePath` is enough?

**Review by wuchong — APPROVED** [review]
