### PR TITLE
[flink] Introduce catalog procedure for acl operation.

### LINKED ISSUE #871: Expose ACL operation to Flink Call
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Motivation

Currently, com.alibaba.fluss.client.admin.Admin already supports acl operation. However, it's not easy for user to use it in java application.

Expose it to flink call, then user can use easily with Flink SQL.

### Solution

We can refer what paimon implements flink call.

In paimon, Procedures are provided by SPI ([ProcedureUtil.java#L37].(https://github.com/apache/paimon/blob/371fa748ce7b03ab12012656c8e39e20062439bb/paimon-flink/paimon-flink-common/src/main/java/org/apache/paimon/flink/procedure/ProcedureUtil.java#L37))

Procedure should extends org.apache.paimon.flink.procedure.ProcedureBase. And the identifier is same with path of procedure.
```java
public abstract class ProcedureBase implements Procedure, Factory {
}
```

the param is declared with @ProcedureHint
```java
//org.apache.paimon.flink.procedure.CloneProcedure
public class CloneProcedure extends ProcedureBase {
    public static final String IDENTIFIER = "clone";

    @ProcedureHint(
            argument = {
                @ArgumentHint(
                        name = "warehouse",
                        type = @DataTypeHint("STRING"),
                        isOptional = true),
                @ArgumentHint(name = "database", type = @DataTypeHint("STRING"), isOptional = true),
                @ArgumentHint(name = "table", type = @DataTypeHint("STRING"), isOptional = true),
                @ArgumentHint(
                        name = "catalog_conf",
                        type = @DataTypeHint("STRING"),
                        isOptional = true),
                @ArgumentHint(name = "target_warehouse", type = @DataTypeHint("STRING")),
                @ArgumentHint(
                        name = "target_database",
                        type = @DataTypeHint("STRING"),
                        isOptional = true),
                @ArgumentHint(
                        name = "target_table",
                        type = @DataTypeHint("STRING"),
                        isOptional = true),
                @ArgumentHint(
                        name = "target_catalog_conf",
                        type = @DataTypeHint("STRING"),
                        isOptional = true),
                @ArgumentHint(name = "parallelism", type = @DataTypeHint("INT"), isOptional = true)
            })
    public String[] call(
            ProcedureContext procedureContext,
            String warehouse,
            String database,
            String tableName,
            String sourceCatalogConfigStr,
            String targetWarehouse,
            String targetDatabase,
            String targetTableName,
            String targetCatalogConfigStr,
            Integer parallelismStr)
            throws Exception {
}

```

Then user can use it in flink call, See https://paimon.apache.org/docs/master/flink/procedures/

### Anything else?

_No response_

### Willingness to contribute

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by loserwang1024**
### Purpose

Linked issue: close #871

### CODE REVIEW

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/catalog/FlinkCatalog.java [hunk 1]
```diff
@@ -633,6 +636,26 @@ protected TablePath toTablePath(ObjectPath objectPath) {
         return TablePath.of(objectPath.getDatabaseName(), objectPath.getObjectName());
     }
 
+    @Override
+    public List<String> listProcedures(String dbName)
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/catalog/FlinkCatalog.java:640]: Add `SHOW PROCEDURES` and `SHOW PROCEDURES FROM catalog_name.database_name` tests

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/procedure/ProcedureUtil.java [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+import java.util.ServiceLoader;
+import java.util.stream.Collectors;
+
+/** ProcedureUtil to load procedure. */
+public class ProcedureUtil {
+    private static final String SYSTEM_DATABASE_NAME = "sys";
+    private static final Logger LOG = LoggerFactory.getLogger(ProcedureUtil.class);
+
+    public static List<String> listProcedures() {
+        final List<ProcedureBase> discoverProcedures = discoverProcedures();
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/procedure/ProcedureUtil.java]: We don't need to make the procedures plugable, just hard code it to a static map.

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/procedure/AclProcedure.java [hunk 3]
```diff
@@ -0,0 +1,230 @@
...
+import com.alibaba.fluss.security.acl.ResourceFilter;
+
+import org.apache.flink.table.procedure.ProcedureContext;
+
+import java.util.Collection;
+import java.util.Collections;
+import java.util.concurrent.ExecutionException;
+
+/** {@link org.apache.flink.table.procedures.Procedure} to operate acl. */
+public class AclProcedure extends ProcedureBase {
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/procedure/AclProcedure.java]: Let's seprate the acl call into 3 calls, because they have different number of parameters, combining them into one call is hard to use for users. 
```
sys.add_acl(..)
sys.drop_acl(..)
sys.list_acl(..)
```

File: fluss-test-coverage/pom.xml [hunk 4]
```diff
@@ -327,6 +327,7 @@
                                         <exclude>com.alibaba.fluss.rocksdb.RocksIteratorWrapper
                                         </exclude>
                                         <exclude>com.alibaba.fluss.plugin.PluginUtils</exclude>
+                                        <exclude>com.alibaba.fluss.flink.procedure.ProcedureUtil</exclude>
```
Comment (wuchong) [inline fluss-test-coverage/pom.xml]: Let's check it again, if the coverage if passes after we added tests and refactored `ProcedureUtil`.

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/procedure/AclProcedure.java [hunk 5]
```diff
@@ -0,0 +1,230 @@
...
+     * @param action Actoion of ACL operation to perform. Valid values are:
+     *     <ul>
+     *       <li>{@code ADD}: Adds an ACL entry.
+     *       <li>{@code DROP}: Removes an ACL entry.
+     *       <li>{@code LIST}: Lists matching ACL entries.
+     *     </ul>
+     *
+     * @param resource Resource on which the ACL operation applies. The format must be one of:
+     *     <ul>
+     *       <li>{@code fluss-cluster} - cluster level
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/procedure/AclProcedure.java]: Use `cluster` to represent

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/procedure/AclProcedure.java [hunk 6]
```diff
@@ -0,0 +1,230 @@
...
+     *       <li>{@code fluss-cluster.db_name} - database level
+     *       <li>{@code fluss-cluster.db_name.table_name} - table level
+     *     </ul>
+     *
+     * @param permission Permission type to grant or revoke. Common values include in {@link
+     *     PermissionType}.
+     * @param principal Principal (user or role) to apply the ACL to. Accepts:
+     *     <ul>
+     *       <li>{@code ANY}
+     *       <li>{@code ALL}
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/procedure/AclProcedure.java]: Add tests to verify the case insensitive

File: fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/procedure/AclProcedure.java [hunk 7]
```diff
@@ -0,0 +1,230 @@
...
+                                        new AccessControlEntryFilter(
+                                                flussPrincipal, host, operationType, permission)))
+                        .get();
+        return aclBindings.stream()
+                .map(
+                        aclBinding -> {
+                            Resource matchResourceresource = aclBinding.getResource();
+                            AccessControlEntry entry = aclBinding.getAccessControlEntry();
+                            return String.format(
+                                    "| %s | %s | %s | %s | %s | %s |",
```
Comment (wuchong) [inline fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/procedure/AclProcedure.java]: Change to json format

**Comment by loserwang1024** [comment]
@wuchong , I have modified it based on your CR. Please help review again.

**Review by wuchong — APPROVED** [review]
