### PR TITLE
[flink] Disable count push down for lake enabled table and catch exce…

### LINKED ISSUE #1667: Unify the behavior of streaming read
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Description

1: If lake source implementation is not found in classpath, throw exception
2: Currently, not to support count push down for lake enabled table, otherwise it'll cause miss count data in lake

### Willingness to contribute

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by caozhen1937**
…ption when create lake source

### Purpose

Linked issue: close #1667

### CODE REVIEW

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/FlinkTableSource.java [hunk 1]
```diff
@@ -567,7 +570,8 @@ public boolean applyAggregates(
                 || aggregateExpressions.size() != 1
                 || hasPrimaryKey()
                 || groupingSets.size() > 1
-                || (groupingSets.size() == 1 && groupingSets.get(0).length > 0)) {
+                || (groupingSets.size() == 1 && groupingSets.get(0).length > 0)
+                || isDataLakeEnabled) {
```
Comment (luoyuxia) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/FlinkTableSource.java:577]: add comment for why dataLakeEnabled is not supported for aggregate

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/utils/LakeSourceUtils.java [hunk 2]
```diff
@@ -60,19 +60,16 @@ public static LakeSource<LakeSplit> createLakeSource(
         try {
             lakeStoragePlugin = LakeStoragePluginSetUp.fromDataLakeFormat(dataLake, null);
         } catch (UnsupportedOperationException e) {
-            LOG.info(
-                    "No LakeStoragePlugin can be found for datalake format: {}, return null to disable reading from lake source.",
-                    dataLake);
-            return null;
+            throw new UnsupportedOperationException(
+                    "No LakeStoragePlugin can be found for datalake format: " + dataLake);
```
Comment (luoyuxia) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/utils/LakeSourceUtils.java]:
```suggestion
                   throw new UnsupportedOperationException(
                    String.format(
                            "No LakeStoragePlugin available for data lake format: %s. "
                                    + "To resolve this, ensure fluss-lake-%s.jar is in the classpath.",
                            dataLake, dataLake.toLowerCase()));
```

File: fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/utils/LakeSourceUtils.java [hunk 3]
```diff
@@ -60,19 +60,16 @@ public static LakeSource<LakeSplit> createLakeSource(
...
         }
         LakeStorage lakeStorage = checkNotNull(lakeStoragePlugin).createLakeStorage(lakeConfig);
         try {
             return (LakeSource<LakeSplit>) lakeStorage.createLakeSource(tablePath);
         } catch (UnsupportedOperationException e) {
-            LOG.info(
-                    "method createLakeSource throw UnsupportedOperationException for datalake format {}, return null as lakeSource to disable reading from lake source.",
-                    dataLake);
-            return null;
+            throw new UnsupportedOperationException(
```
Comment (luoyuxia) [inline fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/utils/LakeSourceUtils.java:73]:
```suggestion
            throw new UnsupportedOperationException(
    String.format("Table using '%s' data lake format cannot be used as historical data in Fluss.", dataLake));
```
