### PR TITLE
[client] Consider empty tablet server metadata response as stale metadata & fix npe when detination to send and fetch can't be found in metadata

### LINKED ISSUE #605: Sender will retry forever while MetadataUtils.getOneAvailableTabletServerNode() throw FlussRuntimeException
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

main (development)

### Please describe the bug 🐞

Sender will retry forever while `MetadataUtils.getOneAvailableTabletServerNode()` throw `FlussRuntimeException`, it cannot be recovery:

Image

### Solution

Although now I don't know why it failed here, but when the exception `Caused by: com.alibaba.fluss.exception.FlussRuntimeException: no alive tablet server in cluster` is thrown, we should be able to recover by using the `tryToInitializeCluster` method.

Update:
After checking the root cause, it turns out that when one `tabletServer` is killed, there is a period during which the `metadataUpdater` request metadata from the server that does not include the killed `tabletServer`. As a result, `metadataUpdater.getTabletServer()` will return null. However, we currently do not have protection in place for this scenario, leading to a `NullPointerException (NPE) `when creating the `Gateway`. The affected behaviors include `Sender`, `LogFetcher#sendFetchRequest()`, and `LookupSender#sendLookups()`. Therefore, it is necessary to systematically reconsider the design of the client metadata as mentioned in issue: #483

Image

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by luoyuxia**
### Purpose

Linked issue: close #605 

The pr will to try fix three problems:

1. no any alive tablet available to request metadata
2. the destinaion to send write batch can't be found in  metadata cache to cause NPE
3. the destinaion to fetcj can't be found in  metadata cache to cause NPE

Note the lookup, limit scan will also have the problem of NPE, but now, let's foucus on write and read.

### Brief change log

1. some time, if client request metadata from a startingup tablet server, the tablet server will return empty metadata, we consider it as stale metadata and not to accept the metadata. Otherwise, we'll get into no alive tablet available to request metadata again
2. if the destinaion node can't be found in  metadata cache, invalid the metadata so that it can request metadata again to get the destinaion node  evetually

### Tests

1. `MetadataUpdaterTest` verify empty metadata is not accepted
2. `testFetchWhenDestinationIsNullInMetadata` verify fetch when destination node is null in Metadata
3. `testSendWhenDestinationIsNullInMetadata` verify send when destination node is null in Metadata

### CODE REVIEW

File: fluss-client/src/main/java/com/alibaba/fluss/client/write/Sender.java [hunk 1]
```diff
@@ -329,25 +329,38 @@ private void sendWriteRequest(int destination, short acks, List<WriteBatch> batc
...
+        ServerNode destinationNode = metadataUpdater.getTabletServer(destination);
+        if (destinationNode == null) {
+            LOG.warn(
+                    "Server {} is not found in metadata cache, "
+                            + "going to request metadata update.",
+                    destination);
+            // invalidate the metadata to request metadata
+            invalidBucketMetadata(batches);
+            // requeue the write batch
+            batches.forEach(this::reEnqueueBatch);
```
Comment (wuchong) [inline fluss-client/src/main/java/com/alibaba/fluss/client/write/Sender.java]: We can unify the logic with `handleWriteRequestException`. The batch re-enqueue is more complex than just calling `reEnqueueBatch`.

File: fluss-client/src/main/java/com/alibaba/fluss/client/table/scanner/log/LogFetcher.java [hunk 2]
```diff
@@ -192,28 +193,39 @@ public void wakeup() {
...
+            // invalid the metadata to request metadata update
+            LOG.warn(
+                    "Server {} is not found in metadata cache, "
+                            + "going to request metadata update.",
+                    destination);
+            invalidTableOrPartitions(tableOrPartitionsInFetchRequest);
+            LOG.debug(
+                    "Removing pending request for node: {} due to the destination node is not found in metadata cache",
+                    destination);
+            nodesWithPendingFetchRequests.remove(destination);
```
Comment (wuchong) [inline fluss-client/src/main/java/com/alibaba/fluss/client/table/scanner/log/LogFetcher.java]: We can unify the logic with handle exception in `handleFetchLogResponse`.

**Comment by wuchong** [comment]
@luoyuxia I pushed a commit to apply some minor improvements.

**Comment by luoyuxia** [comment]
> @luoyuxia I pushed a commit to apply some minor improvements.

Thanks for the patch. LGTM
