### PR TITLE
[connector] Fix partition state update and filter non-existent partitions on restore

### LINKED ISSUE #348: PartitionNotExistException will be thrown when restore from checkpoint
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

main (development)

### Please describe the bug 🐞

When remove a partition from Fluss, Flink will discovery the removed partition,  and send partition removed event to source reader, source reader will then unsubstribe the partition.. But the partition won't be removed from the state of the soure reader.. When restore, the soure reader will still try to substribe  the partitiion assigned, but since it has been removed from fluss.. It'll then throw `PartitionNotExistException`.. 

Can be reproduced by the following ITCase:
```
class FlinkTableSourceFailOverITCase {

    private static final String CATALOG_NAME = "testcatalog";

    @RegisterExtension
    public static final FlussClusterExtension FLUSS_CLUSTER_EXTENSION =
            FlussClusterExtension.builder()
                    .setClusterConf(
                            new com.alibaba.fluss.config.Configuration()
                                    // set snapshot interval to 1s for testing purposes
                                    .set(ConfigOptions.KV_SNAPSHOT_INTERVAL, Duration.ofSeconds(1))
                                    // not to clean snapshots for test purpose
                                    .set(
                                            ConfigOptions.KV_MAX_RETAINED_SNAPSHOTS,
                                            Integer.MAX_VALUE))
                    .setNumOfTabletServers(3)
                    .build();

    @TempDir File checkpointDir;
    @TempDir File savepointDir;

    protected static Connection conn;
    protected static Admin admin;

    protected static com.alibaba.fluss.config.Configuration clientConf;

    @BeforeAll
    protected static void beforeAll() {
        clientConf = FLUSS_CLUSTER_EXTENSION.getClientConfig();
        conn = ConnectionFactory.createConnection(clientConf);
        admin = conn.getAdmin();
    }

    @Test
    void testRestore() throws Exception {
        final int numTaskManagers = 2;
        final int numSlotsPerTaskManager = 2;
        final int parallelism = numTaskManagers * numSlotsPerTaskManager;

        final MiniClusterResourceFactory clusterFactory =
                new MiniClusterResourceFactory(
                        numTaskManagers,
                        numSlotsPerTaskManager,
                        getFileBasedCheckpointsConfig(savepointDir));

        StreamExecutionEnvironment execEnv = StreamExecutionEnvironment.getExecutionEnvironment();
        execEnv.setParallelism(parallelism);
        StreamTableEnvironment tEnv =
                StreamTableEnvironment.create(execEnv, EnvironmentSettings.inStreamingMode());
        String bootstrapServers = String.join(",", clientConf.get(ConfigOptions.BOOTSTRAP_SERVERS));
        // crate catalog using sql
        tEnv.executeSql(
                String.format(
                        "create catalog %s with ('type' = 'fluss-aplus', '%s' = '%s')",
                        CATALOG_NAME, BOOTSTRAP_SERVERS.key(), bootstrapServers));
        tEnv.executeSql("use catalog " + CATALOG_NAME);

        tEnv.executeSql(
                "create table test_partitioned("
                        + "a int, b varchar"
                        + ") partitioned by (b) "
                        + "with ("
                        + "'table.auto-partition.enabled' = 'true',"
                        + "'table.auto-partition.time-unit' = 'year',"
                        + "'scan.partition.discovery.interval' = '100ms',"
                        + "'table.auto-partition.num-precreate' = '1')");

        tEnv.executeSql(
                "create temporary table test_partitioned_sink(a int, b varchar) with ('connector' = 'blackhole')");

        Table table = tEnv.sqlQuery("select * from test_partitioned");
        tEnv.toDataStream(table).addSink(new DiscardingSink<>());

        JobGraph jobGraph = execEnv.getStreamGraph().getJobGraph();

        JobID jobId = jobGraph.getJobID();

        MiniClusterWithClientResource cluster = clusterFactory.get();
        cluster.before();
        ClusterClient<?> client = cluster.getClusterClient();

        String savePointPath;

        try {
            client.submitJob(jobGraph).get();
            waitForAllTaskRunning(cluster.getMiniCluster(), jobId, false);

            // create a partition manually
            FlinkTestBase.createPartitions(
                    FLUSS_CLUSTER_EXTENSION.getZooKeeperClient(),
                    TablePath.of("fluss", "test_partitioned"),
                    Collections.singletonList("2000"));
            // wait from a while to wait the source discovery the partition changes.
            Thread.sleep(3000);

            // drop a partition manually,
            FlinkTestBase.dropPartitions(
                    FLUSS_CLUSTER_EXTENSION.getZooKeeperClient(),
                    TablePath.of("fluss", "test_partitioned"),
                    Collections.singleton("2000"));

            // wait from a while to wait the source unsubscribe the partition
            Thread.sleep(3000);

            // now, stop the job with save point
            savePointPath =
                    client.cancelWithSavepoint(jobId, null, SavepointFormatType.CANONICAL).get();

            execEnv = StreamExecutionEnvironment.getExecutionEnvironment();
            execEnv.setParallelism(parallelism);
            tEnv = StreamTableEnvironment.create(execEnv, EnvironmentSettings.inStreamingMode());
            // crate catalog using sql
            tEnv.executeSql(
                    String.format(
                            "create catalog %s with ('type' = 'fluss-aplus', '%s' = '%s')",
                            CATALOG_NAME, BOOTSTRAP_SERVERS.key(), bootstrapServers));
            tEnv.executeSql("use catalog " + CATALOG_NAME);
            table = tEnv.sqlQuery("select * from test_partitioned");
            tEnv.toDataStream(table).addSink(new DiscardingSink<>());
            jobGraph = execEnv.getStreamGraph().getJobGraph();
            SavepointRestoreSettings savepointRestoreSettings =
                    SavepointRestoreSettings.forPath(savePointPath, false, RestoreMode.CLAIM.CLAIM);
            jobGraph.setSavepointRestoreSettings(savepointRestoreSettings);
            client.submitJob(jobGraph).get();
            jobId = jobGraph.getJobID();

            waitForAllTaskRunning(cluster.getMiniCluster(), jobId, false);
        } finally {
            cluster.after();
        }
    }

    private Configuration getFileBasedCheckpointsConfig(File savepointDir) {
        return getFileBasedCheckpointsConfig(savepointDir.toURI().toString());
    }

    private Configuration getFileBasedCheckpointsConfig(final String savepointDir) {
        final Configuration config = new Configuration();
        config.set(StateBackendOptions.STATE_BACKEND, "hashmap");
        config.set(CheckpointingOptions.CHECKPOINTS_DIRECTORY, checkpointDir.toURI().toString());
        config.set(CheckpointingOptions.FS_SMALL_FILE_THRESHOLD, MemorySize.ZERO);
        config.set(CheckpointingOptions.SAVEPOINT_DIRECTORY, savepointDir);
        return config;
    }

    private static class MiniClusterResourceFactory {
        private final int numTaskManagers;
        private final int numSlotsPerTaskManager;
        private final Configuration config;

        private MiniClusterResourceFactory(
                int numTaskManagers, int numSlotsPerTaskManager, Configuration config) {
            this.numTaskManagers = numTaskManagers;
            this.numSlotsPerTaskManager = numSlotsPerTaskManager;
            this.config = config;
        }

        MiniClusterWithClientResource get() {
            return new MiniClusterWithClientResource(
                    new MiniClusterResourceConfiguration.Builder()
                            .setConfiguration(config)
                            .setNumberTaskManagers(numTaskManagers)
                            .setNumberSlotsPerTaskManager(numSlotsPerTaskManager)
                            .build());
        }
    }
}
```

When run the test, we can see the following exception:
```
Caused by: com.alibaba.fluss.exception.FlussRuntimeException: Failed to update metadata
	at com.alibaba.fluss.client.metadata.MetadataUpdater.updateMetadata(MetadataUpdater.java:272) ~[classes/:?]
	at com.alibaba.fluss.client.metadata.MetadataUpdater.checkAndUpdatePartitionMetadata(MetadataUpdater.java:228) ~[classes/:?]
	at com.alibaba.fluss.client.scanner.log.FlussLogScanner.subscribe(FlussLogScanner.java:196) ~[classes/:?]
	at com.alibaba.fluss.connector.flink.source.reader.FlinkSourceSplitReader.subscribeLog(FlinkSourceSplitReader.java:243) ~[classes/:?]
	at com.alibaba.fluss.connector.flink.source.reader.FlinkSourceSplitReader.handleSplitsChanges(FlinkSourceSplitReader.java:188) ~[classes/:?]
	at org.apache.flink.connector.base.source.reader.fetcher.AddSplitsTask.run(AddSplitsTask.java:51) ~[flink-connector-base-1.20.0.jar:1.20.0]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:165) ~[flink-connector-base-1.20.0.jar:1.20.0]
	... 6 more
```

### Solution

1: when source reader recieve the partition removed event, split source reader should mark it as finished so that it can be removed from split state, so that the removed partition won't be restored to subscribe

2: it may still happens that Fluss drop a partition, but split source reader haven't been aware of it.. After restore, it'll try to subscribe the removed partition which cause the `PartitionNotExistException`.. We may need to warn it instead of throwing exception direclty..

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by codope**
### Purpose

Linked issue: close #348 

This PR fixes an issue where removed partitions were still retained in the source reader’s state. Upon recovery, the source attempted to re-subscribe to non-existent partitions, leading to a `PartitionNotExistException`.

#### Changes
- **Mark Finished Splits on Partition Removal:**  
  Active bounded splits are now marked as finished when a partition removal event is received. This prevents removed partitions from being restored.
  
- **Remove Pending Snapshot Splits and Unsubscribe Buckets:**  
  Pending snapshot splits and subscribed log buckets associated with removed partitions are removed and unsubscribed respectively.
  
- **Filter Non-existent Partitions During Restore:**  
  The `subscribeLog` method now catches `PartitionNotExistException` and logs a warning instead of failing, filtering out any non-existent partitions on restore.

### Tests

Added `FlinkTableSourceFailOverITCase` integration test.

### API and Format

None

### Documentation

NA

### CODE REVIEW

File: fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/source/FlinkTableSourceFailOverITCase.java [hunk 1]
```diff
@@ -0,0 +1,223 @@
...
+            client.submitJob(jobGraph).get();
+            waitForAllTaskRunning(cluster.getMiniCluster(), jobId, false);
+
+            // create a partition manually
+            FlinkTestBase.createPartitions(
+                    FLUSS_CLUSTER_EXTENSION.getZooKeeperClient(),
+                    TablePath.of("fluss", "test_partitioned"),
+                    Collections.singletonList("2000"));
+            // wait from a while to wait the source discovery the partition changes.
+            Thread.sleep(3000);
```
Comment (codope) [inline fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/source/FlinkTableSourceFailOverITCase.java]: I tried to increase the wait time to 5s and run the test 50 times repeatedly, still could not reproduce the issue.

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java [hunk 2]
```diff
@@ -241,18 +250,38 @@ private void subscribeLog(SourceSplitBase split, long startingOffset) {
...
+                    logScanner.subscribe(partitionId, bucket, startingOffset);
+                } else {
+                    // If no partition id, subscribe by bucket only.
+                    logScanner.subscribe(bucket, startingOffset);
+                }
+            } catch (Exception e) {
+                // Traverse the exception chain to check for PartitionNotExistException.
+                Throwable cause = e;
+                boolean partitionNotExist = false;
+                while (cause != null) {
```
Comment (wuchong) [inline fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java]: nit: we can replace the while loop using 

```java
boolean partitionNotExist = ExceptionUtils.findThrowable(e, PartitionNotExistException.class).isPresent();
```

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java [hunk 3]
```diff
@@ -262,17 +291,42 @@ public Set<TableBucket> removePartitions(Map<Long, String> removedPartitions) {
...
+                    closeCurrentBoundedSplit();
+                    unsubscribedTableBuckets.add(currentBucket);
+                    LOG.info(
+                            "Mark current bounded split {} as finished for removed partition {}.",
+                            currentBucket,
+                            removedPartitions.get(currentBucket.getPartitionId()));
+                } catch (IOException e) {
+                    LOG.warn(
+                            "Failed to close current bounded split for removed partition {}.",
+                            currentBucket.getPartitionId(),
```
Comment (wuchong) [inline fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java]: nit: we can also use `removedPartitions.get(currentBucket.getPartitionId())` to print the partition name rather than id.

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java [hunk 4]
```diff
@@ -241,18 +250,38 @@ private void subscribeLog(SourceSplitBase split, long startingOffset) {
...
+                        partitionNotExist = true;
+                        break;
+                    }
+                    cause = cause.getCause();
+                }
+                if (partitionNotExist) {
+                    LOG.warn(
+                            "Partition {} does not exist when subscribing to log for split {}. Skipping subscription.",
+                            partitionId,
+                            split.splitId());
```
Comment (wuchong) [inline fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java]: should `return` to avoid unnecessary subscribe the partition.

**Comment by wuchong** [comment]
Thanks @codope for the contribution! The fixing looks good to me. I pushed a commit to improve the IT case so that:
1. avoid `Thread.sleep(..)` as it will lead tests unstable if CPU is high.
2. Verify with data instead of verifying with no exception.
3. the new IT case can also reproduce the original exception mentioned in issue description. 

Could you help to review the changes @luoyuxia ?

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java [hunk 5]
```diff
@@ -262,17 +287,42 @@ public Set<TableBucket> removePartitions(Map<Long, String> removedPartitions) {
         // todo, may consider to close the current snapshot reader if
```
Comment (luoyuxia) [inline fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java]: The todo comment can be removed now since in this pr, we wil close currentBoundedSplit

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java [hunk 6]
```diff
@@ -145,6 +149,12 @@ public RecordsWithSplitIds<RecordAndPos> fetch() throws IOException {
                                 new HashSet<>(emptyLogSplits), flinkSourceReaderMetrics);
                 emptyLogSplits.clear();
                 return records;
+            } else if (!removedSplits.isEmpty()) {
```
Comment (luoyuxia) [inline fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java]: I think we can check `!removedSplits.isEmpty()` at the beginning so that the flink enumerate can remove the state of removed splits as soon as possible.

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java [hunk 7]
```diff
@@ -241,18 +251,33 @@ private void subscribeLog(SourceSplitBase split, long startingOffset) {
...
             Long partitionId = tableBucket.getPartitionId();
             int bucket = tableBucket.getBucket();
-            if (partitionId != null) {
-                logScanner.subscribe(partitionId, bucket, startingOffset);
-            } else {
-                logScanner.subscribe(bucket, startingOffset);
+            try {
+                if (partitionId != null) {
+                    // Try to subscribe using the partition id.
+                    logScanner.subscribe(partitionId, bucket, startingOffset);
```
Comment (luoyuxia) [inline fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java:258]: nit:
I think we can limit the try catch scope to only this line since only subscribe a partition, the partitionNotExist will be thrown. 
I'd like suggest to be:
```
            if (partitionId != null) {
                // Try to subscribe using the partition id.
                try {
                    logScanner.subscribe(partitionId, bucket, startingOffset);
                } catch (Exception e) {
                    // the PartitionNotExistException may still happens when partition is removed
                    // but Flink source reader failover before aware of it
                    // Traverse the exception chain to check for PartitionNotExistException.
                    boolean partitionNotExist =
                            ExceptionUtils.findThrowable(e, PartitionNotExistException.class)
                                    .isPresent();
                    if (partitionNotExist) {
                        // mark the not exist partition to be removed
                        removedSplits.add(split.splitId());
                        LOG.warn(
                                "Partition {} does not exist when subscribing to log for split {}. Skipping subscription.",
                                partitionId,
                                split.splitId());
                        return;
                    }
                }
            } else {
                // If no partition id, subscribe by bucket only.
                logScanner.subscribe(bucket, startingOffset);
            }
```

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java [hunk 8]
```diff
@@ -241,18 +251,33 @@ private void subscribeLog(SourceSplitBase split, long startingOffset) {
...
+                    // If no partition id, subscribe by bucket only.
+                    logScanner.subscribe(bucket, startingOffset);
+                }
+            } catch (Exception e) {
+                // Traverse the exception chain to check for PartitionNotExistException.
+                boolean partitionNotExist =
+                        ExceptionUtils.findThrowable(e, PartitionNotExistException.class)
+                                .isPresent();
+                if (partitionNotExist) {
+                    LOG.warn(
```
Comment (luoyuxia) [inline fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java]: We also should mark split as removed since the partition is removed and so that flink enumerator can remove this split state.

**Review by luoyuxia — COMMENTED** [review]
Thanks @codope @wuchong Overall LGTM. Just left minor comments.

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java (hunk 6 above)
Comment (wuchong) [reply fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java]: Yes, we can move the code block at the beginning of `fetch()` method, because the `currentBoundedSplitReader` may still work in progress.

**Comment by wuchong** [comment]
@codope do you have time to address @luoyuxia 's comments? If you are busy, I can help with that.

**Comment by codope** [comment]
Thanks for the review @wuchong and @luoyuxia . I will address your comments by Tue, 25th Feb.

File: fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java (hunk 6 above)
Comment (codope) [reply fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java]: That makes sense. I have moved it to the beginning of `fetch`

**Comment by codope** [comment]
@luoyuxia @wuchong I have addressed all the comments. Please take a look again.

**Review by wuchong — APPROVED** [review]
LGTM.

**Review by luoyuxia — APPROVED** [review]
@codope Thanks for updating.. LGTM!
