### PR TITLE
[bug][coordinator/kv] delete remote kv dir for table on coordinator server

### LINKED ISSUE #296: [Improve] Delete table's remote kv directory for coordinator server.
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

main

### Minimal reproduce step

This is sub task of issue #121, for deleting table's remote kv directory for coordinator server.

### What doesn't meet your expectations?

No

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Vipamp**
### Purpose

Linked issue: close #296 

### Tests
KvSnapshotITCase#testKvSnapshotAndDelete

### CODE REVIEW

**Comment by Vipamp** [comment]
> @Vipamp Is this pr ready for review?

Yes，i have finished it，i am sorry that i didn't tell you for review.

File: fluss-common/src/main/java/com/alibaba/fluss/utils/FlussPaths.java [hunk 1]
```diff
@@ -586,6 +587,35 @@ public static FsPath remoteKvTabletDir(
...
+     * <pre>
+     * Remote kv table dir
+     * {$remote.data.dir}/kv/{databaseName}/{tableName}-{tableId}
+     *
+     * Remote log table dir.
+     * {$remote.data.dir}/log/{databaseName}/{tableName}-{tableId}
+     *
+     * </pre>
+     *
+     * @param remoteKvOrLogBaseDir - the remote kv snapshots or log segments root dir of specific
```
Comment (luoyuxia) [inline fluss-common/src/main/java/com/alibaba/fluss/utils/FlussPaths.java]: nit:
```suggestion
     * @param remoteKvOrLogBaseDir - the remote kv snapshots or log segments root dir of tables
```

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorServer.java [hunk 2]
```diff
@@ -180,9 +180,11 @@ protected void startServices() throws Exception {
             // up.
             // in HA for coordinator server, the processor also need to know the leader node during
             // start up
+            RemoteStorageHandler remoteStorageHandler = new RemoteStorageHandler(conf);
             this.coordinatorEventProcessor =
                     new CoordinatorEventProcessor(
                             zkClient,
+                            remoteStorageHandler,
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorServer.java]: nit: not to define local variable, just pass `new RemoteStorageHandler(conf)`;

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+import com.alibaba.fluss.fs.FileSystem;
+import com.alibaba.fluss.fs.FsPath;
+import com.alibaba.fluss.metadata.TablePath;
+import com.alibaba.fluss.utils.FlussPaths;
+
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+import java.io.IOException;
+
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java]: Please add comments for this class..

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+public class RemoteStorageHandler {
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java]: Rename it to `RemoteStorageCleaner` ? as now it's only for delete remote storage dir....

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+
+    private final FsPath remoteKvDir;
+    private final FileSystem remoteFileSystem;
+
+    public RemoteStorageHandler(Configuration configuration) throws IOException {
+        this.remoteKvDir = FlussPaths.remoteKvDir(configuration);
+        this.remoteFileSystem = remoteKvDir.getFileSystem();
+    }
+
+    public void createTableKvDir(TablePath tablePath, long tableId) throws IOException {
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java]: do not introudce this method  since it's only for testing... introduce code used only in testing will make it hard to maintain.

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+        remoteFileSystem.mkdirs(tableKvDir(tablePath, tableId));
+    }
+
+    public void deleteTable(TablePath tablePath, long tableId) {
+        deleteDir(tableKvDir(tablePath, tableId));
+        // todo delete log segments file dirs of table.
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java]: Why don't delete log segments file dirs in this pr?

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+    }
+
+    public boolean isTableKvDirExists(TablePath tablePath, long tableId) throws IOException {
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java]: dito: do not introudce this method since it's only for testing

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java [hunk 8]
```diff
@@ -0,0 +1,73 @@
...
+        return isDirExists(tableKvDir(tablePath, tableId));
+    }
+
+    private boolean isDirExists(FsPath fsPath) throws IOException {
+        return remoteFileSystem.exists(fsPath);
+    }
+
+    private void deleteDir(FsPath fsPath) {
+        try {
+            if (isDirExists(fsPath)) {
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java]: nit: just use `remoteFileSystem.exists(fsPath)`

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java [hunk 9]
```diff
@@ -0,0 +1,73 @@
...
+                remoteFileSystem.delete(fsPath, true);
+                LOG.info("Delete table's remote dir {} success.", fsPath);
+            }
+        } catch (IOException e) {
+            LOG.error("Delete table's remote dir {} failed.", fsPath, e);
+        }
+    }
+
+    private FsPath tableKvDir(TablePath tablePath, long tableId) {
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java]:
```suggestion
    private FsPath tableKvRemoteDir(TablePath tablePath, long tableId) {
```

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java [hunk 10]
```diff
@@ -0,0 +1,73 @@
...
+    public RemoteStorageHandler(Configuration configuration) throws IOException {
+        this.remoteKvDir = FlussPaths.remoteKvDir(configuration);
+        this.remoteFileSystem = remoteKvDir.getFileSystem();
+    }
+
+    public void createTableKvDir(TablePath tablePath, long tableId) throws IOException {
+        remoteFileSystem.mkdirs(tableKvDir(tablePath, tableId));
+    }
+
+    public void deleteTable(TablePath tablePath, long tableId) {
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandler.java]:
```suggestion
    public void deleteTableRemoteDir(TablePath tablePath, long tableId) {
```

File: fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandlerTest.java [hunk 11]
```diff
@@ -0,0 +1,53 @@
...
+
+import org.junit.jupiter.api.BeforeAll;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.io.TempDir;
+
+import java.io.IOException;
+import java.nio.file.Path;
+
+import static org.assertj.core.api.AssertionsForClassTypes.assertThat;
+
```
Comment (luoyuxia) [inline fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/RemoteStorageHandlerTest.java]: Please add comments for this class... Otherwise, checkstyle will fail

File: fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/TableManagerTest.java [hunk 12]
```diff
@@ -159,6 +172,9 @@ void testDeleteTable() throws Exception {
         assertThat(zookeeperClient.getTableAssignment(tableId)).isEmpty();
         // the table will also be removed from coordinator context
         assertThat(coordinatorContext.getAllReplicasForTable(tableId)).isEmpty();
+
+        // the table's remote kv root dir should be removed.
+        assertThat(remoteStorageHandler.isTableKvDirExists(DATA1_TABLE_PATH_PK, tableId)).isFalse();
```
Comment (luoyuxia) [inline fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/TableManagerTest.java]: Also add IT to make sure drop table will also delete kv remote dir.
Maybe we can add in `KvSnapshotITCase`

**Review by luoyuxia — COMMENTED** [review]
@Vipamp Thanks for the pr. Left some comments. PTAL

**Comment by Vipamp** [comment]
> @Vipamp Thanks for the pr. Left some comments. PTAL

Thinks for your comments，i will update those codes later.

**Comment by Vipamp** [comment]
@luoyuxia Hi,  I have updated those code, PTAL, thinks.

File: fluss-server/src/test/java/com/alibaba/fluss/server/replica/KvSnapshotITCase.java [hunk 13]
```diff
@@ -68,16 +74,25 @@ class KvSnapshotITCase {
...
+                coordinatorServer.getClass().getDeclaredField("coordinatorEventProcessor");
+        coordinatorEventProcessorField.setAccessible(true);
+        eventProcessor =
+                (CoordinatorEventProcessor) coordinatorEventProcessorField.get(coordinatorServer);
+        remoteDataDir = FLUSS_CLUSTER_EXTENSION.getRemoteDataDir();
     }
 
     @Test
-    void testKvSnapshot() throws Exception {
+    void testKvSnapshotAndDeleteForTabletServer() throws Exception {
```
Comment (luoyuxia) [inline fluss-server/src/test/java/com/alibaba/fluss/server/replica/KvSnapshotITCase.java]:
```suggestion
    void testKvSnapshotAndDelete() throws Exception {
```

File: fluss-server/src/test/java/com/alibaba/fluss/server/replica/KvSnapshotITCase.java [hunk 14]
```diff
@@ -68,16 +74,25 @@ class KvSnapshotITCase {
...
+    private String remoteDataDir;
 
     @BeforeEach
-    void beforeEach() {
+    void beforeEach() throws NoSuchFieldException, IllegalAccessException {
         completedSnapshotHandleStore =
                 new ZooKeeperCompletedSnapshotHandleStore(
                         FLUSS_CLUSTER_EXTENSION.getZooKeeperClient());
+        CoordinatorServer coordinatorServer = FLUSS_CLUSTER_EXTENSION.getCoordinatorServer();
+        Field coordinatorEventProcessorField =
```
Comment (luoyuxia) [inline fluss-server/src/test/java/com/alibaba/fluss/server/replica/KvSnapshotITCase.java]: It's hack to get `CoordinatorEventProcessor` by reflection..

File: fluss-server/src/test/java/com/alibaba/fluss/server/replica/KvSnapshotITCase.java [hunk 15]
```diff
@@ -191,6 +206,103 @@ private void checkBucketDirsDeleted(Set<File> bucketDirs) {
...
+                // use retry here because the follower min retain offset is updated asynchronously
+                retry(
+                        Duration.ofMinutes(1),
+                        () ->
+                                assertThat(replica.getLogTablet().getMinRetainOffset())
+                                        .as("Replica %s min retain offset", replica)
+                                        .isEqualTo(6));
+            }
+        }
+        eventProcessor.process(new DropTableEvent(tableId, false));
```
Comment (luoyuxia) [inline fluss-server/src/test/java/com/alibaba/fluss/server/replica/KvSnapshotITCase.java]: Can we just use `CoordinatorService#dropTable` to mock the deletion of table? Move the logic to test method `testKvSnapshotAndDeleteForTabletServer` so that
1: the test can be removed
2: we can remove the code in method `testKvSnapshotAndDeleteForTabletServer`
```
CompletableFuture<List<StopReplicaResultForBucket>> future =
                        new CompletableFuture<>();
                server.getReplicaManager()
                        .stopReplicas(
                                INITIAL_COORDINATOR_EPOCH,
                                Collections.singletonList(
                                        new StopReplicaData(
                                                tableBucket, true, INITIAL_COORDINATOR_EPOCH, 1)),
                                future::complete);
```
and replace it with method `CoordinatorService#dropTable` directly to simpify the testing..

**Review by luoyuxia — COMMENTED** [review]
@Vipamp Thanks for updating.. Left minor comments.. Should be ready to be merged in next iteration..

**Comment by Vipamp** [comment]
hi, @luoyuxia I have updated the codes, PTAL, thinks.

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageCleaner.java [hunk 16]
```diff
@@ -0,0 +1,70 @@
...
+    private final FileSystem remoteFileSystem;
+
+    public RemoteStorageCleaner(Configuration configuration) throws IOException {
+        this.remoteKvDir = FlussPaths.remoteKvDir(configuration);
+        this.remoteLogDir = FlussPaths.remoteLogDir(configuration);
+        this.remoteFileSystem = remoteKvDir.getFileSystem();
+    }
+
+    public void deleteTableRemoteDir(TablePath tablePath, long tableId) {
+        deleteDir(tableKvRemoteDir(tablePath, tableId));
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageCleaner.java]: If it's append only table, we can skip delete kv remote dir..
We can get `TableInfo` by `tablePath` in `CoordinatorContext#tableInfoById` to know whether it's append only table or not.

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageCleaner.java [hunk 17]
```diff
@@ -0,0 +1,70 @@
...
+        deleteDir(tableLogRemoteDir(tablePath, tableId));
+    }
+
+    private void deleteDir(FsPath fsPath) {
+        try {
+            if (remoteFileSystem.exists(fsPath)) {
+                remoteFileSystem.delete(fsPath, true);
+                LOG.info("Delete table's remote dir {} success.", fsPath);
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageCleaner.java]: Could you please print the time cost to delete a table remote data dir.. I'm concerned that it'll cost too much time..Such as:

LOG.info("Delete table's remote data dir {} success, cost {}ms.", fsPath);

File: fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageCleaner.java [hunk 18]
```diff
@@ -0,0 +1,70 @@
...
+            }
+        } catch (IOException e) {
+            LOG.error("Delete table's remote dir {} failed.", fsPath, e);
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageCleaner.java]:
```suggestion
            LOG.error("Delete table's remote data dir {} failed.", fsPath, e);
```

**Review by luoyuxia — COMMENTED** [review]
@Vipamp Thanks for updating.. Left minor comments again..

**Comment by Vipamp** [comment]
> @Vipamp Thanks for updating.. Left minor comments again..

hi， @luoyuxia i will do it later.

**Comment by Vipamp** [comment]
@luoyuxia hi, I have updated the codes with conflicts, PTAL, thinks.

**Comment by luoyuxia** [comment]
@Vipamp Hi, I append a commit to use a dedicated ioExecutor to delete files to avoid block CoordinatorEventProcessor..Please take a look, if you have no any other comments, I'll merge then.. Thanks.

**Comment by Vipamp** [comment]
> @Vipamp Hi, I append a commit to use a dedicated ioExecutor to delete files to avoid block CoordinatorEventProcessor..Please take a look, if you have no any other comments, I'll merge then.. Thanks.

hi, @luoyuxia it's ready to merge, thinks.
