### PR TITLE
[client] RemoteLogDownloader should increment remoteFetchBytesPerSecond of ScannerMetricGroup

### LINKED ISSUE #857: RemoteLogDownloader does not increment remoteFetchBytesPerSecond of ScannerMetricGroup
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.6.0 (latest release)

### Please describe the bug 🐞

`RemoteLogDownloader` does not increment `remoteFetchBytesPerSecond` of `ScannerMetricGroup` at present, which causes that the value of `remoteFetchBytesPerSecond` metric is always zero.

### Solution

`RemoteLogDownloader` should increment `remoteFetchBytesPerSecond` of `ScannerMetricGroup`.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by SteNicholas**
### Purpose

Linked issue: close #857

`RemoteLogDownloader` does not increment `remoteFetchBytesPerSecond` of `ScannerMetricGroup` at present, which causes that the value of `remoteFetchBytesPerSecond` metric is always zero.

### Brief change log

`RemoteLogDownloader` should increment `remoteFetchBytesPerSecond` of `ScannerMetricGroup`.

### Tests

`RemoteLogDownloaderTest#testPrefetchNum`.

### API and Format

No.

### Documentation

No.

### CODE REVIEW

File: fluss-client/src/test/java/com/alibaba/fluss/client/table/scanner/log/RemoteLogDownloaderTest.java [hunk 1]
```diff
@@ -163,4 +172,19 @@ private static List<RemoteLogSegment> buildRemoteLogSegmentList(
         }
         return remoteLogSegmentList;
     }
+
+    private static Long remoteLogSegmentFilesLength(
+            List<RemoteLogSegment> remoteLogSegments, FsPath remoteLogTabletDir, int segmentNum) {
+        return remoteLogSegments.stream()
+                .limit(segmentNum)
+                .mapToLong(
+                        segment ->
```
Comment (wuchong) [inline fluss-client/src/test/java/com/alibaba/fluss/client/table/scanner/log/RemoteLogDownloaderTest.java:181]: We can get the bytes length via `RemoteLogSegment#segmentSizeInBytes`.

**Review by wuchong — COMMENTED** [review]
I only left one minor comment.

File: fluss-client/src/test/java/com/alibaba/fluss/client/table/scanner/log/RemoteLogDownloaderTest.java (hunk 1 above)
Comment (SteNicholas) [reply fluss-client/src/test/java/com/alibaba/fluss/client/table/scanner/log/RemoteLogDownloaderTest.java:181]: @wuchong, `RemoteLogSegment#segmentSizeInBytes` is set with `Integer.MAX_VALUE`. Therefore, we could get the length of the log segment file.
