### PR TITLE
[server] AutoPartitionManager shouldn't create partitions for dropped table

### LINKED ISSUE #712: The table id in table zknode is not same with the partition id in the children node of the table in zk
### Search before asking

- [x] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.6.0 (latest release)

### Please describe the bug 🐞

Drop a table and create a table with the same table t1. Then it may happen  in zk that the `t1` zk node is with table id 12, but the children partition node is with table id 11. Then in client, the following exception will happen: 
```
Caused by: java.lang.IllegalArgumentException: table path not found for tableId 11 in cluster
	at com.alibaba.fluss.cluster.Cluster.lambda$getTablePathOrElseThrow$1(Cluster.java:177)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.alibaba.fluss.cluster.Cluster.getTablePathOrElseThrow(Cluster.java:175)
	at com.alibaba.fluss.client.utils.MetadataUtils.lambda$getTableMetadataToUpdate$3(MetadataUtils.java:221)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.alibaba.fluss.client.utils.MetadataUtils.getTableMetadataToUpdate(MetadataUtils.java:217)
	at com.alibaba.fluss.client.utils.MetadataUtils.lambda$sendMetadataRequestAndRebuildCluster$1(MetadataUtils.java:122)
```
It happens with following steps:
1. create tablet t1 with id 11
2. drop tablet t1
3. coordinator listen the t1 is created, do auto partition, create the partition in the zk path `tables/t1/partitions/p1` with table id 11
4. coordinator listen the t1 is dropped, just remove t1 id = 11 remove `AutoPartitionManager`.
5. create tablet t1 with id 12, upsert the zk path `tables/t1` with table id 12
So the inconsistent happens.

### Solution

Seems we should drop the partitions in step 4 after we listen the table `t1` is dropped.
If we don't drop the partitions, it may cause partition leak.

1. create tablet t1 with id 11
2. drop tablet t1
3. coordinator listen the t1 is created, do auto partition 
4. coordinator listen the t1 is dropped
Note, the partitions created in step 3  won't be dropped then.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by wuchong**
### Purpose

Linked issue: close #712

This is a simple fix for #712 that during auto-partition creating it should first check if the table is dropped or re-created before creating partitions. This still don't guarantes the table id consist between the table node and partition node, because the table maybe re-created after the checking... But this should happen very rarely and is tracked in https://github.com/alibaba/fluss/issues/767.

### CODE REVIEW

File: fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java [hunk 1]
```diff
@@ -418,6 +418,11 @@ public int getPartitionNumber(TablePath tablePath) throws Exception {
         return stat.getNumChildren();
     }
 
+    public void createPartitionsPath(TablePath tablePath) throws Exception {
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java]: Seems this method is not used?

**Review by luoyuxia — COMMENTED** [review]
@wuchong Just one minor comment. LGTM.
I believe that the table maybe re-created after the checking is very rarely and it should resolve all most all cases.

File: fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java (hunk 1 above)
Comment (wuchong) [reply fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java]: Good catch!

**Comment by wuchong** [comment]
@luoyuxia , I have addressed the comments and resolved the conflicts. Please take another look.

**Review by luoyuxia — APPROVED** [review]
LGTM！
