### PR TITLE
[common] Fix IndexOutOfBoundsException in ArrowArrayWriter when element count exceeds INITIAL_CAPACITY

### LINKED ISSUE #2164: [Bug] IndexOutOfBoundsException when writing rows with array columns to KV table
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

main (development)

### Minimal reproduce step

Write data containing array columns to a Fluss KV table where:
1. The number of rows is less than 1024 (INITIAL_CAPACITY)
2. The total number of array elements across all rows exceeds 1024

For example: 250 rows with arrays containing 10 integers each (total 2500 elements).

### What do you expect to see?

Data should be written successfully without errors.

### What did you see instead?

```
java.lang.IndexOutOfBoundsException: index: 248, length: 1 (expected: range(0, 248))
    at org.apache.fluss.shaded.arrow.org.apache.arrow.memory.ArrowBuf.checkIndexD(ArrowBuf.java:319)
    at org.apache.fluss.shaded.arrow.org.apache.arrow.memory.ArrowBuf.chk(ArrowBuf.java:306)
    at org.apache.fluss.shaded.arrow.org.apache.arrow.memory.ArrowBuf.getByte(ArrowBuf.java:508)
    at org.apache.fluss.shaded.arrow.org.apache.arrow.vector.BitVectorHelper.setBit(BitVectorHelper.java:82)
    at org.apache.fluss.shaded.arrow.org.apache.arrow.vector.IntVector.set(IntVector.java:160)
    at org.apache.fluss.row.arrow.writers.ArrowIntWriter.doWrite(ArrowIntWriter.java:38)
    at org.apache.fluss.row.arrow.writers.ArrowFieldWriter.write(ArrowFieldWriter.java:59)
    at org.apache.fluss.row.arrow.writers.ArrowArrayWriter.doWrite(ArrowArrayWriter.java:44)
    ...
```

### Root Cause Analysis

In `ArrowWriter.writeRow()`, the `handleSafe` flag is determined by comparing `recordsCount` (number of rows) against `INITIAL_CAPACITY` (1024):

```java
boolean handleSafe = recordsCount >= INITIAL_CAPACITY;
```

When handleSafe = false, Arrow writers use vector.set() which doesn't auto-grow the underlying buffer. When handleSafe = true, they use vector.setSafe() which auto-grows as needed.

The bug is in ArrowArrayWriter: it passes the parent's handleSafe flag (based on row count) to the element writer. However, array element indices are based on the cumulative element count across all arrays, not the row count. This means:

250 rows → handleSafe = false (since 250 < 1024)
But with 10 elements per array, element indices can reach 2500
The element vector was only initialized for 1024 elements
Arrow throws IndexOutOfBoundsException when writing element 1024+

### Solution

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by binary-signal**
## Purpose

Linked issue: close #2164 

Fix `IndexOutOfBoundsException` when writing rows with array columns where the total number of array elements exceeds `INITIAL_CAPACITY` (1024) while the row count stays below it.

### Brief change log

In `ArrowWriter.writeRow()`, the `handleSafe` flag is determined by comparing row count against `INITIAL_CAPACITY`:
```java
boolean handleSafe = recordsCount >= INITIAL_CAPACITY;
```

When `handleSafe = false`, Arrow writers use `vector.set()` which doesn't auto-grow the buffer. The bug is in `ArrowArrayWriter.doWrite()` which passes the parent's `handleSafe` flag to the element writer. However, array element indices grow based on cumulative element count, not row count.

Example: 250 rows with 10-element arrays → row count (250) < 1024 so `handleSafe = false`, but total elements (2500) exceeds the vector's initial capacity, causing `IndexOutOfBoundsException`.

**Fix:**
Always use safe writes (`handleSafe = true`) for array element writers in `ArrowArrayWriter.doWrite()`, since element indices can exceed `INITIAL_CAPACITY` independently of row count.

```java
// Before
elementWriter.write(fieldIndex, array, arrIndex, handleSafe);

// After
elementWriter.write(fieldIndex, array, arrIndex, true);
```

### Tests

- Added `ArrowReaderWriterTest#testArrayWriterWithManyElements`: writes 200 rows with 10-element arrays (2000 total elements), verifying serialization succeeds and data can be read back correctly.

### API and Format

No API or storage format changes.

### Documentation

No documentation changes needed. This is a bug fix.
```

### CODE REVIEW

File: fluss-common/src/main/java/org/apache/fluss/row/arrow/writers/ArrowArrayWriter.java [hunk 1]
```diff
@@ -41,7 +41,11 @@ public void doWrite(int rowIndex, DataGetters row, int ordinal, boolean handleSa
         listVector.startNewValue(rowIndex);
         for (int arrIndex = 0; arrIndex < array.size(); arrIndex++) {
             int fieldIndex = offset + arrIndex;
-            elementWriter.write(fieldIndex, array, arrIndex, handleSafe);
+            // Always use safe writes for array elements because the element index (offset +
```
Comment (vamossagar12) [inline fluss-common/src/main/java/org/apache/fluss/row/arrow/writers/ArrowArrayWriter.java]: We should mention in the comments on the class that the handleSafe field is ignored when writing.

**Review by vamossagar12 — APPROVED** [review]
LGTM

File: fluss-common/src/main/java/org/apache/fluss/row/arrow/writers/ArrowArrayWriter.java [hunk 2]
```diff
@@ -41,7 +41,11 @@ public void doWrite(int rowIndex, DataGetters row, int ordinal, boolean handleSa
...
+            // arrIndex) can exceed INITIAL_CAPACITY even when the row count doesn't. The parent's
+            // handleSafe is based on row count, but array element indices grow based on the total
+            // number of elements across all arrays, which can be much larger.
+            elementWriter.write(fieldIndex, array, arrIndex, true);
```
Comment (platinumhamburg) [inline fluss-common/src/main/java/org/apache/fluss/row/arrow/writers/ArrowArrayWriter.java]:
```suggestion
            boolean elementHandleSafe = fieldIndex >= ArrowWriter.INITIAL_CAPACITY;
            elementWriter.write(fieldIndex, array, arrIndex, elementHandleSafe);
```

Comment (platinumhamburg) [reply fluss-common/src/main/java/org/apache/fluss/row/arrow/writers/ArrowArrayWriter.java]: Perhaps we could apply a clear conditional judgment here.

**Comment by platinumhamburg** [comment]
+1，just a minor suggestion

**Review by wuchong — APPROVED** [review]
I appended a commit from @platinumhamburg #2287 to improve the fix.

**Review by platinumhamburg — APPROVED** [review]
