### PR TITLE
[server/kv]fix bug for deleting remote kv dir

### LINKED ISSUE #121: [Bug] Dropping primary key table doesn't delete kv snapshot
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

fluss 0.5

### Minimal reproduce step

Create a primary key table, wait the snapshot is generated, and then drop it.

### What doesn't meet your expectations?

The  kv snapshot is not deleted

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Vipamp**
### Purpose

Linked issue: close #121 
this pr is aims to solve the bug mentioned in #121

### CODE REVIEW

File: fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java [hunk 1]
```diff
@@ -270,4 +288,41 @@ public KvTablet loadKv(File tabletDir) throws Exception {
...
+            }
+        } catch (Exception e) {
+            throw new RemoteStorageException(
+                    "Failed to delete remote kv tablet path:" + remoteKvTabletDir, e);
+        }
+        deleteEmptyParentRecursively(
+                remoteKvTabletDir.getParent(), remoteKvTableRootDir.getParent());
+    }
+
+    private void deleteEmptyParentRecursively(FsPath curDir, FsPath tableRootParentDir) {
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java]: We shouldn't remove the table parent dir (i.e., the database dir), as it is just a table removal, not database removal. Even if the database is empty, we shouldn't remove it. 

We shouldn't remove the table dir in TabletServer, as it is only responsive for a single bucket. The removing of table dir should be done in Coordinator when all buckets are removed.

File: fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java [hunk 2]
```diff
@@ -85,6 +93,12 @@ private KvManager(
         this.arrowBufferAllocator = new RootAllocator(Long.MAX_VALUE);
         this.memorySegmentPool = LazyMemorySegmentPool.create(conf);
         this.zkClient = zkClient;
+        this.remoteKvDir = FlussPaths.remoteKvDir(conf);
+        try {
+            this.remoteFileSystem = remoteKvDir.getFileSystem();
+        } catch (Exception e) {
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java]: Just throw the `IOException`, this should block the server from starting as it doesn't work if the filesystem is not initialized.

File: fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java [hunk 3]
```diff
@@ -187,14 +201,18 @@ public Optional<KvTablet> getKv(TableBucket tableBucket) {
...
+            PhysicalTablePath physicalTablePath, TableBucket tableBucket, boolean deleteRemote) {
         KvTablet dropKvTablet =
                 inLock(tabletCreationOrDeletionLock, () -> currentKvs.remove(tableBucket));
 
         if (dropKvTablet != null) {
             TablePath tablePath = dropKvTablet.getTablePath();
             try {
                 dropKvTablet.drop();
+                if (deleteRemote) {
+                    dropRemoteKvSnapshot(physicalTablePath, tableBucket);
```
Comment (wuchong) [inline fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java]: This removal is very similar to remote log removal. We can move this invoking `KvManager.dropRemoteKvSnapshot` into `ReplicaManager#stopReplica` after `remoteLogManager.stopReplica`. Ideally, we should delete the remote files (log&kv) asynchronously to not block the worker thread. We can refactor them in the near future.

**Review by wuchong — CHANGES_REQUESTED** [review]
Please add unit tests or IT cases to verify the fixing. An ideal place to add IT cases is `KvSnapshotITCase`.

File: fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java (hunk 1 above)
Comment (Vipamp) [reply fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java]: Thank you for noticing this detail,it only delete bucket dir until table dir is empty and empty table dir will be deleted, the database dir won't be deleted even if it's empty.
i will update this code for deleting table dir by coordinate server, thinks for your guidance.

File: fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java (hunk 2 above)
Comment (Vipamp) [reply fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java]: i will update this code.

File: fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java (hunk 3 above)
Comment (Vipamp) [reply fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java]: Yes,i have notice that，I find RemoteLogManager to manager remote files of LogTable without RemoteKvManager to manager snapshot files of KvTable，is there any plan  to unify those for managering remote files? I will continue to pay attention about it and look forward to participating it.

**Comment by Vipamp** [comment]
> Please add unit tests or IT cases to verify the fixing. An ideal place to add IT cases is `KvSnapshotITCase`. 

Thank you for your guidance，I will add it.

**Comment by Vipamp** [comment]
@wuchong PTAL，thinks

File: fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/PeriodicSnapshotManager.java [hunk 4]
```diff
@@ -177,34 +177,36 @@ public void triggerSnapshot() {
...
-                                                runnable.getSnapshotLocation(),
-                                                runnable.getSnapshotRunnable()));
-                    } else {
-                        scheduleNextSnapshot();
-                        LOG.debug(
-                                "TableBucket {} has no data updates since last snapshot, "
-                                        + "skip this one and schedule the next one in {} seconds",
-                                tableBucket,
-                                periodicSnapshotDelay / 1000);
+                    if (started && !periodicExecutor.isShutdown()) {
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/PeriodicSnapshotManager.java]: Why add `if (started && !periodicExecutor.isShutdown())` in here?

File: fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java [hunk 5]
```diff
@@ -1239,6 +1239,10 @@ private StopReplicaResultForBucket stopReplica(
             }
 
             remoteLogManager.stopReplica(replicaToDelete, delete && replicaToDelete.isLeader());
+            if (delete) {
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java]: Only replica leader need to drop remote kv snapshot.... 
=> `if (delete && replicaToDelete.isLeader())`

File: fluss-server/src/test/java/com/alibaba/fluss/server/replica/KvSnapshotITCase.java [hunk 6]
```diff
@@ -85,6 +93,7 @@ void testKvSnapshot() throws Exception {
             }
         }
 
+        Set<File> bucketDirs = new HashSet<>();
```
Comment (luoyuxia) [inline fluss-server/src/test/java/com/alibaba/fluss/server/replica/KvSnapshotITCase.java]: nit: bucketDirs -> bucketKvSnapshotDirs?

File: fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java [hunk 7]
```diff
@@ -270,4 +281,17 @@ public KvTablet loadKv(File tabletDir) throws Exception {
         this.currentKvs.put(tableBucket, kvTablet);
         return kvTablet;
     }
+
+    public void dropRemoteKvSnapshot(PhysicalTablePath physicalTablePath, TableBucket tableBucket) {
```
Comment (luoyuxia) [inline fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java]: nit:
dropRemoteKvSnapshot -> deleteRemoteKvSnapshot
as we also use `delete` for log....

**Review by luoyuxia — COMMENTED** [review]
@Vipamp Thanks for the pr... Left minor comments..PTAL

File: fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java (hunk 1 above)
Comment (luoyuxia) [reply fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java]: > deleting table dir by coordinate server

Seems deleting table dir by coordinate server is missing in this pr? Right?

File: fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/PeriodicSnapshotManager.java (hunk 4 above)
Comment (Vipamp) [reply fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/PeriodicSnapshotManager.java]: For periodicExecutor summitting snapshot trigger with delay，after bucket deleted and `started` change to false, the snapshot trigger will execute again for last time and generate an empty snapshot, the remote bucket dir will be created again，so i add this code for avoiding this case.

Comment (luoyuxia) [reply fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/PeriodicSnapshotManager.java]: Thanks for the explanation...Make sense to me..But we won't need to check `!periodicExecutor.isShutdown()`, it `periodicExecutor.isShutdown()`, the task won't be scheduled..

**Comment by Vipamp** [comment]
@luoyuxia Comments addressed again and create issue #296 for deleting table remote dir by coordinator  server, PTAL, thinks.

**Review by luoyuxia — APPROVED** [review]
Thanks for update...LGTM!
