### PR TITLE
[lake/paimon] Prohibit users from setting Paimon properties that Fluss depends on

### LINKED ISSUE #1824: [lake] The default configuration of the Lake tables that Fluss depends on can be tampered with
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

main (development)

### Please describe the bug 🐞

When enable a lake (such as Paimon) table for a Fluss table, Fluss will set some default configs for the corresponding Paimon table, such as `bucket = -1` for log table without bucket keys. These configs suppose to be set by Fluss while not by users. If the user sets these properties, it will cause problems with the lakehouse synchronization.

For examle:
```java
    @Test
    void test() throws Exception {
        Map<String, String> customProperties = new HashMap<>();
        customProperties.put("k1", "v1");
        customProperties.put("paimon.file.format", "parquet");
        customProperties.put("paimon.bucket", "112");
        customProperties.put("paimon.bucket-key", "log_c1");

        TableDescriptor logTable =
                TableDescriptor.builder()
                        .schema(
                                Schema.newBuilder()
                                        .column("log_c1", DataTypes.INT())
                                        .column("log_c2", DataTypes.STRING())
                                        .build())
                        .property(ConfigOptions.TABLE_DATALAKE_ENABLED, true)
                        .customProperties(customProperties)
                        .distributedBy(3, "log_c1", "log_c2")
                        .build();
        TablePath logTablePath = TablePath.of(DATABASE, "log_table");
        admin.createTable(logTablePath, logTable, false).get();
        Table paimonLogTable =
                paimonCatalog.getTable(Identifier.create(DATABASE, logTablePath.getTableName()));

        System.out.println(paimonLogTable.options());
    }
```

We expect to get a Paimon table with the same bucket count as Fluss table. But we actually got a Paimon table with 112 buckets.
```
{bucket=112, path=..., fluss.table.datalake.enabled=true, fluss.table.datalake.format=paimon, partition.legacy-name=false, bucket-key=log_c1, file.format=parquet, fluss.k1=v1}

```

### Solution

We need to prevent users from setting these configs. 

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by LiebingYu**
### Purpose

Linked issue: close #1824

### CODE REVIEW

File: fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/utils/PaimonConversions.java [hunk 1]
```diff
@@ -17,26 +17,58 @@
...
+
+    /** Paimon config options set by Fluss should not be set by users. */
+    @VisibleForTesting public static final Set<String> PAIMON_UNSETTABLE_OPTIONS = new HashSet<>();
+
+    @VisibleForTesting public static final Options PAIMON_DEFAULT_OPTIONS = new Options();
+
+    static {
+        PAIMON_UNSETTABLE_OPTIONS.add(CoreOptions.BUCKET.key());
+        PAIMON_UNSETTABLE_OPTIONS.add(CoreOptions.BUCKET_KEY.key());
+        PAIMON_UNSETTABLE_OPTIONS.add(CoreOptions.CHANGELOG_PRODUCER.key());
```
Comment (luoyuxia) [inline fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/utils/PaimonConversions.java]: I think we can make `CHANGELOG_PRODUCER` to be changed by users in case some users may don't want fluss generate change log? WDYT?

File: fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/utils/PaimonConversions.java [hunk 2]
```diff
@@ -17,26 +17,58 @@
...
 
+    // for fluss config
+    private static final String FLUSS_CONF_PREFIX = "fluss.";
+    // for paimon config
+    private static final String PAIMON_CONF_PREFIX = "paimon.";
+
+    /** Paimon config options set by Fluss should not be set by users. */
+    @VisibleForTesting public static final Set<String> PAIMON_UNSETTABLE_OPTIONS = new HashSet<>();
+
+    @VisibleForTesting public static final Options PAIMON_DEFAULT_OPTIONS = new Options();
```
Comment (luoyuxia) [inline fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/utils/PaimonConversions.java]: I suggest to remove PAIMON_DEFAULT_OPTIONS, put `PARTITION_GENERATE_LEGCY_NAME` into  `PAIMON_UNSETTABLE_OPTIONS`. 
And hard code 
```
options.set(CoreOptions.PARTITION_GENERATE_LEGCY_NAME, false);
```
direclty. Introduce two options make me hard to figure out what that mean.

File: fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/utils/PaimonConversions.java [hunk 3]
```diff
@@ -104,4 +135,111 @@ public static List<SchemaChange> toPaimonSchemaChanges(
...
+                        throw new InvalidConfigException(
+                                String.format(
+                                        "The Paimon option %s will be set automatically by Fluss "
+                                                + "and should not set manually.",
+                                        k));
+                    }
+                });
+    }
+
+    private static void setPaimonDefaultProperties(Options options) {
```
Comment (luoyuxia) [inline fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/utils/PaimonConversions.java:219]: nit:
`convertFlussPropertyKeyToPaimon`

**Review by luoyuxia — COMMENTED** [review]
@LiebingYu Thanks for the pr. Left minor comments. PTAL

File: fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/utils/PaimonConversions.java (hunk 1 above)
Comment (LiebingYu) [reply fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/utils/PaimonConversions.java]: When do users need to change the `CHANGELOG_PRODUCER `? Fluss will generate the CDC logs and I think we should always use `INPUT` for Fluss lake table?
