### PR TITLE
Fix Lance writer to emit Arrow FixedSizeList for array columns to enable native vector search

### LINKED ISSUE #2706: [lake/lance] Lance writer should emit Arrow FixedSizeList for array columns to enable native vector search
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

main (development)

### Please describe the bug 🐞

When tiering tables with ARRAY<FLOAT> columns to Lance, Fluss always writes them as Arrow's variable-length List<Float32>. This prevents Lance's native vector search (nearest / ANN index) from working, since Lance requires FixedSizeList<Float32>(n) for vector columns.

This seems to be due to LanceArrowUtils.toArrowType(), ArrayType unconditionally maps to ArrowType.List.INSTANCE:

```java
  // fluss-lake/fluss-lake-lance/src/main/java/org/apache/fluss/lake/lance/utils/LanceArrowUtils.java:140
  } else if (dataType instanceof ArrayType) {
      return ArrowType.List.INSTANCE;
  }
```

### Solution

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by leekeiabstraction**
### Purpose

Linked issue: close #2706

Fix Lance writer to emit Arrow FixedSizeList for array columns to enable native vector search.

Querying with pylance native vector search fails because pylance expects embedding column to be of fixedSizeList type instead of variable size list. This PR fixes the conversion from Fluss' arrow data to Lance's arrow data by using FixedSizeList if `<column>.arrow.fixed-size-list.size` is defined, similar to how Spark SQL does it ref: https://lance.org/integrations/spark/operations/ddl/create-table/#creating-large-string-columns

### Tests

Added unit test
- Tested manually that pylance successfully performed a vector search on the tiered data

### CODE REVIEW

**Comment by leekeiabstraction** [comment]
@XuQianJin-Stars Appreciate if you can review this PR 🙏

**Comment by leekeiabstraction** [comment]
Addressed Co-pilot comments, also fixed a memory leak that could occur if exception is thrown during conversion from shaded to non-shaded objects.

File: fluss-lake/fluss-lake-lance/src/main/java/org/apache/fluss/lake/lance/LanceLakeCatalog.java [hunk 1]
```diff
@@ -61,7 +61,9 @@ public void createTable(TablePath tablePath, TableDescriptor tableDescriptor, Co
         List<Field> fields = new ArrayList<>();
         // set schema
         fields.addAll(
-                LanceArrowUtils.toArrowSchema(tableDescriptor.getSchema().getRowType())
+                LanceArrowUtils.toArrowSchema(
+                                tableDescriptor.getSchema().getRowType(),
+                                tableDescriptor.getCustomProperties())
```
Comment (XuQianJin-Stars) [inline fluss-lake/fluss-lake-lance/src/main/java/org/apache/fluss/lake/lance/LanceLakeCatalog.java:66]: Need to confirm the return type of `getCustomProperties()`. If it returns an immutable Map or a Properties type rather than `Map<String, String>`, will `tableProperties.get(fieldName + FIXED_SIZE_LIST_SIZE_SUFFIX)` in toArrowField work correctly? Suggest using `Map<String, String>` in the new method signature and ensuring compatibility at the call site.

File: fluss-lake/fluss-lake-lance/src/main/java/org/apache/fluss/lake/lance/utils/LanceArrowUtils.java [hunk 2]
```diff
@@ -47,31 +47,76 @@
...
+import static org.apache.fluss.utils.Preconditions.checkArgument;
+
 /**
  * Utilities for converting Fluss RowType to non-shaded Arrow Schema. This is needed because Lance
  * requires non-shaded Arrow API.
  */
 public class LanceArrowUtils {
 
+    /** Property suffix for configuring a fixed-size list Arrow type on array columns. */
+    public static final String FIXED_SIZE_LIST_SIZE_SUFFIX = ".arrow.fixed-size-list.size";
```
Comment (XuQianJin-Stars) [inline fluss-lake/fluss-lake-lance/src/main/java/org/apache/fluss/lake/lance/utils/LanceArrowUtils.java:62]: The property key format is <column_name>.arrow.fixed-size-list.size. If the column name itself contains . (e.g., a.b), it leads to parsing ambiguity. For example, a.b.arrow.fixed-size-list.size — it's unclear whether this refers to column a.b or column a with some unrelated suffix.

Suggestion:
1. Explicitly document that column names must not contain `.`; or
2. Validate in toArrowField that the column name does not contain ., and throw a meaningful error message if it does.

File: fluss-lake/fluss-lake-lance/src/main/java/org/apache/fluss/lake/lance/utils/LanceArrowUtils.java [hunk 3]
```diff
@@ -47,31 +47,76 @@
...
+            String fieldName, DataType logicalType, Map<String, String> tableProperties) {
+        ArrowType arrowType;
+        if (logicalType instanceof ArrayType && tableProperties != null) {
+            String sizeStr = tableProperties.get(fieldName + FIXED_SIZE_LIST_SIZE_SUFFIX);
+            if (sizeStr != null) {
+                int listSize = -1;
+                try {
+                    listSize = Integer.parseInt(sizeStr);
+                } catch (NumberFormatException ignored) {
+                    // Not really ignored, IllegalArgumentEx still thrown below.
```
Comment (XuQianJin-Stars) [inline fluss-lake/fluss-lake-lance/src/main/java/org/apache/fluss/lake/lance/utils/LanceArrowUtils.java]: Validating for a positive integer is correct. However, if the property value is an empty string "" or whitespace " ", Integer.parseInt will throw a NumberFormatException without a user-friendly error message. Suggest catching NumberFormatException and converting it to an IllegalArgumentException that includes the property key name, making it easier for users to locate the configuration issue.
```
int listSize;
try {
    listSize = Integer.parseInt(sizeStr);
} catch (NumberFormatException e) {
    throw new IllegalArgumentException(
        String.format("Invalid value '%s' for property '%s', expected a positive integer.",
            sizeStr, fieldName + FIXED_SIZE_LIST_SIZE_SUFFIX), e);
}
checkArgument(listSize > 0, "...");
```

File: fluss-lake/fluss-lake-lance/src/test/java/org/apache/fluss/lake/lance/tiering/LanceTieringTest.java [hunk 4]
```diff
@@ -233,6 +246,13 @@ private void verifyLogTableRecords(
                     .isEqualTo(expectRecord.getRow().getString(1).toString());
             assertThat(((VarCharVector) root.getVector(2)).getObject(i).toString())
                     .isEqualTo(expectRecord.getRow().getString(2).toString());
+            // check embedding column
+            java.util.List<?> embeddingValues = embeddingVector.getObject(i);
+            assertThat(embeddingValues).hasSize(EMBEDDING_LIST_SIZE);
+            org.apache.fluss.row.InternalArray expectedArray = expectRecord.getRow().getArray(3);
+            for (int j = 0; j < EMBEDDING_LIST_SIZE; j++) {
+                assertThat((Float) embeddingValues.get(j)).isEqualTo(expectedArray.getFloat(j));
```
Comment (XuQianJin-Stars) [inline fluss-lake/fluss-lake-lance/src/test/java/org/apache/fluss/lake/lance/tiering/LanceTieringTest.java:254]: Missing null value scenario in test data?

File: fluss-lake/fluss-lake-lance/src/main/java/org/apache/fluss/lake/lance/LanceLakeCatalog.java (hunk 1 above)
Comment (leekeiabstraction) [reply fluss-lake/fluss-lake-lance/src/main/java/org/apache/fluss/lake/lance/LanceLakeCatalog.java:66]: getCustomProperties() returns Map<String, String>

```java
    public Map<String, String> getCustomProperties() {
        return customProperties;
    }
```

File: fluss-lake/fluss-lake-lance/src/main/java/org/apache/fluss/lake/lance/utils/LanceArrowUtils.java (hunk 2 above)
Comment (leekeiabstraction) [reply fluss-lake/fluss-lake-lance/src/main/java/org/apache/fluss/lake/lance/utils/LanceArrowUtils.java:62]: Good comment, I actually look up Lance doc further and found that they do not support dots in columns. Ref: https://docs.lancedb.com/search/filtering#advanced-sql-filters

Updated to throw exception

File: fluss-lake/fluss-lake-lance/src/test/java/org/apache/fluss/lake/lance/tiering/LanceTieringTest.java (hunk 4 above)
Comment (leekeiabstraction) [reply fluss-lake/fluss-lake-lance/src/test/java/org/apache/fluss/lake/lance/tiering/LanceTieringTest.java:254]: Great comment. Testing for null actually surfaced a bug.

The fix did take me some time to get to..

**Comment by leekeiabstraction** [comment]
@XuQianJin-Stars Appreciate if you can review again

**Comment by XuQianJin-Stars** [comment]
> @XuQianJin-Stars Appreciate if you can review again

well

**Comment by XuQianJin-Stars** [comment]
LGTM
